### ISSUE TITLE
Lat, Lon values not proper

### ISSUE THREAD

**Issue by thinrhino** [cowinapi/developer.cowin#1]
In the response to the API `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id={}&date={}`
the value of the latitude and longitude is not proper. decimal place values are missing to get a accurate location of the vaccination center.
```
{'center_id': 674554,
 'name': 'Mandarboni SC',
 'state_name': 'West Bengal',
 'district_name': 'West Bardhaman',
 'block_name': 'Durgapur-Faridpur',
 'pincode': 713384,
 'lat': 87,
 'long': 23,
 'from': '09:00:00',
 'to': '18:00:00',
 'fee_type': 'Free',
 'sessions': [{'session_id': '45c934e2-6b78-48a6-b50f-cea9c88cd6f7',
   'date': '07-05-2021',
   'available_capacity': 0,
   'min_age_limit': 45,
   'vaccine': '',
   'slots': ['09:00AM-11:00AM',
    '11:00AM-01:00PM',
    '01:00PM-03:00PM',
    '03:00PM-06:00PM']}]}
```

**Comment by amitvsavant** [comment]
Yes, Please do not use the lat, lon values in the response. This information is mostly entered by vaccination site administrators and may be inocrrect. CoWIN team is in the process of correcting this information. Please ignore this until communicated.

**Comment by abhaira** [comment]
Why the issue is marked as closed, even though it is not fixed yet?

**Comment by gaurav8809** [comment]
@abhaira Correct
Open the issue again if it is not resolved

**Comment by jagadeeshchirasani** [comment]
> Yes, Please do not use the lat, lon values in the response. This information is mostly entered by vaccination site administrators and may be inocrrect. CoWIN team is in the process of correcting this information. Please ignore this until communicated.

Can you atleast change the datatype of those fields, even if the people enters the right data, you will not be able see the correct data. Please change it to float.
