### ISSUE TITLE
Introduce Captcha or some sort of means to prevent auto booking

### ISSUE THREAD

**Issue by avgcoderlife** [cowinapi/developer.cowin#10]
Its highly unethical that few folks have designed script to auto book slots !
We cannot defeat the bots - and its frustrating to see slots getting booked in seconds.

Some means of Captcha should be introduced to prevent bots from auto booking the slots ! Some are even boasting in twitter that they were able to get the slot via bot !

**Comment by satishchandra-pandey** [comment]
@avgcoderlife 
Can you please send us the linked in snapshot or URLs

**Comment by avgcoderlife** [comment]
https://twitter.com/umanghome/status/1388598049044267008
https://twitter.com/umanghome/status/1388743239671312384/photo/1

**Comment by avgcoderlife** [comment]
https://twitter.com/umanghome/status/1388598049044267008
https://twitter.com/umanghome/status/1388743239671312384/photo/1

Just a simple Captcha can solve this

**Comment by avgcoderlife** [comment]
https://twitter.com/darthdevi/status/1389603312895291395

**Comment by avgcoderlife** [comment]
https://twitter.com/umanghome/status/1388743239671312384

**Comment by avgcoderlife** [comment]
Simple captcha can prevent this !

**Comment by avgcoderlife** [comment]
https://twitter.com/peegeekay/status/1389074034520846338
Simple captcha can prevent this !

**Comment by avgcoderlife** [comment]
@satishchandra-pandey  : See this
https://github.com/pallupz/covid-vaccine-booking

created by https://twitter.com/pallupz

https://medium.com/@virender_48687/how-to-use-a-bot-to-auto-book-your-vaccine-slot-in-india-7853facd5537

**Comment by shivamchire** [comment]
@avgcoderlife Why did you closed the issue without getting a response from the developer? This is a genuine problem.

**Comment by sasank2102** [comment]
the public api seems to give only availability info. booking still has to be done manually as far as i understand

**Comment by manikanta689** [comment]
@sasank2102  booking can still be automated given that u write code to keep updating bearer token in your code once it expires.
Though the APIs are private and need tokens to access,they are still enough gaps to take advantage of I believe.
