### ISSUE TITLE
Feature Request : Vaccination details of beneficiary to be made public

### ISSUE THREAD

**Issue by Anirudhk07** [cowinapi/developer.cowin#100]
A request to cowin team - Kindly make vaccine dose status of a beneficiary public.

For example - 
1. How many doses a person has taken?
2. Date of dose taken by a beneficiary 
3. Date of next dose

I saw a beneficiary schema which is not public.

Currently `certificate api` is public but since it's response is `application/pdf` and not a `json schema` it is **useless** . I would request the team to give us the response back in `json`.

This will help create application which can track and remind people of their vaccine doses. I personally believe that this format will be very helpful to developers out there !

cc: @sudhir-trigyn @satishchandra-pandey @amitvsavant @cowinapi

**Comment by ipankajkumar93** [comment]
agree

**Comment by rachit2427** [comment]
Agreed. Basic data, as mentioned by @Anirudhk07, should be made public. Parsing PDF to fetch the data is not useful at all.

**Comment by Anirudhk07** [comment]
> Agreed. Basic data, as mentioned by @Anirudhk07, should be made public. Parsing PDF to fetch the data is not useful at all.

Absolutely true. Parsing the PDF is again a tedious job to do ! I hope the cowin team will soon make it public

cc: @sudhir-trigyn @satishchandra-pandey @amitvsavant @cowinapi
