### ISSUE TITLE
Confirm OTP Error

### ISSUE THREAD

**Issue by deepak-ezetap** [cowinapi/developer.cowin#101]
Hello,
I am getting "Invalid OTP" while trying trying the api via postman
{ "errorCode": "USRAUT0014", "error": "Invalid OTP" }

Sample API request:
URL: https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP
{
  "otp": "435990",
  "txnId": "76d2983b-14a0-467a-beef-7b15be9779ea"
}

Request your help here. What is the format of OTP to be sent? I am sending this as clear.

Thanks

**Comment by malathit** [comment]
The otp should be SHA-256 encoded

**Comment by mehulcse** [comment]
Try encoding the OTP using this(SHA256). It should work.


https://emn178.github.io/online-tools/sha256.html

**Comment by Ameerak124** [comment]
#Use in Python3 

import hashlib
hashlib.sha256(otp_string.encode('utf-8')).hexdigest()

**Comment by deepak-ezetap** [comment]
This is resolved. Thank you.
