### ISSUE TITLE
Not realted to the API but the COWIN website UI

### ISSUE THREAD

**Issue by ghost** [cowinapi/developer.cowin#103]
I don't know whats wrong with you guys. Why in the world won't you enable the "Enter" and "Tab" key on your site. 

Enters mobile number and presses enter on keyboard, 🤦 . Oh search the mouse
Enters otp and enter, 🤦 . Again search the mouse
Presses tab while switching from state to district 🤦 . Mouse again 🙃 

WHY WHY in the world would you disable the Enter and the Tab key. 😡

**Comment by NikhilTanwar48** [comment]
that is the central government for you my friend they just know how to block things that make the life of people easy.
