### ISSUE TITLE
Not able to use the generated token to view Beneficiaries

### ISSUE THREAD

**Issue by nilmond010** [cowinapi/developer.cowin#105]
I have just started noticing that get Beneficiaries API is giving unauthorized error for a valid token.

Observation: The token generated by the Cowin website has extra information present whereas the token generated using confirm OTP  has missing information such as "secret_key", "ua" am I missing any header in the request?

This has started breaking just now? 8-5-21 10.30 PM

**Comment by rishabhjainj** [comment]
Same here!

**Comment by shekharkumar86** [comment]
i am facing the same problem. any solution , please let me know.
