### ISSUE TITLE
BUG? Why are slots open at 11pm at night for THAT day?

### ISSUE THREAD

**Issue by skewwhiff** [cowinapi/developer.cowin#107]
I've seen instances when one or two slots open up for a given day, while the latest slot window is 6:00 pm. I've seen this happen in public APIs (Even with a 30 minute cache time, there shouldn't be slots at 11pm when the latest slots close at 6pm) and Cowin website too.  Please provide a more up-to-date availability status so that the website is usable. 

It's not completely clear in the image. But I managed to take a screengrab at 11:30 pm which said, there is one slot in some hospital on 8th May. **(The screenshot was taken at around 11:30 pm)**

![117548983-85e4b880-b055-11eb-9052-13fef453a3d9](https://user-images.githubusercontent.com/3540024/117549134-479bc900-b056-11eb-9e60-90889fb4b992.png)

Here are the corresponding slots for the selected center:

![117549014-b2003980-b055-11eb-9086-f58013f86ad7](https://user-images.githubusercontent.com/3540024/117549131-45396f00-b056-11eb-80d4-6726746c0524.png)

**Both these were taken at around 11:30 pm on 8th May 2021. If available slots are not up to date, what should we book based upon?!**

**Comment by mehulcse** [comment]
Is it possible that someone who booked and appointment, never visited the center and cancelled the appointment? That may lead to this confusion.

**Comment by skewwhiff** [comment]
Can you cancel appointments AFTER slot time?! That doesn't make sense. I guessed more on the lines of some hospital updating info incorrectly.

**Comment by mehulcse** [comment]
Apparently you can cancel even after the time of appointed has passed. At least that's what I experienced when my grandparents visited the hospital and they did the new registrations. I removed the old appointment the next day.

**Comment by prashanthr84** [comment]
Possible to cancel. I did cancel the appointment. Appointment scheduled for 6th and cancelled on 9th

**Comment by skewwhiff** [comment]
I didn't know this. Thanks. This only makes the website a bit more unusable. It might help to update those free slots only if they are at a time greater than current-time.
