### ISSUE TITLE
Any API to get list of states, cities and all of the city PinCodes ?

### ISSUE THREAD

**Issue by ipankajkumar93** [cowinapi/developer.cowin#108]
We have made our own json but that we have made by whatever was available on internet (not so updated and definitely outdated).
Even the list of all pinCodes on data.gov.in is so wrong that Agra shows in Andaman Nicobar.

**Comment by skewwhiff** [comment]
https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2#/Metadata%20APIs/states For states and districts per state. I don't think PINCODES are shared separately through an interface.

**Comment by ipankajkumar93** [comment]
@skewwhiff
Yeah that's sad, coz making a list of pincodes from internet is causing a lot of trouble.
So basically just leave it on user to enter manually then, RIP
