### ISSUE TITLE
How to use /v2/appointment/sessions/public/calendarByDistrict when we don't have id's of districts ?

### ISSUE THREAD

**Issue by ipankajkumar93** [cowinapi/developer.cowin#109]
Please provide a list of districts and its ID which everyone can use.

**Comment by tharun518** [comment]
Its already mentioned in the API site how to get district ID. 
State ID: https://cdn-api.co-vin.in/api/v2/admin/location/states
District ID: https://cdn-api.co-vin.in/api/v2/admin/location/districts/{state_id}

**Comment by ipankajsingh** [comment]
Yeah got it, thanks
but how do we get the list of all Pincode for a particular district ?

**Comment by ipankajkumar93** [comment]
@tharun518
Yeah got it, thanks
but how do we get the list of all Pincode for a particular district ?

**Comment by tharun518** [comment]
Can't find any option for that. But pincodes are public records, you can download from other sites.

**Comment by ipankajkumar93** [comment]
@tharun518
We are doing that for now , but using states and cities from these API and then referring to pincode list of outside is causing a lot of mismatch, not possible to be honest.
The only option is leave it to user to type without showing suggestions for pincode.

**Comment by luvneet** [comment]
Go with random input , if its valid pin then it will return result otherwise it will return error with status code 400.
