### ISSUE TITLE
How to use /v2/registration/certificate/public/download , how to use bearerToken from outside?

### ISSUE THREAD

**Issue by ipankajkumar93** [cowinapi/developer.cowin#110]
It is listed under Public API but it requires bearerToken
Can someone tell me how should I integrate this API in a web application.
I guess just hitting the API with beneficiary reference id won't get me the result or will it ?

**Comment by luvneet** [comment]
Public Api are free to use ,there is no use of bearer token yet, i guess they were created for private api's

**Comment by shivam-methi** [comment]
#177
