### ISSUE TITLE
Enhancement to show up slots based on Age group

### ISSUE THREAD

**Issue by klpradeepkl** [cowinapi/developer.cowin#113]
In Bangalore for 18+ has started on May 2nd at very small scale in private hospitals. Slots are getting ( as many as 200) filled in under 30 sec even with introduction of captcha. Every one has to be  lightning fast to grab a slot. Can you please consider the following enhancements:

1. Show the slots based on age on click of Search button. Currently, we need to click 2 buttons Search and Age 18+. This takes time. Just by clicking search, all age group data gets listed and since result is reasonably large list, user needs to do browser scroll and result area scroll, which is not user friendly. Even with my suggestion, scrolling cannot be avoided, but filter list will be relatively small. This is applicable when we search by district. When vaccine shortage is prelevant, pincode search is of little use for 18+ for now at least.
2.  Captcha in numbers will be better. 
3. The result area needs to be scrolled when we search by district. Can some thing be done to avoid scrolling. Once the slots for a center are filled, can the booked slots be pushed down in the list or when a new slot is being opened and when user searches by district, can the newly opened slot be shown in the top of result search until slots are available. This way scrolling can be avoided.
4. Not sure what is the session timeout configured. If it is less than 30 mins, can it be configured to at least 30 mins. In 2 occurrence, when i clicked on confirm session timed out and i lost chance book. 

Please do consider few of these enhancements. There at least minimum of 1000 users in Bangalore whenever the slots are opened and slots (50-200) do get filled in 30 sec.

**Comment by SehgalNeeraj** [comment]
> In Bangalore for 18+ has started on May 2nd at very small scale in private hospitals. Slots are getting ( as many as 200) filled in under 30 sec even with introduction of captcha. Every one has to be lightning fast to grab a slot. Can you please consider the following enhancements:
> 
> 1. Show the slots based on age on click of Search button. Currently, we need to click 2 buttons Search and Age 18+. This takes time. Just by clicking search, all age group data gets listed and since result is reasonably large list, user needs to do browser scroll and result area scroll, which is not user friendly. Even with my suggestion, scrolling cannot be avoided, but filter list will be relatively small. This is applicable when we search by district. When vaccine shortage is prelevant, pincode search is of little use for 18+ for now at least.
> 2. Captcha in numbers will be better.
> 3. The result area needs to be scrolled when we search by district. Can some thing be done to avoid scrolling. Once the slots for a center are filled, can the booked slots be pushed down in the list or when a new slot is being opened and when user searches by district, can the newly opened slot be shown in the top of result search until slots are available. This way scrolling can be avoided.
> 4. Not sure what is the session timeout configured. If it is less than 30 mins, can it be configured to at least 30 mins. In 2 occurrence, when i clicked on confirm session timed out and i lost chance book.
> 
> Please do consider few of these enhancements. There at least minimum of 1000 users in Bangalore whenever the slots are opened and slots (50-200) do get filled in 30 sec.

Refer #67 and #94 for points 1,3
