### ISSUE TITLE
DOUBT- need to change my registered mobile number.

### ISSUE THREAD

**Issue by Inderpreetsingh11** [cowinapi/developer.cowin#115]
I got myself vaccinated for the first dose and it's showing the same when I open the portal with my registered mobile number. But for some reason I need to change my registered mobile number. Can my data be shifted to the new mobile number?

**Comment by shubhamtawde** [comment]
@Inderpreetsingh11 I don't think so. If you register a new beneficiary it starts afresh. (That's what people told me). I haven't tried it personally. Check if there's an edit option.

**Comment by DeepakUdherani** [comment]
I don't think we have that liberty till now.
Tried registering my id with other number, it started as fresh one allowing for dose 1 booking
