### ISSUE TITLE
Appointment can't be booked as no time slots are listed 

### ISSUE THREAD

**Issue by attium** [cowinapi/developer.cowin#118]
I noticed that appointments in some hospitals are available but have no time slots listed

![image](https://user-images.githubusercontent.com/38878456/117571640-102c2b80-b0ed-11eb-88d3-96c2bfab2e82.png)

Since we can't confirm appointments  without selecting a time slot, these appointments can't be booked.

**Comment by gopal-amlekar** [comment]
I got the same error for multiple centers. Strange thing is the available slots for these centers go on reducing that means some people are able to book it. Not sure how they can do it if there is no Time Slot available.
