### ISSUE TITLE
curl working on localhost but raising 403 on online server with same script

### ISSUE THREAD

**Issue by rishabhrkc98** [cowinapi/developer.cowin#119]
@cowinapi I am doing using PHP, I am able to retrieve data on Localhost but when I place same following code on online server (website), it is raising 403 error as shown in screenshot below.

$headers = [
       "accept:application/json", 
        "Accept-Language:hi_IN", 
        "user-agent:Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
    ];
$url="https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=852131&date=09-05-2021";
$ch = curl_init();
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_URL, $url);
$result=curl_exec($ch);
print_r($result); 

LocalHost -

![image](https://user-images.githubusercontent.com/83907821/117572286-dc063a00-b0ef-11eb-8756-5cf3ab9f6b45.png)

But with Online Host - https://cowinslot.lyricshome.xyz/check.php

![image](https://user-images.githubusercontent.com/83907821/117572344-1c65b800-b0f0-11eb-9965-df821aedc29c.png)

**Comment by prashanthr84** [comment]
Doesnt work if the request is sent from outside India

**Comment by hkrish0** [comment]
I am getting the same error in postman locally.I am using php and sending request with in india only.
The generateOtp and ConfirmOTP apis are working fine.The getStates api is throwing this 403 error.

**Comment by shardul08** [comment]
> I am getting the same error in postman locally.I am using php and sending request with in india only.
> The generateOtp and ConfirmOTP apis are working fine.The getStates api is throwing this 403 error.

@hkrish0 have you tried adding headers?
```
headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"}
```

**Comment by hkrish0** [comment]
@shardul08 Now it is working..I was checking the header in the postman..Now I added inside the script also
..working fine..thanks

**Comment by Vaibhav-Lodha** [comment]
@hkrish0 how are u making generateOtp request, im trying for some hours now but its not working for some reason

**Comment by hkrish0** [comment]
@Vaibhav-Lodha normal post request...what is the error you are getting ?

**Comment by Vaibhav-Lodha** [comment]
Error 400, @hkrish0 
![image](https://user-images.githubusercontent.com/76046097/117575255-addc2680-b0fe-11eb-9bd5-47d3a7e8f59a.png)

**Comment by hkrish0** [comment]
@Vaibhav-Lodha try sendinig mobile number as string value

**Comment by hkrish0** [comment]
@Vaibhav-Lodha /v2/auth/public/generateOTP
This is the public api I am using..yours looking different..

**Comment by hkrish0** [comment]
@Vaibhav-Lodha /v2/auth/generateOTP
this is the protected api for generating otp.
Check the api

**Comment by Vaibhav-Lodha** [comment]
I tried the public api as well 😅 it was giving the same error so i tried the api in inspect view

**Comment by hkrish0** [comment]
@Vaibhav-Lodha Your api name looks wrong ... "generateMobileOTP" in the above screenshot..

**Comment by Vaibhav159** [comment]
I will try again with the public again

**Comment by tuktuk24** [comment]
> Doesnt work if the request is sent from outside India

This must be the issue. I have my node backend running on heroku, deployed on US servers. So it throws 403. However running the node app on my local machine works just fine (after using User-Agent header). Guys are there services like heroku that are hosted on Indian servers?
