### ISSUE TITLE
Procedure to increase 100 api limit

### ISSUE THREAD

**Issue by anirudhkh1** [cowinapi/developer.cowin#120]
I have made a website that E-Mails user about the slot availabilty in user select district. The website is up and working, but sometimes throws the 100 bypass limit error.

Right now my website is hitting /v2/appointment/sessions/public/calendarByDistrict 5-6 requests each 20 seconds. I will be needing to increase these requests in future.

Any idea if I can increase/change this limit so users can get realtime appropriate E-Mails.

**Comment by tru-rohit** [comment]
Either this or have them accept an array of district_ids in calendarByDistrict API

**Comment by pranshukas** [comment]
Can You Help out how to use their API's to Search for States. I am trying to use POSTMAN to send Get request to URL provided on cowin Open API but it's showing Error ~!
