### ISSUE TITLE
Can we send API request from servers located outside India?

### ISSUE THREAD

**Issue by shardul08** [cowinapi/developer.cowin#121]
I am trying to host a script to get slot updates on a cloud server that is located outside India.
When I run the script on my local machine, the script works fine. But when I run it on the cloud server, I am getting the 403 error.
Can we send request to the API from an IP outside India or only from Indian IP?

**Comment by iamarjun** [comment]
@shardul08 No

**Comment by shardul08** [comment]
@iamarjun any Indian cloud service that you are aware of?

**Comment by luvneet** [comment]
@shardul08 Amazon Aws works fine for me.

**Comment by romelraman85** [comment]
> 
> 
> I am trying to host a script to get slot updates on a cloud server that is located outside India.
> When I run the script on my local machine, the script works fine. But when I run it on the cloud server, I am getting the 403 error.
> Can we send request to the API from an IP outside India or only from Indian IP?

No, you cannot do so, they might have blocked all the IPs outside India and they have done it rightly so.

**Comment by saran-surya** [comment]
Hi @shardul08, Yes we can have the server hosted outside India and still access the COWIN API, 
If you are using a NODE JS app, you can try this package CASSTA to proxy your server to your current location,
I have tested this on HEROKU with an US server for this API. Yes it does take some energy from your local machine, but if you want to have the server hosted for free this can help.
