### ISSUE TITLE
Not able to get the secret_key in JWT token from my web app after 200 status code in 

### ISSUE THREAD

**Issue by haldarmahesh** [cowinapi/developer.cowin#122]
Hey I am able to generate the JWT token from my web app running from local.

The token generated from my web app is following:
curl
```
curl 'https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP' \
  -H 'authority: cdn-api.co-vin.in' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'accept-language: en-US,en;q=0.9,hi;q=0.8' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: http://localhost:49764' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:49764/' \
  --data-raw '{"otp":"b40d43aa1cea09ef963cf3a7752a16df41e66fd7f8b410d8dc4a8d74c7338dea","txnId":"3e826be7-53c8-45d2-b50a-096544e45ce6"}' \
  --compressed
```

Decoded the token from response:
```
{
  "user_name": "7d4d6792-001e-4228-89d7-d350cc1c5f0a",
  "user_type": "BENEFICIARY",
  "user_id": "7d4d6792-001e-4228-89d7-d350cc1c5f0a",
  "mobile_number": 814756****,
  "beneficiary_reference_id": 84935921668690,
  "txnId": "3e826be7-53c8-45d2-b50a-096544e45ce6",
  "iat": 1620565124,
  "exp": 1620566024
}
```

The token received from https://selfregistration.cowin.gov.in/ on success login is
```
{
  "user_name": "7d4d6792-001e-4228-89d7-d350cc1c5f0a",
  "user_id": "7d4d6792-001e-4228-89d7-d350cc1c5f0a",
  "user_type": "BENEFICIARY",
  "mobile_number": 814756****,
  "beneficiary_reference_id": 84935921668690,
  "secret_key": "b5cab167-7977-4df1-8027-a63aa144f04e",
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "date_modified": "2021-05-09T13:08:46.644Z",
  "iat": 1620565726,
  "exp": 1620566626
}
```

if you see the difference is in the 1st token there is no `secret_key` and `ua`. Can you share what it needs to add `secret_key` key and `ua` in JWT token? 

PS. if I run APIs from postman, I am able to get `secret_key` in JWT token though.

**Comment by Vaibhav-Lodha** [comment]
Are u able to generate otp ?

**Comment by haldarmahesh** [comment]
Yes @Vaibhav-Lodha  i am able to generate otp, hence hitting the validateOtp api

**Comment by Vaibhav-Lodha** [comment]
@haldarmahesh how are u making request to valid otp, i am trying to pass mobile and secret, but im not sure how to generate secret, or the headers required, currently im just passing User agent and content type but it gives 400

**Comment by luvneet** [comment]
@haldarmahesh can you please share ,how do you get this
( "otp":"b40d43aa1cea09ef963cf3a7752a16df41e66fd7f8b410d8dc4a8d74c7338dea" )
from a 6 digit OTP number ?

**Comment by haldarmahesh** [comment]
@luvneet you can get the hash of 6 digit OTP using the sha256 function.

**Comment by luvneet** [comment]
@haldarmahesh Ty, solved hash ,it was hash256.
did you found the solution of this issue?
now i'm also able to login successful and received my token.
but even with token ,not able to retrieve beneficiary data.
what else do i need to add in my header request.
please help if found any solution?
