### ISSUE TITLE
There are 2 apis for getting centres , which one to use?

### ISSUE THREAD

**Issue by souvickm** [cowinapi/developer.cowin#123]
We have  /api/v2/appointment/sessions/public/calendarByDistrict
 and.    /api/v2/appointment/sessions/calendarByDistrict. Which one is more realtime?

**Comment by luvneet** [comment]
1st one as it is build for public usage.
you can not get result with 2nd one ,as this api is used by website itself for authenticated users.
2nd one is more realtime ,1st one provide website cached data (30 min late)

**Comment by souvickm** [comment]
2nd one(non public) is also working with Postman but not from code.

**Comment by luvneet** [comment]
@souvickm It might work sometime but it was designed to work for authenticated user as it takes barer token for authentication in its header.

**Comment by anmolkhemuka** [comment]
The second API sometimes work and sometimes not. Why it is so?
