### ISSUE TITLE
Public API shows slots available but after logged in shows fully booked 

### ISSUE THREAD

**Issue by Heerok** [cowinapi/developer.cowin#127]
Public API shows slots available but after logged in, it shows fully booked. Why the data difference? Where are bookings going?

https://twitter.com/HazarikaHeerok/status/1391410249915981825?s=20

**Comment by DeepakUdherani** [comment]
Public API data is cached, which is essentially refreshed after 30 mins. There is a high possibility that the data itself is showing up late until the cache refresh is yet to happen.

**Comment by Heerok** [comment]
Okay. Thanks for clarification

**Comment by Heerok** [comment]
Can there be a parameter in the response which says the last cached timestamp?

**Comment by DeepakUdherani** [comment]
I don't think any such attribute is available.

**Comment by monish-1234** [comment]
No that is done in the backend by the mods. Reducing the cache time is a heavily requested feature

**Comment by Heerok** [comment]
If there is no solution to this then I will close the issue.

**Comment by pinkeshsingh01** [comment]
An easy and effective solution for this, add a microservice/Kafka layer (call it cache optimizer) that consumes the triggered message to rebuild the cache as soon as the new data is entered into the DB. The corresponding keys from the cache layer will get modified with the new data. By this, our cache system will remain in place and will have updated data every time.
