### ISSUE TITLE
Getting a not valid key=value pair (missing equal-sign) error (403)

### ISSUE THREAD

**Issue by sharshub** [cowinapi/developer.cowin#129]
I have tried setting the Authorization header as 'Bearer token' and 'Basic token'.
The error I receive is:

'token' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer token'

**Comment by KBA07** [comment]
@sharshub Can you attach the complete request which you are sending along with the complete response. This will help other people debug this.

**Comment by rsdev009** [comment]
@sharshub how did you fix this issue?

**Comment by John0911** [comment]
facing same issue... kinldy guide
