### ISSUE TITLE
Cowin API inconsistent results for slots - District vs Pin Code

### ISSUE THREAD

**Issue by KKcorps** [cowinapi/developer.cowin#13]
Whenever a slot appears as free, it is shown in both district vs pin code search. The pin code search however, updates the number of slots correctly while it takes the district search more than half an hour to update the count. [](URL)

As you can see in the attached screenshots w.r.t. to the following API calls at 12:20 PM IST on 5th May 2021.  The available capacity is shown as 49 in the `calendarByDistrict` API and 0 slots as empty in the `pincode` API. The `pincode` API  has the correct response since most slots were booked within a minute of opening.

https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=265&date=05-05-2021

https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=560007&date=05-05-2021

<img width="570" alt="Screenshot 2021-05-05 at 12 20 39 PM" src="https://user-images.githubusercontent.com/5559703/117105813-6b33ea80-ad9c-11eb-952b-8f853f6f7b1e.png">
<img width="541" alt="Screenshot 2021-05-05 at 12 20 45 PM" src="https://user-images.githubusercontent.com/5559703/117105820-6d964480-ad9c-11eb-88ab-da956b0126e1.png">

**Comment by KKcorps** [comment]
Most likely the reason can be the use of cache in the background for fetching information of multiple pin codes for a district. It is just a theory from a third-party perspective though.

**Comment by chandraaditya** [comment]
What about the findBy APIs? Have you done any tests on them?

**Comment by satishchandra-pandey** [comment]
@KKcorps 
The data cached on the server.
Please read more in this links description: https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2

**Comment by chandraaditya** [comment]
I don't understand why the data is being cached tho? And also so is the find by Pincode API not cached? I'm specifically asking for the findBy APIs, not calendarBy
