### ISSUE TITLE
No documentation regarding Response Code 403 in the API documentation

### ISSUE THREAD

**Issue by adityachanekar** [cowinapi/developer.cowin#130]
I've been noticing the many people have been getting 403 res code when they call the appointment API (byPincode and/or byDistrict)

there is no documentation about why 403 is being responded on the API Setu Website

**Comment by rishabhrkc98** [comment]
I was also getting same problem. It is actually geolocation protected so API can be accessed only from servers located in INDIA.  I tried with Indian servers, now it is working fine

**Comment by adityachanekar** [comment]
There another thing, you need to add
`'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
`
to the headers as told by #34

**Comment by BelalQuamar** [comment]
> 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

This too isn't working.
funny though. I have two servers both Nginx running on a subdomain and public IPv4(do not confuse, both subdomains are on a different domain each).
one server can hit the API, the other cant.
with one of them I am hitting 100 times every 5 minutes and it's all fine
the other can't hit even once
tried with a new VM on a different IP address, still the same issue


Edit:
It is somehow flagging IP addresses as well, I tried from two IP's of 139.59.0.***. The responses were the same {failed}

Spun another VM and got IP 128.99.**".*** and it works.

So if it doesn't get a new IP address..that seems to be the only fix for now

**Comment by adityachanekar** [comment]
Closing this as a temporary fix to the issue is found, but there seems to be no one from the CoWIN Dev team to update their documentation.
