### ISSUE TITLE
Does the CoWIN website use the public API?

### ISSUE THREAD

**Issue by rnayabed** [cowinapi/developer.cowin#131]
Does the website show real time data or does it use the same public API, and shows cached data?

**Comment by DeepakUdherani** [comment]
No they use protected ones.
Public Apis are cached with 30 mins delay.

**Comment by luvneet** [comment]
yes for homepage.
but it use protected Api when you log in and search centers for booking

**Comment by luvneet** [comment]
@DeepakUdherani just inspect their homepage request, you will know..

**Comment by rnayabed** [comment]
@luvneet I was thinking the same too, that the homepage uses the public API. but the problem is that if you compare the results by using the public api yourself and the website itself its different. I checked the network tab using dev tools and seemed that they use the public api

**Comment by DeepakUdherani** [comment]
@luvneet 
Yes verified in network tab, they are hitting public Apis.
@rnayabed 
Sorry for initial comment, I did not checked for home page calls

**Comment by luvneet** [comment]
@rnayabed didn't compared this like you said .
Going to try it tomorrow ,but i think its not possible same API providing two different results.

**Comment by rnayabed** [comment]
> @rnayabed didn't compared this like you said .
> Going to try it tomorrow ,but i think its not possible same API providing two different results. 

yeah please do, I think this is just a human error on my end.

**Comment by karthik261099** [comment]
They are using public APIs only.

**Comment by anuragchoudhary01** [comment]
This is on the homepage 
`https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=xxx&date=xxxx`

The above URL has public.

This is after you login 
`https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=xxx&date=xxxx`

**Comment by rnayabed** [comment]
Seems like it, I guess it was a human error

**Comment by raj-k-jangid** [comment]
They are using public API I checked

**Comment by pranab-witbybit** [comment]
But the api & cowin website both are getting different data for the same link. Is there a way to replicated the request sent by cowin? I tried doing it in every possible way, without any progress.

**Comment by pranabs1ngh** [comment]
But the api & cowin website both are getting different data for the same link. Is there a way to replicated the request sent by cowin? I tried doing it in every possible way, without any progress.

**Comment by Bhupendersinghbisht** [comment]
Hello,

I would like to use protected API's to get slot availability. How can I get auth token details ?
thanks

**Comment by rnayabed** [comment]
> Hello,
> 
> I would like to use protected API's to get slot availability. How can I get auth token details ?
> thanks

I think you need to contact the govt using their phone number or something. I do not think you can get any help from github unless a cowin developer magically sees your comment (most of us here are just random people like you lol)

**Comment by rnayabed** [comment]
> But the api & cowin website both are getting different data for the same link. Is there a way to replicated the request sent by cowin? I tried doing it in every possible way, without any progress.

Yeah i had the same issue, i think they are using something additional to get the latest data

**Comment by pranabs1ngh** [comment]
> I would like to use protected API's to get slot availability. How can I get auth token details ?
thanks

You can use these routes to get & confirm otp. And then you can set the token received in header as authorization. 
Just check the network logs in your browser after you sign in for more info. 
![image](https://user-images.githubusercontent.com/29424090/117668247-623f8080-b1c3-11eb-9a3e-4e757e375fed.png)

Note: the token is valid only for 15 mins from time of generation.

**Comment by mayukh18** [comment]
Quite sure they are handling it internally in any different way ( don't know what though). The responses from the public apis are mostly cached and does not correlate with the ones in the appointment booking page in real time.
