### ISSUE TITLE
Getting 401 on Test Server  for appointment by pincode end point

### ISSUE THREAD

**Issue by Chaitanya426** [cowinapi/developer.cowin#132]
curl --location --request GET 'https://api.demo.co-vin.in/api/v2/appointment/sessions/findByPin?pincode=562111&date=11-05-2021&vaccine=COVAXIN' \
--header 'accept: application/json' \
--header 'Accept-Language: hi_IN' \
--header 'Authorization: Bearer 3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi'

**Comment by Chaitanya426** [comment]
![401_Cowin](https://user-images.githubusercontent.com/33853755/117582038-bee86000-b11d-11eb-9b1e-6f3f6d10db58.PNG)

**Comment by monish-1234** [comment]
Access the public API

eg.
https://api.demo.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=562111&date=11-05-2021&vaccine=COVAXIN

To be Noted: only Calendar API returns both booked and un-booked slots. findByPin and findByDistrict will only return if there are any un-booked slots
