### ISSUE TITLE
Get list of districts is not accessible

### ISSUE THREAD

**Issue by MakarandD** [cowinapi/developer.cowin#135]
I tried fetching the records with the above API and its not returning any values with state_id.

Kindly give me steps to access them

**Comment by monish-1234** [comment]
Check this out.
https://github.com/cowinapi/developer.cowin/issues/140#issuecomment-836215512

**Comment by HRN-Projects** [comment]
In my case, I had to pass 2 important keys to headers while requesting states and districts list APIs.
1. user-agent - Pass user-agent key according to the environment where you are running your code from.
2. Authorization - I had to create auth key using OTP authorization and then pass it to 'authorization' key in headers, as a bearer token.

I have also tried both APIs without passing any authorization header key and token, and I got 403 error for every request that I made.

Other than this, you would need to pass a specific 'state_id' in request URL as well.
