### ISSUE TITLE
Slots Availability

### ISSUE THREAD

**Issue by PRA1995SAG** [cowinapi/developer.cowin#136]
> Hello, yesterday (09/05/2021) I tried to **schedule for vaccines** three times around 11AM - 3PM
- Age: 45+
- State: Maharashtra
- District: Ratnagiri

> There were no available slots to book.
> today morning (10/05/2021) site showing all slots are booked.

> what's particular time to schedule vaccination ?
> what time site's db update ?

Kind regards

**Comment by monish-1234** [comment]
As far as I know, the slot opening is done by the hospitals. So it'll take place randomly. 
That is why there are tons of scripts and notifiers to book slots.

But to answer your question, I've seen slots opening up from 3-6PM and again from 10PM-2AM

**Comment by Inderpreetsingh11** [comment]
For the districts that I'm looking the slots are opening between 6pm - 8pm for 18+. For 45+ it's 6pm to 11pm.
