### ISSUE TITLE
2nd Dose Date Issue

### ISSUE THREAD

**Issue by shruthiiraju** [cowinapi/developer.cowin#138]
Hey team,

This is regarding an issue for those who are trying to book an appointment for 2nd DOSE. 
If you are trying to schedule an appointment for 2nd Dose, you cannot see appointments for the current day, only the NEXT day, even if the 6-8 week wait period is well over. 
Is this by design?

Eg. Today is May 10th. When I log in to book for second dose (my 8 week wait is over), I can only see slots from May 11th onwards. Why?

**Comment by chandraaditya** [comment]
Yup! I noticed the same issue! Could see it in the API and was trying to book for my dad but could not find it on CoWIN.

**Comment by shruthiiraju** [comment]
More details:

For 2nd dose appointments:
Current day slots are visible and available in the AarogyaSetu app. But it is impossible to book slots for the current day, we get a "Failed Confirmation" response as attached.

![Screenshot_20210510-114327_Aarogya Setu](https://user-images.githubusercontent.com/17351298/117614618-318d2600-b186-11eb-948e-9534fe61c19d.jpg)

**Comment by shruthiiraju** [comment]
For 2nd dose appointments:
Current day slots are visible and available in the AarogyaSetu app. But it is impossible to book slots for the current day, we get a "Failed Confirmation" response as attached.
![IMG_20210510_115127_879](https://user-images.githubusercontent.com/17351298/117614797-787b1b80-b186-11eb-869a-4fcfccdb8868.jpg)
