### ISSUE TITLE
calenderByDistrict API to accept array of district_ids

### ISSUE THREAD

**Issue by tru-rohit** [cowinapi/developer.cowin#142]
Hello,

We understand that there is a rate limit of 100 requests per 5 minutes and we don't want to flood the CoWIN servers with a lot of traffic either. 

Just wanted to understand if it's possible to get the list of centers with an array of District IDs. A lot of times we want to get centers in multiple districts and we want to avoid calling this API in a loop.

It would be much easier and avoid traffic outages if this API was updated to accept an array of district_ids. 

Or maybe release another API for this use case?

@monish-1234 @cowinapi

**Comment by monish-1234** [comment]
@roh-git  👀 I am not a developer in CoWin. 

But I don't see a possibility of that happening any time soon as I am honestly surprised that they released a Public API in the first place. But they even created a Github Repo for Issues. I don't think this has happened in such a large scale ever before in the history of Indian Government.

The feature you request for is only useful for 3rd party devs like us. So it would be on a very low priority as they are busy with the issues in the website.  But it would reduce a lot of API calls thus reducing their AWS Costs. So they might ? idk man.

This and filter option for age and vaccine would be very helpful for Devs. Let's see

**Comment by ASHISHTOM** [comment]
where do we find the district ids and corresponding districts??
