### ISSUE TITLE
Arbitrary 401?

### ISSUE THREAD

**Issue by p16r** [cowinapi/developer.cowin#143]
I called the same API endpoint about 5 minutes apart and the first time I got 200 OK and the second time I got 401 Unauthorized.

<figure>
  <img width="1440" alt="Screenshot 2021-05-10 at 12 37 53" src="https://user-images.githubusercontent.com/29314504/117619950-88e2c480-b18d-11eb-9ac6-ee9d4448170d.png"><figcaption>200 OK</figcaption>
</figure>

____

<figure>
  <img width="1440" alt="Screenshot 2021-05-10 at 12 37 57" src="https://user-images.githubusercontent.com/29314504/117619919-7d8f9900-b18d-11eb-860e-1423b7d378ba.png"><figcaption>401 Unauthorized, 5 minutes later, identical request params</figcaption>
</figure>

____

Any idea if I’m supposed to do any sort of caching? ETag based caching does not seem to work as identical data will sometimes return different ETags.

Edit: Raw HTTP request:
```
GET https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=115&date=10-05-2021 HTTP/1.1
Host: cdn-api.co-vin.in
Accept: application/json
Accept-Language: en-us
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
```

**Comment by monish-1234** [comment]
`GET https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=115&date=10-05-2021 HTTP/1.1`

You are accessing Protected API. 
Protected API's should always give 401 Errors but sometimes it doesn't (probably some backend issue). Try Public API.
Eg.
`GET https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=115&date=10-05-2021 HTTP/1.1`

**Comment by p16r** [comment]
This is working correctly. Thank you!

**Comment by rudrasura** [comment]
``You can still use the Protected API.
Try any valid Bearer AUTH token, it would work.
Please do note the public APIs may be fetching data from cache which may be late by 30 min. (AS per official CoWIn Website)
By using any valid Basic AUTH token, Protected APIs can be accessed.
For any failures try using a retryer 
` @RequestMapping(
            value = "/calendarByDistrict",
            headers = {
                    "accept=application/json",
                    "Accept-Language=hi_IN",
                    "DNT=1",
                    "authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI5NWEwNGEwZS03YmNjLTQxY2QtYTBhYS00ZDU2OWRmZGNmNDMiLCJ1c2VyX2lkIjoiOTVhMDRhMGUtN2JjYy00MWNkLWEwYWEtNGQ1NjlkZmRjZjQzIiwidXNlcl90eXBlIjoiQkVORUZJQ0lBUlkiLCJtb2JpbGVfbnVtYmVyIjo5OTg2MDUwNjUxLCJiZW5lZmljaWFyeV9yZWZlcmVuY2VfaWQiOjg0NDE0NTI4MjA3NzAwLCJzZWNyZXRfa2V5IjoiYjVjYWIxNjctNzk3Ny00ZGYxLTgwMjctYTYzYWExNDRmMDRlIiwidWEiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvOTAuMC40NDMwLjkzIFNhZmFyaS81MzcuMzYiLCJkYXRlX21vZGlmaWVkIjoiMjAyMS0wNS0xMFQxMDoxNzoyMy4yNTBaIiwiaWF0IjoxNjIwNjQxODQzLCJleHAiOjE2MjA2NDI3NDN9.Z-maZOH1iqv3RH_VMM8y0xfcm5waXN40S-dt_-Dp0bQ",
                    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"},
            method = RequestMethod.GET,
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    CowinResponse getCentersByDistrict(@RequestParam(value = "district_id") String district_id, @RequestParam(value = "date") String date);`

**Comment by p16r** [comment]
How do you generate the bearer token JWT? Surely this one JWT cannot work all the time?
