### ISSUE TITLE
Why not just have a lottery system on daily basis..

### ISSUE THREAD

**Issue by nagesh-salunke** [cowinapi/developer.cowin#145]
Why not just have a lottery system on daily basis?
**The booking system isn't fair for a large number of users**, an only select hundred from thousands who are trying are getting slots and it's also based on the luck of their request reaching servers fast!

The lottery can be drawn between applied people for a center on a daily basis

**Comment by monish-1234** [comment]
Not sure if you're sarcastic or if you're actually recommending it. I would say the issue is with the low availability of vaccines and importantly the tons of people who register and then not show up to Vaccinate. 

#63 This issue would solve that problem.

**Comment by nagesh-salunke** [comment]
In the current scenario, If we have to be really "fair" for distribution, I see the Lottery option could be more realistic
Given that there is already a vaccine shortage, there are very few paid centers
Also, I don't think people are booking slots unnecessarily, Given that how hard it is to book and get a slot, Doing that for fun itself is a task!

**Comment by zerebral** [comment]
> In the current scenario, If we have to be really "fair" for distribution, I see the Lottery option could be more realistic
> Given that there is already a vaccine shortage, there are very few paid centers
> Also, I don't think people are booking slots unnecessarily, Given that how hard it is to book and get a slot, Doing that for fun itself is a task!

True. Looking out an active slot is quite an ask and is wasting hours of productive time! (at least for those who care for it) - I think the CoWIN app needs to probably allot slots on a first come first serve basis and those who do not accept or miss it should not get another chance for a few weeks at least or should be placed at the back end of the queue perhaps!

**Comment by nagesh-salunke** [comment]
"First come first serve basis" is very difficult on "internet" scale
Example : 
My daily help and my driver won't be able to get the vaccine slots for months with the current scenario.
First - They would need "high" speed internet
Second - They should be lucky enough to be first

The system is adding to the problem of vaccine shortage by being discriminative on who gets the vaccine!
Software systems are supposed to "solve" the problem and not add more problems!

**Comment by zerebral** [comment]
People are travelling to other districts as well to get the jab and the locals there are opposing, sending them back. Perhaps rightly so! To curtail such issues CoWIN needs to just put people in a centrally managed queue per zip code and then notify them when their day arrives! This way the data could be used centrally to ensure vaccine availability where there is more demand!

**Comment by zerebral** [comment]
> "First come first serve basis" is very difficult on "internet" scale
> Example :
> My daily help and my driver won't be able to get the vaccine slots for months with the current scenario.
> First - They would need "high" speed internet
> Second - They should be lucky enough to be first
> 
> The system is adding to the problem of vaccine shortage by being discriminative on who gets the vaccine!
> Software systems are supposed to "solve" the problem and not add more problems!

Yeah, unfair that way! Totally! CoWIN would know the target demographics and can schedule people from various categories to make it fair. There are smart people out there I suppose who can solve these internet scale problems! But I get it, a vast majority may not even have a cell phone (let alone internet access!) - poor guys just have to walk-in and get lucky! :-(

**Comment by karanssh** [comment]
Adding on to this, I would recommend devs to please add something like "Book for me when available" - similar to a lottery system, but at least you don't have to spend all day hoping to get a slot.
