### ISSUE TITLE
 need of secret key

### ISSUE THREAD

**Issue by anmolkhemuka** [cowinapi/developer.cowin#147]
Can someone tell what is the need for a secret key in the post request for getting an OTP?
This parameter is not mentioned in the API portal but when I did inspect element on the cowin website I come to know that they are also sending some secret key in the post request.

**Comment by Kashyab19** [comment]
Hi
I am also trying to understand the same thing. Please let me know if you find something

If this helps @anmolkhemuka :
https://documenter.getpostman.com/view/9564387/TzRPip7u 

Also this:
https://github.com/cowinapi/developer.cowin/issues/124

**Comment by anmolkhemuka** [comment]
Hey, I looked into this and found that there is no relation between OTP and the secret key. Actually, the secret key is used to encode the user agent info in the header which you will be sending along with the request.
