### ISSUE TITLE
Unable to access the public APIs - Getting 403 Error

### ISSUE THREAD

**Issue by pranshukas** [cowinapi/developer.cowin#148]
I am using Postman to generate Get Request to Public API `https://cdn-api.co-vin.in/api/v2/admin/location/states`

But it's giving 403 Error 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>

<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
	<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD>

<BODY>
	<H1>403 ERROR</H1>
	<H2>The request could not be satisfied.</H2>
	<HR noshade size="1px">
	Request blocked.
	We can't connect to the server for this app or website at this time. There might be too much traffic or a
	configuration error. Try again later, or contact the app or website owner.
	<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
	<BR clear="all">
	<HR noshade size="1px">
	<PRE>
Generated by cloudfront (CloudFront)
Request ID: ACW_-DwcAsGB2oOR6Jhnx_dD-VCGy61Ob_emkisf6N-Bg_rfYsHsUg==
</PRE>
	<ADDRESS>
	</ADDRESS>
</BODY>

</HTML>
```

What is the Use of Bearer Authentication. I have also used it but still getting error. How to authenticate ?

**Comment by riteshghodrao** [comment]
Try adding a User-Agent to your requests headers such as 
{"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"}

**Comment by pranshukas** [comment]
> Try adding a User-Agent to your requests headers such as
> {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56"}

**Comment by saran-surya** [comment]
Hello @pranshukas , This user agent does not work for Heroku servers, kindly mention them it will be helpful.

**Comment by rudrasura** [comment]
> Hello @pranshukas , This user agent does not work for Heroku servers, kindly mention them it will be helpful.

Hi heroku apps dynamos are located outside India. It won't work. Try using AWS on India region.
AS an experiment I asked my US friends to directly access Get APIs, it gave the 403 error for them as well.

**Comment by pranshukas** [comment]
> > Hello @pranshukas , This user agent does not work for Heroku servers, kindly mention them it will be helpful.
> 
> Hi heroku apps dynamos are located outside India. It won't work. Try using AWS on India region.
> AS an experiment I asked my US friends to directly access Get APIs, it gave the 403 error for them as well.

Thanks, I was also confused why it's not working on Postman while accesing directly by Chrome or any other browser is giving JSON File.

**Comment by rudrasura** [comment]
> > > Hello @pranshukas , This user agent does not work for Heroku servers, kindly mention them it will be helpful.
> > 
> > 
> > Hi heroku apps dynamos are located outside India. It won't work. Try using AWS on India region.
> > AS an experiment I asked my US friends to directly access Get APIs, it gave the 403 error for them as well.
> 
> Thanks, I was also confused why it's not working on Postman while accesing directly by Chrome or any other browser is giving JSON File.

HI, That issue is specifically because header needs to have User Agent.
Without that, the API would give 403.
