### ISSUE TITLE
Is it possible? get vaccine status by Aadhaar number?

### ISSUE THREAD

**Issue by mihirvadalia** [cowinapi/developer.cowin#149]
**Is it possible?**

First of all, thank you team for great work on APIs and development.

I want to know, is it possible to know any person has taken vaccine or not using api?
for example, using only person's Aadhaar card number, get his vaccine shots status like [TAKEN, NOT_TAKEN]?

Kindly let us know, if it is possible to get data using Aadhaar number for vaccine shots? any pointers for it?

**Comment by mihirvadalia** [comment]
@cowinapi @sudhir-trigyn @animarawat @chalukyamohanraj @satishchandra-pandey can you please help here?

**Comment by tech-gainers** [comment]
Team,

we are also looking for such API which will help us in achieving our use case.

**Comment by souvik234** [comment]
I don't think if it'll be possible since not every user registered on Co-WIN will have an Aadhaar Card.
