### ISSUE TITLE
Different API response to different users

### ISSUE THREAD

**Issue by Inderpreetsingh11** [cowinapi/developer.cowin#152]
There is a scenario on which I want to discuss.
I subscribed to getjab.in to get notification for available slots, and I did get one that 250 slots are available in X hospital but at that very moment I ran the API for the same district but I didn't get the available slot count and after 50 seconds I was returned 0(I believe everything was booked) available slots for hospital X.
Does anyone has any idea about this? Why I wasn't returned that slot count at the first place?

**Comment by athJ** [comment]
@Inderpreetsingh11 this might answer your question : https://indianexpress.com/article/technology/social/new-cowin-api-guidelines-reduce-reliability-of-third-party-alert-services-7306116/#:~:text=Further%2C%20the%20APIs%20are%20also,even%20further%20in%20some%20cases.&text=The%20tools%20and%20web%20pages,the%20CoWIN%20platform%20every%20day.
