### ISSUE TITLE
API testing

### ISSUE THREAD

**Issue by anmolkhemuka** [cowinapi/developer.cowin#156]
I was not able to test get OTP in postman on the production server API. Has anyone tried?

**Comment by gautam404** [comment]
Hey, Can you help me with Production Server API

**Comment by gautam404** [comment]
> I was not able to test get OTP in postman on the production server API. Has anyone tried?

Hey, Can you help me with Production Server API

**Comment by ghost** [comment]
{'errorCode': 'USRAUT0010', 'error': 'Mobile is Required'}
i am getting this error, i used requests module in python with request data as 
data={"mobile": "9999999999"}
and url as
"https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP"
it is correct right, why am I getting errors?

**Comment by ChethanChandra** [comment]
> data={"mobile": "999999999"}
> it is correct right, why am I getting errors?

may be because mobile number has to be 10 digits?

**Comment by ghost** [comment]
> > data={"mobile": "999999999"}
> > it is correct right, why am I getting errors?
> 
> may be because mobile number has to be 10 digits?

well..... i put my 10 digits number that is some random number for obvious reasons

**Comment by deepgandhi** [comment]
I have not tried request module in python, but using urllib3. You have to make json of {"mobile"="999999999"} and to pass as "body" keyword argument.

**Comment by siddhesh1770** [comment]
Guys, You have to post mobile no in json format in post method
try following
![image](https://user-images.githubusercontent.com/70662187/117887075-c77f9880-b2cd-11eb-8ee0-77c90edc6ad4.png)

**Comment by aditya2712** [comment]
> {'errorCode': 'USRAUT0010', 'error': 'Mobile is Required'}
> i am getting this error, i used requests module in python with request data as
> data={"mobile": "9999999999"}
> and url as
> "https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP"
> it is correct right, why am I getting errors?

**_You have to also pass content-type as application/json
For instance the JS code would be_**
```
fetchBody = {"mobile" : "9999999999"}
fetch('https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP',{
            method: 'post',
            body: JSON.stringify(fetchBody),
            headers: { 'Content-Type': 'application/json' }
})
```
