### ISSUE TITLE
anyone know how to work with this public api's with python requests library because in my case it always give 403

### ISSUE THREAD

**Issue by techsouravganguly** [cowinapi/developer.cowin#163]
### here is the code i have used in pyhton
url = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=800020&date=12-5-2021"
res = requests.get(url)
print(res.status_code)
this code always give 403
**but wirting the url directly pasting to the browser giving me results**
**if anyone knows how to work with these using python please help me with it.**

**Comment by athJ** [comment]
You have to give a common user agent in headers , like 
`"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",`

**Comment by PrettyCodes** [comment]
Thanks, @athJ this worked like a charm.
For anyone wondering, use the link https://www.whoishostingthis.com/tools/user-agent/ to get your headers and save that in a variable my_headers (or anything you wish) and add to the requests as shown below.

`jaipur1 = requests.get("https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=505&date="+str(today), headers={'User-Agent':my_headers})`

**Comment by techsouravganguly** [comment]
th

> You have to give a common user agent in headers , like
> `"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",`

**Comment by arclive202** [comment]
The common headers isn't working with Angular, when I test it in google chrome I get an error message like **Refused to set unsafe header "User-Agent"**
Can anyone help me out with this?

**Comment by athJ** [comment]
@arclive202 what library are you using with angular to call the API ? Axios ?
