### ISSUE TITLE
Confirm OTP error

### ISSUE THREAD

**Issue by akashkumar11110** [cowinapi/developer.cowin#164]
I getting this message despite of passing the SHA256 of otp and TxnId in Postman.
{"errorCode":"USRAUT0012", "error":"OTP is Required"}

Body:-
{
  "otp": "dab64b6247e4a9175aece970404a3d037acd4d94a9c69f422af0df921d792471",
  "txnId": "865f1177-10c1-45f6-b249-6c41d352b5cf"
}

anything else needs to be considered ?

**Comment by siddhesh1770** [comment]
please confirm that you are posting this data in json ?

**Comment by akashkumar11110** [comment]
> please confirm that you are posting this data in json ?

Thanks, I was posting it as text only. It worked now.
