### ISSUE TITLE
Bug:Multipe Slots booking with same adhar number 

### ISSUE THREAD

**Issue by tarunrawat87** [cowinapi/developer.cowin#165]
Hi,
i'm not sure if this is intended or is a bug but i was able to book two slots against one adhar card by two different account.
Is it okay or is this a bug ?

**Comment by siddhesh1770** [comment]
> Hi,
> i'm not sure if this is intended or is a bug but i was able to book two slots against one adhar card by two different account.
> Is it okay or is this a bug ?

currently there is no authentication with UIDAI, thats why you can create multiple profiles of same individual on multiple mobile number.
`print("Follow @siddhesh1770")`
