### ISSUE TITLE
token expiration time

### ISSUE THREAD

**Issue by hemantsingh011** [cowinapi/developer.cowin#175]
What is the token (received after login) expiration time?

**Comment by loflet** [comment]
It is 15 minutes.

**Comment by hemantsingh011** [comment]
@loflet thanks, how you get this information? As I was under assumption that OTP is valid for 3 minutes so might be token is also valid for 3 minutes

**Comment by loflet** [comment]
Once you get the bearer token, any token which is OAuth supported, you can view the meaning behind that here - https://jwt.io/  Like below, if you hover over "exp" you will see the time of the expiry.
![image](https://user-images.githubusercontent.com/7891707/118003187-fb0e0180-b365-11eb-8cf4-55fd91384eaa.png)

**Comment by hemantsingh011** [comment]
great, thanks :)

**Comment by patelhir** [comment]
> It is 15 minutes.

So when token expired, it gives token expired error or just unauthenticated access? I am constantly getting unauthenticated access error on all platform.

**Comment by loflet** [comment]
Yes, it gives an Unauthenticated access message once the token has expired, like below.
![image](https://user-images.githubusercontent.com/7891707/118004818-6e644300-b367-11eb-8e39-37c4b589b201.png)

**Comment by patelhir** [comment]
And have you passed any other extra headers other than token?

**Comment by loflet** [comment]
> 
> 
> And have you passed any other extra headers other than token?

Yes, I have. If I provide valid token then it works.

**Comment by hemantsingh011** [comment]
@loflet even if I pass token, sometimes I receive a cached (old) response for slot availability. Do you have any solution for the same?

**Comment by loflet** [comment]
> 
> 
> @loflet even if I pass token, sometimes I receive a cached (old) response for slot availability. Do you have any solution for the same?

Ohh is it so? I didn't receive anything like that, maybe I haven't tried with many request after token expiry. Just for my curiosity, which API were you calling?

**Comment by hemantsingh011** [comment]
I am polling /v2/appointment/sessions/public/calendarByDistrict

**Comment by loflet** [comment]
> 
> 
> I am polling /v2/appointment/sessions/public/calendarByDistrict

The API that you are calling is a public API and you don't need token for that as per API setu documentation. Also, this is the same API called on their public site as well without authentication.

**Comment by hemantsingh011** [comment]
@loflet which one I should use so that I can pass the token and get the latest availability slots?

**Comment by hemantsingh011** [comment]
I got the problem, I need to use a protected one. Thanks for your help @loflet

**Comment by patelhir** [comment]
@loflet  This is my python code for fetching beneficiaries

**Comment by patelhir** [comment]
Below is python code, i keep changing bearer token after 15 mins but for fetching beneficiaries i always get unauthenticated access:

Here is python code:

`import requests

url = "https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries"

headers = {
    'authorization': "Bearer {token}",
    'cache-control': "no-cache",
    'Accept-Language': 'hi_IN'
    }

response = requests.request("GET", url, headers=headers)

print(response.text)`

**Comment by loflet** [comment]
> 
> 
> Below is python code, i keep changing bearer token after 15 mins but for fetching beneficiaries i always get unauthenticated access:
> 
> Here is python code:
> 
> `import requests
> 
> url = "https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries"
> 
> headers = {
> 'authorization': "Bearer [Token]",
> 'cache-control': "no-cache",
> 'Accept-Language': 'hi_IN'
> }
> 
> response = requests.request("GET", url, headers=headers)
> 
> print(response.text)`

This api should work, mostly your token might have expired. I can see it expired at 2.26 PM. Also, please don't share your bearer token. It reveals your identity, even your phone number. Request you to delete/modify your message to not reveal the token.

**Comment by patelhir** [comment]
Thanks for pointing that, I have edited my comments but token displays in your comment. Can you please delete your comment?

And if you don't mind can you share your code python, php any, I still get unauthenticated access token even if I try immediately.
