### ISSUE TITLE
What are the rate limits?

### ISSUE THREAD

**Issue by avinassh** [cowinapi/developer.cowin#18]
How many requests I can make per second?

**Comment by m0j0r0j0** [comment]
100 per 5 mins

**Comment by avinassh** [comment]
@m0j0r0j0 are you from CoWin team or is this rate limit documented somewhere?

**Comment by sidlal154** [comment]
@avinassh They have updated it here: https://apisetu.gov.in/public/marketplace/api/cowin

**Comment by avinassh** [comment]
@nikogoul oh damn. thank you both.

**Comment by subrata304** [comment]
@nikogoul Can you please point out where exactly they mentioned about the rate limiter? I have gone through the doc but didn't find the same.
