### ISSUE TITLE
Forbidden message on public API

### ISSUE THREAD

**Issue by priyeshmashelkar** [cowinapi/developer.cowin#180]
I get http error 403 when I try to access the public API. Is this API not accessible outside India?

Response from API:
{"message": "Forbidden"}

**Comment by balakrishnakini** [comment]
Yes, CoWin API is not accessible outside India.

**Comment by dhs26206** [comment]
Me Same Problem

**Comment by pranavkarnik** [comment]
Getting "403, Error From CloudFront, Request Blocked"

**Comment by iamabhishek-n** [comment]
Make Sure you are hitting the API with an Indian IP, and add an user-agent to the request header before calling the API 

**User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36**

**Comment by saran-surya** [comment]
Hello @priyeshmashelkar which codebase are you using python or NODE ?, If NODE I have a workaround for it.
