### ISSUE TITLE
calenderByDistrict working fine in Postman but not working in android studio, i used okHttp client for making api calls/

### ISSUE THREAD

**Issue by sid077** [cowinapi/developer.cowin#182]
![Screenshot from 2021-05-13 10-41-50](https://user-images.githubusercontent.com/41814119/118081229-8922d000-b3d8-11eb-87e6-1591ca7dbe4c.png)

**Comment by sid077** [comment]
It's giving 401

**Comment by Ayushman-Saha** [comment]
Try adding a header to the request as  "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)". It worked for me!

**Comment by ninjabhishek** [comment]
the header shoule be 
{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

**Comment by sid077** [comment]
Actually the mistake was in the spelling of calendar and for android we can use system property to get user agent.
