### ISSUE TITLE
Public API returning 403

### ISSUE THREAD

**Issue by jaygandhi129** [cowinapi/developer.cowin#183]
Public API working fine in browser but returning 403 in my python application. I haven't exceeded the limit.
![Capture](https://user-images.githubusercontent.com/57639468/118088280-7615fd00-b3e4-11eb-94e1-ee2ac6a580be.JPG)
![Capture](https://user-images.githubusercontent.com/57639468/118088359-95ad2580-b3e4-11eb-948d-2db14e6ca148.JPG)

**Comment by Ayushgup85** [comment]
is your issue solved? I am also facing same issue.

**Comment by sarthi2395** [comment]
Been facing the same issue for a while. No luck.

**Comment by sarthi2395** [comment]
Found a workaround. The server returns 403 in all script initiated API requests. Try adding the header
````
User-Agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
````

This made it work in R scripts.

**Comment by saran-surya** [comment]
You have to add user-agents to access the data, Kindly try adding the user agents from @sarthi2395 , they work fine with NODE JS apps also

**Comment by jaygandhi129** [comment]
Worked fine!! Thanks @sarthi2395 @saran-surya

**Comment by RajendarKumar** [comment]
I am not able to generate OTP using following API, Try with postman as well and getting error :
{"errorCode":"USRAUT0010", "error":"Mobile is Required"}

curl -X POST "https://api.demo.co-vin.in/api/v2/auth/generateOTP" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"mobile\":\"9999988888\"}"

**Comment by saran-surya** [comment]
@RajendarKumar , Kindly try adding the country code 91xxxxxxxxx

**Comment by RajendarKumar** [comment]
tried with +91xxxxxxxxx and 91xxxxxxxxx both but no luck, still same issue @saran-surya

**Comment by sarthi2395** [comment]
Public API still has the 403 issue when you try to access it via scripts. Please add the below header to your API request. It should work then

````
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
````

**Comment by saran-surya** [comment]
The main problem with the API is that it is geofenced to INDIA, so if we have the server hosted outside India it will be a problem, so we have to go with workaround if the servers are not in INDIA.

**Comment by RajendarKumar** [comment]
I did try with a header as well GET is working but this post not working
here is my post request @saran-surya 

import requests

params={"mobile": "919999988888"}
headers={'User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'}
response = requests.post("https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP", data=params, headers=headers)

print(response.status_code)

**Comment by rdsoze** [comment]
@RajendarKumar send params in json format

```python
response = requests.post("https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP", data=json.dumps(params))
```

**Comment by RajendarKumar** [comment]
@rdsoze thank you it worked

**Comment by Codehappala** [comment]
> Public API still has the 403 issue when you try to access it via scripts. Please add the below header to your API request. It should work then
> 
> ```
> User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36o

on which platform did you run the script?

**Comment by Codehappala** [comment]
> > Public API still has the 403 issue when you try to access it via scripts. Please add the below header to your API request. It should work then
> > ```
> > User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36o
> > ```
> 
> on which platform did you run the script?

It seems none of the user agent settings work when the script is run from cloud based providers ,which may hit the host from outside india. correct me if i am wrong.

**Comment by KajalKukreja** [comment]
I tried with user agent header as well. But cowin api still returns 403 when I run below python code from my server.
``
import requests

url='https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=3&date=19-05-2021'
headers = {
    "accept": "application/json", 
    "Accept-Language": "hi_IN",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
}
x = requests.get(url, headers=headers)
print(x.text)
``

**Comment by jaygandhi129** [comment]
@KajalKukreja Are you hosting it somewhere? Cause Cowin API only allows Indian IP addresses to request data, You need to host it on a server located in India.

**Comment by jaygandhi129** [comment]
> > > Public API still has the 403 issue when you try to access it via scripts. Please add the below header to your API request. It should work then
> > > ```
> > > User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36o
> > > ```
> > 
> > 
> > on which platform did you run the script?
> 
> It seems none of the user agent settings work when the script is run from cloud based providers ,which may hit the host from outside india. correct me if i am wrong.

Yes, you are right!
