### ISSUE TITLE
Bug: Unable to view slots for the same day for 2nd dose 

### ISSUE THREAD

**Issue by attium** [cowinapi/developer.cowin#190]
For people trying to get the 2nd dose, only slots from the next day are visible in COWIN. 

Slots that have opened on the same day cannot be booked using COWIN even if they are available.

Screenshot , taken on **13/05/2021** (no filters applied, for a person registering for 2nd dose) 

![image](https://user-images.githubusercontent.com/38878456/118124719-9d37f300-b413-11eb-9750-7ffc3346fec3.png)

In the network tab, it can be seen the API is being called with the next day's date (**14/05/2021**)  :
![image](https://user-images.githubusercontent.com/38878456/118122183-1c2b2c80-b410-11eb-8bd7-e33add98ae30.png)

On the other hand, same-day slots are visible to people trying to book the first dose, and the API is being called with the **same day's date** 
 

![image](https://user-images.githubusercontent.com/38878456/118125044-18010e00-b414-11eb-8bf8-d66b2ad97711.png)

![image](https://user-images.githubusercontent.com/38878456/118122459-817f1d80-b410-11eb-84d4-9a7b4ddf8ef1.png)

**Comment by gopal-amlekar** [comment]
In my case, trying to book for 2nd slot, I can see the slots being requested starting same day. So there is some different reason it looks like in your case.

![image](https://user-images.githubusercontent.com/3242003/118141043-95ce1500-b426-11eb-9ec1-68fc59c01c91.png)

**Comment by shruthiiraju** [comment]
I have noticed this as well and posted a similar issue. Why did you close this issue? It is very much a problem for people booking 2nd dose.

**Comment by attium** [comment]
In my case, the person was due for the 2nd dose only on the next day. I hadn't considered this when I posted this issue and assumed that was the reason I couldn't book. That's why I closed it. 
I checked again the next day and found that I was able to book slots on the same day.
