### ISSUE TITLE
Calling public api from a hosted node app returns 403 Forbidden

### ISSUE THREAD

**Issue by me-nkr** [cowinapi/developer.cowin#191]
I have made a node script to call the public API, which works when run locally but returns 403 forbidden when called from hosted environment like openshift or glitch. Is there something that's blocking the api call from those platforms ?

**Comment by wittyPuneet** [comment]
You have to call it from an Indian IP address with a propert browser user agent in the header.

Unfortuntely, they seemed to have blocked DO Banglore IP ranges, and from latest reports, Azure India Central cloud functions server is blocked too.

**Comment by me-nkr** [comment]
so hosting it where can work ?

**Comment by saran-surya** [comment]
@me-nkr , I have a workaround for this, You can this package to proxy your server to your current location, It is working on heroku. BUT it only supports get requests, and no post requests are allowed. [https://github.com/saran-surya/cassata](https://github.com/saran-surya/cassata)

**Comment by trkailash** [comment]
@me-nkr did you get bearer-token APIs to work from localhost? I did use correct headers for user-agent. For auth I use authorization set to Bearer ${token-string}. Not able to say why calls to beneficiaries and schedule fails ... Insight would help.

**Comment by me-nkr** [comment]
@saran-surya hey that package looks promising. Unfortunately my server is a web socket server so I don't think this one can help.

**Comment by me-nkr** [comment]
@trkailash I haven't still figured out how to use the protected api, the public one works locally, I think issue #177 might help you.

**Comment by me-nkr** [comment]
@wittyPuneet when I was testing locally it worked without any trouble, even without headers specified. When I hosted it on glitch and openshift, it was returning `403 Forbidden`. And now when I hosted it on a aws lightsail instance running at `ap-south-1a` region, the api is returning `{ sessions: [] }`. What is happening exactly ?

**Comment by saran-surya** [comment]
> @saran-surya hey that package looks promising. Unfortunately my server is a web socket server so I don't think this one can help.

@me-nkr The package work seamlessly on node + express servers. I have also tested it with HEROKU server hosted in US and i am able to proxy the data.

**Comment by Raxy45** [comment]
> > @saran-surya hey that package looks promising. Unfortunately my server is a web socket server so I don't think this one can help.
> 
> @me-nkr The package work seamlessly on node + express servers. I have also tested it with HEROKU server hosted in US and i am able to proxy the data.

Your package looks promising can you help me up with the setup for NodeJS app hosted on heroku ?!

**Comment by saran-surya** [comment]
Hi @Raxy45, I have a complete documentation in the repository, Kindly look into them they should solve all your issues, if so you are facing some issues, Kindly contact me, Happy to help 💯
