### ISSUE TITLE
where to get token from to use download certificate API.

### ISSUE THREAD

**Issue by m0j0r0j0** [cowinapi/developer.cowin#20]
where to get token from to use download certificate API?

**Comment by amitvsavant** [comment]
Please refer to [User Authentication APIs](https://apisetu.gov.in/public/api/cowin/). A Bearer token is returned in the response of /confirmOTP This token is used to download a certificate.

**Comment by ajkumark** [comment]
How to convert the OTP received in phone to the long string which should be used in **/v2/auth/public/confirmOTP** API?

**Comment by vsingal-p** [comment]
^ +1. Same doubt

**Comment by apugoneappu** [comment]
You can convert the OTP to SHA256 using [https://emn178.github.io/online-tools/sha256.html](https://emn178.github.io/online-tools/sha256.html)

**Comment by m0j0r0j0** [comment]
> You can convert the OTP to SHA256 using https://emn178.github.io/online-tools/sha256.html

Worked! closing this.

**Comment by Anirudhk07** [comment]
Can someone pls tell how to use the `Bearer Token` to further request for the certificate. 

For eg. I first used `/v2/auth/public/generateOTP` To generate otp and got the `txn-id`. After this I confirmed the OTP and `txn-id`.  In return I got back a **Token**.

After this how should I request for the certificate api ? What to do with **Token**? How to use this API - `/v2/registration/certificate/public/download`
