### ISSUE TITLE
[feature request] Separate slots for first dose and second dose

### ISSUE THREAD

**Issue by arundevma** [cowinapi/developer.cowin#204]
Since vaccine are having acute shortage in some states like Kerala, many people who took first dose are unable to book second dose slots. Whenever slots are opened, it gets booked in few minutes and most of the booking are done by people looking for first dose. Will it be possible to add separate slots for first dose and second dose so that hospitals can list them separately?

For eg:- a hospital can put 100 slots for first dose  and 100 slots for second dose on the same date.  People who has taken 1st dose can book only second dose slots and vice versa. @cowinapi

**Comment by gimmevaccine** [comment]
Given that the two doses for the Sputnik vaccine (which is likely to be circulated soon) are actually two slightly different formulations, this feature would be necessary.

AFAIK, the CoWIN devs are already working on this, as indicated in issue #60.

**Comment by arundevma** [comment]
This feature is currently implemented. So closing the request
