### ISSUE TITLE
U45 telegram groups

### ISSUE THREAD

**Issue by rudhacharya** [cowinapi/developer.cowin#215]
How do the telegram groups fetch what seems to be fresh data? Are they also using the public APIs? They often send notifications of slot availability even when none of the APIs (calendarByDistrict/Pin, findByDistrict/Pin) show any slots available.

**Comment by AkashKrDutta** [comment]
I haven't noticed them sending notification any time soon than reflected at public API. But if indeed that's the case, my guess is one can be "authorized" to subscribe to certain events in a webhook as stated in the api doc:
```
Please contact Ministry of Health and Family Welfare, Government of India to get access to these APIs. [Updated on 11 May 2021]
```

**Comment by rohandhamapurkar** [comment]
All threads are saying that findByDistrict gives more real-time data, which is what people are using in most telegram groups.
