### ISSUE TITLE
findByDistrict is NOT returning any data

### ISSUE THREAD

**Issue by amlanrd** [cowinapi/developer.cowin#216]
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=53&date=16-05-2021 is returning data accurately. 
But, https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=53&date=16-05-2021 is NOT returning any data.

Anyone aware of this, what could be the issue?

**Comment by AkashKrDutta** [comment]
From the definition, findByDistrict only lists sessions where there is atleast one capacity, while calendarByDistrict lists all in 7 days period.

**Comment by amlanrd** [comment]
Is there any official statement on the same? They have only mentioned "API to get planned vaccination sessions on a specific date in a given district."

**Comment by amlanrd** [comment]
> From the definition, findByDistrict only lists sessions where there is atleast one capacity, while calendarByDistrict lists all in 7 days period.

Is there any official statement on the same? They have only mentioned "API to get planned vaccination sessions on a specific date in a given district."

**Comment by AkashKrDutta** [comment]
https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2, the "atleast one capacity" remark is just observation based.
