### ISSUE TITLE
403 Error 

### ISSUE THREAD

**Issue by kaushikpuka1998** [cowinapi/developer.cowin#22]
403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Can anyone say is there any problem going on this API??

**Comment by mtwn105** [comment]
Multiple reasons possible due to which this error occurred -
1. Trying to access from outside India
2. Exceeded rate limit of 100 per 5 mins per IP
3. Missing browser headers

**Comment by kartikaydw** [comment]
Still getting 403
- Accessing from India.
- Rate limit not exceeded (under 100 requests)
- Trying to access https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=294&date=06-05-2021

**Comment by kartikaydw** [comment]
@kaushikpuka1998
for python request it works like this

header = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    link = f"https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=294&date={date}-05-2021"
    f = requests.get(link, headers=header)

**Comment by RoystonDmello** [comment]
@kartikaydw this worked. Thanks!

**Comment by avin3sh** [comment]
Spoofing user agent header is against API Setu TOS. You shouldn't be doing this!

**Comment by RoystonDmello** [comment]
@avin3sh then what is the API Setu TOS compliant solution to this problem?

**Comment by kartikaydw** [comment]
@avin3sh yes , would like to know what is a proper way to do this as per TOS . @cowinapi can you guide please guide . The API's are broken from days

**Comment by satishchandra-pandey** [comment]
Duplicate please refer issue #19
