### ISSUE TITLE
Api Cache issue

### ISSUE THREAD

**Issue by amanjain325** [cowinapi/developer.cowin#220]
I am using https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=146&date=15-05-2021 in cron job and calling after every 4 seconds. But the actual remaining slot data is coming late. 

Does anyone knows, is there any caching in this api?
How can I overcome to this issue so it should become real time?

I also don't know some telegram groups are sending notification even before data comes from above api. Do anyone knows which apis they are using?

**Comment by AkashKrDutta** [comment]
There is caching of 30 mins as described in official api site. And default cron doesn't have seconds granularity, you might wanna check your config.

**Comment by amanjain325** [comment]
@AkashKrDutta If I want to generate Auth token after every 15 min so to use protected apis. Can u tell me how can I do that?

**Comment by amanjain325** [comment]
> @AkashKrDutta If I want to generate Auth token after every 15 min so to use protected apis. Can u tell me how can I do that?

Or What is the way to use protected apis?

**Comment by AkashKrDutta** [comment]
You'd have to automate the whole otp retrieval workflow (auth process in short), unless they support refresh tokens (which they don't seem to do at the moment). I would suggest instead using the public APIs that don't need user token. Specifically using the findByDistrict api call, which doesn't seem to cache at all as pointed out by others in different threads. I use the same.

**Comment by amanjain325** [comment]
@AkashKrDutta As I am using the Delhi location which consists of 11 districts, so I have to call apis after every 30 seconds, which gives a huge lag in fetching slots. Can u please help me how can I reduce the interval to 10 seconds or less than that?

**Comment by AkashKrDutta** [comment]
Use more than 1 Ips. 30 seconds is honestly not that high right? Also, using Aarogya setu, you can bypass captcha.

**Comment by dhruvjindal213** [comment]
@AkashKrDutta 

Hi, are you sure about the findByDistrict API? I have been using calendarByDistrict and it definitely doesn't show real-time data.

**Comment by AkashKrDutta** [comment]
@dhruvjindal213  Others in different issue threads, have pointed out findByDistrict gives a more real time data, sometimes better than under45.in etc telegram groups.
