### ISSUE TITLE
[feature-request] Add a new filter in the UI to display only centres with available slots

### ISSUE THREAD

**Issue by harshit-sh** [cowinapi/developer.cowin#230]
I sometimes see that a particular centre has one/two odd available slots on the day when the slots open up in a city. This feature would help in better access to users to such slots.

**Comment by kichappa** [comment]
Why wouldn't you filter it from the API response that is available now?

**Comment by harshit-sh** [comment]
I meant this as an enhancement for the Cowin UI since it is troublesome to go through all the centres (including centres which are completely booked) when booking a slot. Closing this issue.
