### ISSUE TITLE
Wrong API data

### ISSUE THREAD

**Issue by Kanchangk** [cowinapi/developer.cowin#231]
Since last night, I am getting wrong API data (even the CoWin.gov.in website showing wrong data when one search for the slots without logging in).  The issue is still there. Is anyone else is having this issue? The API seems to be broken (or intentionally broken?)

**Comment by Shrey-Sheladia** [comment]
Having the same issue as well

**Comment by kichappa** [comment]
I, too, am facing the same issue.

**Comment by Kanchangk** [comment]
Issue got resolved after I made changes in code related to API response of dose 1 and dose 2 (new modifications in API response)
