### ISSUE TITLE
403 error via postman for prod api

### ISSUE THREAD

**Issue by sanjaychembali** [cowinapi/developer.cowin#26]
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.

Pls let me know if I am missing anything

**Comment by satishchandra-pandey** [comment]
Duplicate please refer issue #19
