### ISSUE TITLE
Problem in otp generation while in Production

### ISSUE THREAD

**Issue by aditya2712** [cowinapi/developer.cowin#265]
I used the api to generate otp. I used node-fetch for fetching the api. 
I passed all the necessary headers, except bearer auth (I don't know is it necessary or not), but my application is working fine in development environment (localhost). While in the production (deployed on heroku US servers), the generateOtp api is not sending otp.
Is it related to bearer auth, if so please guide, on how to generate it and add it in headers.
Or is it some problem of heroku US server, because someone said that it is a problem of geolocation !! 
P.S. : If someone wants to see my code , here is the repository: [https://github.com/aditya2712/vaccine-notify](https://github.com/aditya2712/vaccine-notify)

**Comment by ninjabhishek** [comment]
Geolocation is an issue, since covin apis allow requests originating from Indian IP only

**Comment by aditya2712** [comment]
@ninjabhishek 
Is there any free Indian Service/server where I can deploy?

**Comment by ninjabhishek** [comment]
Well, for starters, a basic server on AWS is free for 1 year, so you can try that. Or maybe on gcp and azure as well, they offer credits along with free basic server. Just make sure you chose your DC in India location. I have been running my services on Azure and they are working fine
