### ISSUE TITLE
Python Code for Telegram Notifications for Slot Availability Not Working Please Check and Help ..

### ISSUE THREAD

**Issue by SHEKHAR-SAHU-JAIPUR** [cowinapi/developer.cowin#267]
#!/usr/bin/python3

import requests
import datetime
import json
import time

browser_header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}

Message = ""
date=""
fulldate=""
flag2 = False

while(True):
    Message = ""
    flag2 = False
    sysdate = datetime.datetime.today()
    next_sysdate = sysdate + datetime.timedelta(days=1)
    
    sysdate2 = sysdate.strftime("%d-%m-%Y")
    next_sysdate2 = next_sysdate.strftime("%d-%m-%Y")

    sysdate3 = sysdate.strftime("%d-%m-%Y %H:%M:%S")
    next_sysdate3 = next_sysdate.strftime("%d-%m-%Y %H:%M:%S")
    
    
    hour = sysdate.strftime("%H")
    if(int(hour)>=9):
        date = next_sysdate2
        fulldate = next_sysdate3
    else:
        date = sysdate2
        fulldate = sysdate3
    
    URL = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id={}&date={}".format(505, date)
    try:
        response = requests.get(URL, headers=browser_header)
        
        if str(response) == "<Response [403]>":
            print(fulldate + " Your API Hit Limit exceeded.. " + str(response))
        else:
            print(fulldate + " API Hits within Limits " + str(response))
        
    except:
        {print("Internet Not Working")}
    else:   
        if response.ok:
            resp_json = json.loads(response.text)
            if resp_json["centers"]:
                for center in resp_json["centers"]:
                    for session in center["sessions"]:
                        if session["min_age_limit"] == 18 and session["available_capacity"] > 1 :
                            Message = Message + "-------------\n" + "M-J1-Slot Detail:\n" + "Date-" + str(date) + "\nName-" + center["name"] + "\nDist-" + center["district_name"] + "\nFee-" + center["fee_type"] + "\nAge-"+str(session["min_age_limit"]) + "\nAval Cap-"+str(session["available_capacity"]) + "\nVacc Name-"+session["vaccine"] + "\n-----------\n\n"
                            flag2 = True
                        
                
    if(flag2):
        url1 = "https://api.telegram.org/bot[BOT API {I have it ..}]/sendMessage?chat_id=-1**11**244***&text=M-J1-URGENT!! Slot Available"
        requests.post(url1)
        url2 = "https://api.telegram.org/bot[BOT API {I have it ..}]/sendMessage?chat_id=-1**11**244***&text={}".format(Message)
        requests.post(url2)

    
    time.sleep(3.00001)

**Comment by hemantsavkar** [comment]
What issue are you getting ?

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
Hy Hemant , Actually whenever there are slots , I mean whenever other telegram channels give notifications of slots , my script never responds

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
I tested the script for , available_capacity == 0 (it works very well) , i checked script for available_capacity > 1 {for rural areas , where there is always slots are available} ,, but no notification when i choose jaipur I or jaipur II as district

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
Just tell me one thing ,, i should go for calendarByDistrict OR findByDistrict

**Comment by Harshini2898** [comment]
calendarByDistrict : It is used to get planned vaccination sessions for 7 days from a specific date in a given district.
findByDistrict: It is used to get planned vaccination sessions on a specific date in a given district.
Based on data you need, you can use any endpoint.

**Comment by hemantsavkar** [comment]
> Just tell me one thing ,, i should go for calendarByDistrict OR findByDistrict

You can use any, however considering the restrictions those are added, if you calling API endpoint 100 times in 5 minutes then those will be throttled. So better option is to use the findByDistrict endpoint and have your own parsing logic to get slots for specific Pincode.
