### ISSUE TITLE
Appointment Availability public api is returning 403 Error.

### ISSUE THREAD

**Issue by Sayandeep** [cowinapi/developer.cowin#268]
I am using **PHP** and **cURL** to fetch the **findByPin** API data. In my local it is working fine , but it is returning the below error when I am deploying it to my website:

> Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Please find my code below:

```php
<?php
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=799264&date=19-05-2021',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
    '
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
?>
```

**Comment by SHEKHAR-SAHU-JAIPUR** [comment]
Keep changing your ip address,,
allowed api hits are 100 in 5 minutes per IP

**Comment by hemantsavkar** [comment]
If your server is out of India then it will not work!
The team has made all efforts to give Citizens a pain for booking...

**Comment by Sayandeep** [comment]
> If your server is out of India then it will not work!

Yes the Server is from Singapore , but what is the resolution then ?

**Comment by hemantsavkar** [comment]
> > If your server is out of India then it will not work!
> 
> Yes the Server is from Singapore , but what is the resolution then ?

Buy some local cheap webhosting
