### ISSUE TITLE
Not receiving OTP on my mobile from last two days

### ISSUE THREAD

**Issue by akashkumar11110** [cowinapi/developer.cowin#274]
Previously it was coming but now it stopped. I was doing some api programming and tested this api many times in a day. It works fine for other mobile numbers but for a particular one from which I was testing is not receiving OTP anymore. Checked with n/w operator as well, all seems to be fine. 

Is anyone else also facing this issue ? anything else which I should try ?

**Comment by abhaira** [comment]
Facing the same issue. Error code 403 is returned.

**Comment by akashkumar11110** [comment]
> Facing the same issue. Error code 403 is returned.

I am getting the txn code in postman but not receiving the OTP on mobile.

**Comment by abhaira** [comment]
are you using any headers also, in postman?

**Comment by akashkumar11110** [comment]
> are you using any headers also, in postman?

yes. 
set the 'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

**Comment by abhaira** [comment]
could you share?

**Comment by akashkumar11110** [comment]
> could you share?

shared in my previous comment.
