### ISSUE TITLE
Authorization in API

### ISSUE THREAD

**Issue by rutup** [cowinapi/developer.cowin#28]
Hi Team,
API seems not to require authorization. But why there is Authorization button in swagger page

**Comment by amitvsavant** [comment]
@rutup , authorization is required for certificate download API.

**Comment by vsadhav02** [comment]
Once I get bearer token post OTP authentication, how to use it to call endpoint to see slot available? I tried to set "Authorization" header as "Bearer xxxxxx" where xxxx is actual token. But I get 403 status response.  I tried replacing work Bearer with basic, JWT but nothing works, may be I am setting authorization wrongly?

**Comment by rutup** [comment]
I am not correct person to respond but as far as i know you dont need to have token for slot availability
see sample URL `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=600119&date=01-05-2021`

**Comment by chefpk23** [comment]
I tried making post call to ​/v2​/auth​/public​/generateOTP by giving my mobile number in the body and received txnId in the response. Now to call /v2/auth/public/confirmOTP, we need both OTP and txnId. The OTP example mentioned in the swagger is string but what we get is a 6 digit number. When I tried with that 6 digit OTP and txnId I received from my first api call, I get - 
{ "errorCode": "USRAUT0014", "error": "Invalid OTP" }

Wondering what would be the right value of OTP for the confirmOTP API call.

**Comment by apugoneappu** [comment]
@chefpk23 Please see https://github.com/cowinapi/developer.cowin/issues/20#issuecomment-833243981

**Comment by vsadhav02** [comment]
> I am not correct person to respond but as far as i know you dont need to have token for slot availability
> 
> see sample URL `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=600119&date=01-05-2021`

@rutup thanks, I see I have to add header with user-agent to make it work.

**Comment by HemantDriefcase** [comment]
Hi Team,

I have raised GET request to API: 
https://cdn-api.co-vin.in/api/v2/admin/location/districts/16
From Postman. I am getting below response.

Response :
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: wJKVkKH1IpLuju6NM7Te7pF8YR8JW9FIu4tcVvqHIMtNs6JrZuEg7Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
