### ISSUE TITLE
Always getting Error 401 : Unauthenticated Access

### ISSUE THREAD

**Issue by Spunky02** [cowinapi/developer.cowin#281]
i am trying to send a get request to the Cowin API and getting the error 401 every time. Please someone tell me how to fix it.
I am also using the API key with a value.

![image](https://user-images.githubusercontent.com/31632023/118776689-e077e300-b8a5-11eb-8ea6-6f844ebfc137.png)

**Comment by parjanyaacoder** [comment]
Please tell from where to get API key. @Spunky02

**Comment by Spunky02** [comment]
> Please tell from where to get API key. @Spunky02
https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2
you can use this demo server and authorize yourself.

PS: I found why I was getting the issue.  Free version of POSTMAN gives us a random region to send requests and Cowin API server only accepts request from Indian Region that is why I was getting ERROR : 401
