### ISSUE TITLE
Is API key required for protected endpoints?

### ISSUE THREAD

**Issue by patelhir** [cowinapi/developer.cowin#284]
Can anyone here confirm to access protected endpoints we need API key or not? I am able to get token but that token never works and gives unauthenticated access.

**Comment by amanjain325** [comment]
You don't need any API keys in protected key.

You have to use generate otp and confirm otp api which will return u a token. Pass that token in Authorization header with Bearer

**Comment by patelhir** [comment]
I did that, but no luck. Do you code in PHP/Python, if so can you please paste the code?


` `headers = {
    'Authorization': "Bearer {token}",
    'Accept-Language': 'hi_IN',
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'User-Agent': user_agent_desktop
    }``

**Comment by amanjain325** [comment]
This is a document which I found. It will help you.

https://documenter.getpostman.com/view/9564387/TzRPip7u#bc8f4d99-fdf8-4742-8d8c-c916e2be2371

**Comment by patelhir** [comment]
Final conclusion is we don't need API key to use protected end points.

**Comment by gupta-nikhil** [comment]
How do you manage to access
