### ISSUE TITLE
How to query the test server for beneficiaries?

### ISSUE THREAD

**Issue by apugoneappu** [cowinapi/developer.cowin#29]
## What is the correct way to use the test server (for any API such as getting beneficiary etc)?

I am getting an authentication error on trying the following 
```
curl --location --request GET 'https://api.demo.co-vin.in/api/v2/appointment/beneficiaries' \
--header 'accept: application/json' \
--header 'authorization: Bearer <AUTH_TOKEN_HERE>' \
--header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36' \
--header 'x-api-key: 3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi'
```
by replacing the <AUTH_TOKEN_HERE> with my auth token.

@amitvsavant @chalukyamohanraj @satishchandra-pandey

**Comment by apugoneappu** [comment]
Sorry, I'm not getting an auth error but instead 
```
{
    "errorCode": "APPOIN0001",
    "error": "No beneficiary found for provided beneficiary mobile number 9876543210"
}
```

**Comment by amitvsavant** [comment]
Yes, you may be getting this error because currently no beneficiary is registered with this mobile number in the test server. You will have to first register beneficiaries with this mobile number by calling [Beneficiary Registration APIs](https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2#/Beneficiary%20Registration%20APIs).

**Comment by aravindkumar01** [comment]
@amitvsavant I m facing the following issue access the first time on APIS.

API:
https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP
Responce:
{"errorCode":"USRAUT0024", "error":"Beneficiary Not Registered"}

Notes:
1.Used SHA256 for OTP conversion.

Please check and do the needful.
