### ISSUE TITLE
Data issue : District list contains data issue

### ISSUE THREAD

**Issue by iamvickyav** [cowinapi/developer.cowin#3]
For state of Tamil Nadu, few taluks are mentioned as districts 

E.g. Palani, Kovilpatti, Cheyyar etc are not districts but **taluks**. But they are coming under districts in https://www.cowin.gov.in/home slot availability. Pls validate the data

**Comment by cowinapi** [comment]
Thank You for your observation and feedback, Our team will be check and clean the data!
