### ISSUE TITLE
403 Error, is it maintenance hour

### ISSUE THREAD

**Issue by tejaswinichile** [cowinapi/developer.cowin#30]
getting this error since morning.
`We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.`

When we try to find by pin or find by district It's giving an error 403.

We are using 6 API calls just for my pin codes per 30 minutes. which doesn't cross the limit mentioned `these APIs are subject to a rate limit of 100 API calls per 5 minutes per `

I tested for other pincodes too : `curl -X GET "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=110001&date=07-05-2021" -H "accept: application/json" -H "Accept-Language: hi_IN"`

**Comment by lazy-way** [comment]
Setting user agent before making the call works for me.
For java it looks like this:
connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");

**Comment by tejaswinichile** [comment]
Oh yeah worked thanks :)

**Comment by tejaswinichile** [comment]
Closing this.
