### ISSUE TITLE
I believe the APIs are being abused to book slots in seconds as soon as there is an availability. 

### ISSUE THREAD

**Issue by anantmi3** [cowinapi/developer.cowin#305]
There are chances of malicious use of this APIs, where people are booking the slots as soon as a slot is opened and hence others are unavailable to book through the normal process.
People might be booking slots at the very next second through code as soon as a slot gets opened which I believe is not a good solution for the normal non technical people.

**Comment by alokas** [comment]
I dont think that is happening (or at least widely). The Appointment API's are protected, so not everyone can get access to it.

**Comment by Ajax-Light** [comment]
If it actually is a **Protected "API"** how are the slots getting booked in a millisec? 
This is obviously a scam, the slots shown are just a token gesture to show how "technologically advanced" we are. Who cares about them adopting the Open API standards when you need a User-Agent hack to get this **"API"**, if it even is one, to work?
