### ISSUE TITLE
Add Public API for getting a list of Beneficiaries 

### ISSUE THREAD

**Issue by alokas** [cowinapi/developer.cowin#308]
Please make the "/v2/appointment/beneficiaries" as a Public API. This will allow us to see the beneficiaries, and if they have been vaccinated. We are making a system, in which the person has to enter their beneficiary number in addition to mobile number and authenticate with the OTP to get the certificate. 

We simply need the following 

`{
  "beneficiaries": [
    {
      "beneficiary_reference_id": "1234567890123",
      "name": "Rajesh Pawar",
      "birth_year": "1995",
      "gender": "Male",
      "mobile_number": "******1403",
      "photo_id_type": "Driving License",
      "photo_id_number": "********9999",
      "comorbidity_ind": "Y",
      "vaccination_status": "Not Vaccinated",
      "vaccine": "COVISHIELD",
      "dose1_date": "01-03-2021",
      "dose2_date": "29-03-2021"
   }
]
}`

If making it public is not possible, can you please let us know the steps to get the protected API access.

**Comment by alokas** [comment]
This is to simplify the process of the company systems to be able to download the certificate of the employees directly from the COWIN to keep it in our database (Offcourse after the permission from the employee and the OTP that will be generated by Cowin itself) 

Thanks!

**Comment by alokas** [comment]
I have found a workaround! Thanks. Not needed now

**Comment by vishal24tuniki** [comment]
@alokas What is the workaround? Can help us too

**Comment by shekharkumar86** [comment]
> I have found a workaround! Thanks. Not needed now

please help me, i am facing the Unauthenticated access! 401 error code. to get the beneficiaries list 

i am using this url : https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries

i got the toke from confirmOTP api and put as bearer token but i am facing the Unauthenticated access error.

**Comment by arunim2405** [comment]
@alokas  what is the workaround?
