### ISSUE TITLE
Co-Win API Credentials

### ISSUE THREAD

**Issue by ghost** [cowinapi/developer.cowin#31]
How will I get the API credentials to use this service?

**Comment by arun-chib** [comment]
Credentials aren't required for API thats why they are public APIs.

**Comment by anishgowda21** [comment]
I think there is no credentials for the api , except for the certificate api for which u need beneficiary reference id .
If you are trying to access metadata or appointment api from python or any other scripts u need an header

**Comment by Anirudhk07** [comment]
@anishgowda21  Even thought the Certificate API is public , I am getting `Unauthenticated access!` even after entering correct beneficiary reference id. Can someone help regarding this ?

**Comment by anishgowda21** [comment]
I don't have any id's to test it out by the way did u use headers while making the request?and what are you using to make the request like curl or a python script

**Comment by siddhesh1770** [comment]
> @anishgowda21 Even thought the Certificate API is public , I am getting `Unauthenticated access!` even after entering correct beneficiary reference id. Can someone help regarding this ?

You have to use bearer token in headers which was acquired by logging in user
`
print("If this worked please follow me @siddhesh1770")`

**Comment by nikant20** [comment]
Hi @siddhesh1770 , can you please provide a sample code for using bearer token in headers? It will be helpful.
