### ISSUE TITLE
Vaccine name for SPUTNIK V?

### ISSUE THREAD

**Issue by mtwn105** [cowinapi/developer.cowin#310]
What will be the vaccine name for Sputnik V? 
Like for Covishield and Covaxin has COVISHIED & COVAXIN respectively in the `sessions` object under `center`

**Comment by vishalv26** [comment]
It will be `Sputnik V` already tested when there was availability in HYD

**Comment by kanaksinghal** [comment]
Are you sure about the casing @vishalv26 ? But the other brand names are in uppercase

**Comment by karanssh** [comment]
@vishalv26 would it be possible to share a json response of what you got during your testing?
