### ISSUE TITLE
Is it possible to get the list of center-id's for a district

### ISSUE THREAD

**Issue by aravindrajk** [cowinapi/developer.cowin#315]
Currently any API gives the center-id and name whenever there is any availability or 0. But is there any data dump or way to get the list of center-names and id's for given district id.

**Comment by KuroStack** [comment]
You can refer to Cowin API Doc. Seems there is no API which provide the dump of center but there are API's which can provide you the list of available centers for given date:

https://apisetu.gov.in/public/api/cowin#/Appointment%20Availability%20APIs/calendarByCenter
The above will return list of the centers with available slot for the week

**Comment by aravindrajk** [comment]
yeah.. it needs the center_id and date and parameters. 

District or pincode api's does not give the center which i was looking for. So i thought of checking if there is any dump to take the center-id.

Closing this as it is currently not present.
