### ISSUE TITLE
Which encryption algorithm to be applied on OTP while sending it in ConfirmOTP API call

### ISSUE THREAD

**Issue by asimamitavm** [cowinapi/developer.cowin#317]
{
  "otp": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
  "txnId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

The expected otp is in 64 chars, does any one know which encryption algo is to be applied on OTP.

**Comment by KuroStack** [comment]
Duplicate of issue no 101 (https://github.com/cowinapi/developer.cowin/issues/101)

**Comment by amit4996** [comment]
SHA-256

**Comment by theGeekyLad** [comment]
@asimamitavm please close the issue once done. 👍🏼

**Comment by asimamitavm** [comment]
Thanks for the reply.
