### ISSUE TITLE
Unable to get OTP when i refresh the page (for few minutes )

### ISSUE THREAD

**Issue by amit4996** [cowinapi/developer.cowin#320]
![image](https://user-images.githubusercontent.com/69569478/119245872-25e42b00-bb9a-11eb-8394-b60160799a6e.png)

Can anyone help me with the issue i am able to get otp when i click on submit for first time , it shows error when i refresh it again . Is it because i can generate only one otp which is then valid for few minutes and only then i can generate a new otp ?

**Comment by KuroStack** [comment]
If you refresh page after generating the OTP then you have to wait for few minutes(1-2) before generating the otp for same number.

**Comment by manovasanth1227** [comment]
Unable to get the otp... Can you send the otp generation code in js??
