### ISSUE TITLE
Zero availability centers showing up in findByDistrict public API

### ISSUE THREAD

**Issue by kranthitej** [cowinapi/developer.cowin#323]
Hi,

Why are vaccination centers with no slots (no slots for dose1 and dose2) showing up in the findByDistrict public API? Earlier, only centers with available slots were showing up in the API response. I have provided a sample response below (where slots are not available and still response includes the center):

{
            "address": "Fortis Escort Heart Institute Red Building Okhla RoadSukhdev Vihar Metro Station New Delhi",
            "available_capacity": 0,
            "available_capacity_dose1": 0,
            "available_capacity_dose2": 0,
            "block_name": "Not Applicable",
            "center_id": 706727,
            "date": "23-05-2021",
            "district_name": "South East Delhi",
            "fee": "850",
            "fee_type": "Paid",
            "from": "09:00:00",
            "lat": 28,
            "long": 77,
            "min_age_limit": 18,
            "name": "Fortis Escort Red Bldg Site 4",
            "pincode": 110025,
            "session_id": "f6900e85-e1d4-4325-979f-0167ef4f7c10",
            "slots": [
                "09:00AM-11:00AM",
                "11:00AM-01:00PM",
                "01:00PM-03:00PM",
                "03:00PM-05:00PM"
            ],
            "state_name": "Delhi",
            "to": "17:00:00",
            "vaccine": "COVISHIELD"
        }

Kindly help me with this. Did the response schema change?

**Comment by worstcoderofalltime** [comment]
The findByDistrict API shows all the center details for next 7 days for the given District ID, no matter if slots are available or not. It has always been that way, at least since the start of May.

Now you have to use the conditions to filter out the centers based on your criteria.

**Comment by kranthitej** [comment]
> The findByDistrict API shows all the center details for next 7 days for the given District ID, no matter if slots are available or not. It has always been that way, at least since the start of May.
> 
> Now you have to use the conditions to filter out the centers based on your criteria.

No. That is the calendarbyDistrict API. The findByDistrict API has been giving only available slots information up until yesterday.

**Comment by kartikeyas00** [comment]
This is working with my code. You can find it [here](https://github.com/kartikeyas00/cowin-automate)

**Comment by kranthitej** [comment]
> This is working with my code. You can find it [here](https://github.com/kartikeyas00/cowin-automate)

This also uses the calendarByDistrict API. My question is about the response of findByDistrict API.

**Comment by kartikeyas00** [comment]
> > This is working with my code. You can find it [here](https://github.com/kartikeyas00/cowin-automate)
> 
> This also uses the calendarByDistrict API. My question is about the response of findByDistrict API.

Oops, I misread it. Sorry about that!
