### ISSUE TITLE
Getting 403 on digital ocean server BLR1 region

### ISSUE THREAD

**Issue by Shrenik27** [cowinapi/developer.cowin#324]
Hi,

I'm getting a 403  error on my digital ocean server which is situated in Bangalore when using the public API. I have also used the agent user headers but still, the problem persists. However, on my local server, the API is running just fine.

Please tell me how can I resolve this?

**Comment by Shrenik27** [comment]
Shifted to another service provider. Marking it as closed

**Comment by kartikeyas00** [comment]
I think on DigitalOcean after some time it starts to get the 200 response back
