### ISSUE TITLE
Co-Win API not supporting multi language like Hindi(hi_IN)

### ISSUE THREAD

**Issue by amitkrgautm** [cowinapi/developer.cowin#329]
![image](https://user-images.githubusercontent.com/36753607/119305993-21e20700-bc87-11eb-8999-bee8aa1f794e.png)

**Comment by amitkrgautm** [comment]
@cowinapi Any update about this

**Comment by kichappa** [comment]
This is not a problem with the accepted language. This is a CORS error.

**Comment by amitkrgautm** [comment]
This is from co-win swagger api. Do you know how we can use multi language with co win Api

**Comment by kichappa** [comment]
> Do you know how we can use multi-language with co win API?

I don't think the CoWin backend provides replies in multiple languages.

**Comment by amitkrgautm** [comment]
![5F702C50-0F51-4798-841C-0089A44B6DCD](https://user-images.githubusercontent.com/36753607/119520286-c9e6f580-bd97-11eb-8cf3-58a5bfeb1980.png)

look they have mentioned

**Comment by kichappa** [comment]
> look they have mentioned

I know. That might just be for namesake but is not functional.
