### ISSUE TITLE
API endpoint for Slot availability continuously returning 403 error .. even though hitting the endpoint under the prescribed rate limits. 

### ISSUE THREAD

**Issue by Akki1308** [cowinapi/developer.cowin#33]

**Comment by shayuayush** [comment]
Please let us know the solution for this issue. Facing same issue continuously.

**Comment by HandOfGod94** [comment]
sharing curl  request response. might help in looking deeper into the issue
```
curl -vv https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict\?date\=07-05-2021\&district_id\=294
*   Trying 99.86.20.50...
* TCP_NODELAY set
* Connected to cdn-api.co-vin.in (99.86.20.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.co-vin.in
*  start date: Feb 28 00:00:00 2021 GMT
*  expire date: Mar 29 23:59:59 2022 GMT
*  subjectAltName: host "cdn-api.co-vin.in" matched cert's "*.co-vin.in"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f893680f600)
> GET /api/v2/appointment/sessions/public/calendarByDistrict?date=07-05-2021&district_id=294 HTTP/2
> Host: cdn-api.co-vin.in
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 403
< server: CloudFront
< date: Thu, 06 May 2021 09:35:21 GMT
< content-type: text/html
< content-length: 919
< x-cache: Error from cloudfront
< via: 1.1 ee4b0f825dda492e2b7ef534f4322523.cloudfront.net (CloudFront)
< x-amz-cf-pop: BLR50-C2
< x-amz-cf-id: w3My1W5IA1TdQ6beRVptqNijYRyiPlLg5IBTwMCKFgK79Kp1GL2QWw==
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: w3My1W5IA1TdQ6beRVptqNijYRyiPlLg5IBTwMCKFgK79Kp1GL2QWw==
</PRE>
<ADDRESS>
</ADDRESS>
* Connection #0 to host cdn-api.co-vin.in left intact
</BODY></HTML>* Closing connection 0
```

**Comment by Akki1308** [comment]
> sharing curl request response. might help in looking deeper into the issue
> 
> ```
> curl -vv https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict\?date\=07-05-2021\&district_id\=294
> *   Trying 99.86.20.50...
> * TCP_NODELAY set
> * Connected to cdn-api.co-vin.in (99.86.20.50) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/cert.pem
>   CApath: none
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: CN=*.co-vin.in
> *  start date: Feb 28 00:00:00 2021 GMT
> *  expire date: Mar 29 23:59:59 2022 GMT
> *  subjectAltName: host "cdn-api.co-vin.in" matched cert's "*.co-vin.in"
> *  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
> *  SSL certificate verify ok.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x7f893680f600)
> > GET /api/v2/appointment/sessions/public/calendarByDistrict?date=07-05-2021&district_id=294 HTTP/2
> > Host: cdn-api.co-vin.in
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> * Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
> < HTTP/2 403
> < server: CloudFront
> < date: Thu, 06 May 2021 09:35:21 GMT
> < content-type: text/html
> < content-length: 919
> < x-cache: Error from cloudfront
> < via: 1.1 ee4b0f825dda492e2b7ef534f4322523.cloudfront.net (CloudFront)
> < x-amz-cf-pop: BLR50-C2
> < x-amz-cf-id: w3My1W5IA1TdQ6beRVptqNijYRyiPlLg5IBTwMCKFgK79Kp1GL2QWw==
> <
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
> <TITLE>ERROR: The request could not be satisfied</TITLE>
> </HEAD><BODY>
> <H1>403 ERROR</H1>
> <H2>The request could not be satisfied.</H2>
> <HR noshade size="1px">
> Request blocked.
> We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
> <BR clear="all">
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> <BR clear="all">
> <HR noshade size="1px">
> <PRE>
> Generated by cloudfront (CloudFront)
> Request ID: w3My1W5IA1TdQ6beRVptqNijYRyiPlLg5IBTwMCKFgK79Kp1GL2QWw==
> </PRE>
> <ADDRESS>
> </ADDRESS>
> * Connection #0 to host cdn-api.co-vin.in left intact
> </BODY></HTML>* Closing connection 0
> ```

Add this header 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36' to your request and make the requests from within Indian IP, it worked for me locally

**Comment by Akki1308** [comment]
> Please let us know the solution for this issue. Facing same issue continuously.

Add this header to your requests 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
and make the request using India IP

**Comment by HandOfGod94** [comment]
yup @Akki1308 it  worked. Thanks

This is working for me.
```
curl -vv 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=294&date=06-05-2021' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8'
```

**Comment by siddheshkubal14** [comment]
@Akki1308 This works on postman and on localhost, but the same error when I deploy and run from heroku. The region options I have there are just the US and Europe. Any suggestions?
