### ISSUE TITLE
How long is the session really?

### ISSUE THREAD

**Issue by theGeekyLad** [cowinapi/developer.cowin#332]
I'm talking about the **CoWIN portal** website and not any scripts that interface with CoWIN APIs.

I understand that life of an authenticated sessions were around 15m before. Is the same even now? Refreshing the page after nearabout 5m erroneously says, _"Something went wrong! Please try again later."_ 

Is anyone else facing the same? Do I need to re-login with OTP every 5m now?

**Comment by Dipchandan-kalita** [comment]
I am also facing the same issue. Even if I try to log in after the error, I get another error in the login screen that a new OTP can be sent only after 180 seconds of the last OTP. I waited more than 5 mins, also tried clearing the cache, but I still get the same error. I am unable to log in as the OTP is not generated.

**Comment by theGeekyLad** [comment]
Request the @cowinapi team's intervention here.

**Comment by TheScriptingVajra** [comment]
This is because now they have restricted call or click per minute from IP.  If doing so many clicks, it happens. When that error comes, just change IP or switch to different connection. It works and session is not logged out. Bad days for bots!

**Comment by theGeekyLad** [comment]
Indeed, a prudent measure to keep bots at bay, but, it exacerbates UX. I've heard of colleagues that have spent over 3h before the screen trying to bag a slot. Qualifying the "clicks/IP/min" is a harbinger of bad days for _"human"_ users as well.

**Comment by TheScriptingVajra** [comment]
Yup, true. My Chrome extension started throwing this error since last two days. adding delay is useless when slots get booked within a second. Need to keep checking 2-3 times in a second. I am planning to switch IP every 2 minutes, refresh a page, keep looking for a slot.

**Comment by theGeekyLad** [comment]
Alright so, after a bunch of shots in the dark, I've come to realise that the there's no such definite number of clicks that blocks me out. It's affected by randomness: sometimes 31 tries and at other times even 64 ranging from a minute to even more than 8.

For posterity, automated solutions _could_ work they way around with @gbnavapara 's suggestion while _human_ users would just have to brook with this, unfortunately. 

Closing this issue as we now have clarity.
