### ISSUE TITLE
Getting API status_code as 200 but not getting any data (session array is empty)

### ISSUE THREAD

**Issue by rahulwaghmare14** [cowinapi/developer.cowin#342]
I am using cowin public api to find slot by district. Initially it is working fine but after some time api returning status code 200 but there is no data in seesion array.

**Comment by Shrenik27** [comment]
Same was happening to me. How did you resolve?

**Comment by rahulwaghmare14** [comment]
Actually there is no problem with the API in my case. I am getting 200 response code but no data the reason behind this is the data of that particular date is not uploaded by the centers. To verify this just copy the API url and paste it in the browser and see if you are getting any data.
