### ISSUE TITLE
Cowin api access request using python is giving error code 401

### ISSUE THREAD

**Issue by pooja2323** [cowinapi/developer.cowin#346]
when trying to access the following api : "https://cdn-api.co-vin.in/api/v2/admin/location/states" using a python code, it is giving following error message:

equests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cdn-api.co-vin.in/api/v2/admin/location/states

**Comment by avinashbarik91** [comment]
You might have crossed the threshold limit of 100 requests per 5 minutes.

**Comment by siddhesh1770** [comment]
> when trying to access the following api : "https://cdn-api.co-vin.in/api/v2/admin/location/states" using a python code, it is giving following error message:
> 
> equests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cdn-api.co-vin.in/api/v2/admin/location/states

Use this user agent in headers 

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**Comment by pooja2323** [comment]
Thanks! using the header worked.
