### ISSUE TITLE
Got vaccinated second dose but certificate not generated

### ISSUE THREAD

**Issue by Venky1957** [cowinapi/developer.cowin#349]
My name is Babu Venkatesan aged 64 yrs/male. My reference id for vaccination is : 31541376960190. I had my first dose of Covishield on 03 Apr 2021 at Medway Hospitals. At that time my second dose was on 28 Apr 2021 which was subsequently changed to 15 May 2021. Accordingly I had scheduled my appointment through CoWin on 15 May 2021 at Coronation centre, Kumbakonam 612001 for Covishield between 09:00 to 11:00 AM. I was vaccinated my second dose after handing over the copy of my Copy of Aadhar card (my mobile number endorsed) and Appointment details. I was told after two days I will get my certificate link through SMS.

2.    After three days when I checked up with the centre, I was told the server has been updated and time gap between the doses for Covishield has been increased to 84 to 112 days. With this although I had completed my vaccine schedule I am not getting vaccination completion certificate.

3.   After vaccinating second dose I had booked my tickets to visit my son staying abroad on 22 Jun 2021 from Chennai.

4.     I, therefore request you to issue Covid vaccine certificate to enable me to travel abroad. An early action is requested.

**Comment by anantmi3** [comment]
Try to download your certificate from digilocker app https://play.google.com/store/apps/details?id=com.digilocker.android   use the same phone number used while vaccination.

**Comment by Venky1957** [comment]
The vaccinator could not update my records as the server increased the
second dose period.

**Comment by Venky1957** [comment]
Issues resolved
