### ISSUE TITLE
How to set alert message/email if free slot available  

### ISSUE THREAD

**Issue by arunattukal** [cowinapi/developer.cowin#35]
We have successfully integrated the API, but the notification is not working. If any one knows kindly explain the logic 'how can we do the same'.

**Comment by snehil** [comment]
how did you get the API to work on GET requests? I am seeing HTTP 403

**Comment by arunattukal** [comment]
use this header you will get the response 
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

**Comment by DeepakUdherani** [comment]
@arunattukal 
How you have coded, I mean you have written a Java code or something else?

**Comment by arunattukal** [comment]
we have written C++ (.net MVC)

**Comment by siddhesh1770** [comment]
> We have successfully integrated the API, but the notification is not working. If any one knows kindly explain the logic 'how can we do the same'.

use smtplib in python 
refer to [https://www.tutorialspoint.com/python/python_sending_email.htm](url)
