### ISSUE TITLE
New guidelines for protected API usage - Update apisetu website with these guidelines. 

### ISSUE THREAD

**Issue by anantmi3** [cowinapi/developer.cowin#350]
Read the post here 

https://twitter.com/MoHFW_INDIA/status/1397456229237084160?s=20

https://github.com/cowinapi/developer.cowin/issues/333

Finally a stop on unauthorized access to the protected API. Thank you CoWIN team for hearing us out.

**Comment by Shrenik27** [comment]
But we have to register ourselves for using Public APIs too!!

**Comment by anantmi3** [comment]
public api works fine with just the user agent in the headers.
