### ISSUE TITLE
OTP not able to validate

### ISSUE THREAD

**Issue by vaibhavsingh0208** [cowinapi/developer.cowin#36]
When I am trying to validate the OTP while logging in the API docs are giving a very long string here in swagger but I am getting six-digit OTP on mobile. Is there any kind of encoding done here?

please help!

**Comment by heavell7870** [comment]
please encode OTP using SHA-256 and then send it to the server

`import { sha256 } from 'react-native-sha256';`

`sha256(otp).then(hash => {
     console.log(hash)
})`

**Comment by vaibhavsingh0208** [comment]
Thx heavell7870

**Comment by heavell7870** [comment]
@vaibhavsingh0208 welcome buddy
