### ISSUE TITLE
APIs returning calendar results not showing latest results. 

### ISSUE THREAD

**Issue by saikrishnaa97** [cowinapi/developer.cowin#364]
APIs that return calendar results are not returning the latest results. Even after the doses are all booked in a particular centre (shown by the findBy* apis), the calendar APIs sill show that there are some slots left.

**Comment by safiyat** [comment]
To quote from the [website](https://apisetu.gov.in/public/api/cowin):

> The appointment availability data is cached and may be upto 30 minutes old.

<img width="1214" alt="Screenshot 2021-05-30 at 1 42 45 PM" src="https://user-images.githubusercontent.com/833219/120097224-f52d6400-c14c-11eb-8bbc-c61c2501be52.png">


You will get stale data from the public APIs. Switch to private APIs if you can, and it should work better.

**Comment by theGeekyLad** [comment]
Request the OP to kindly skim through the other issues (like [this](https://github.com/cowinapi/developer.cowin/issues/40)) before spawning a new one. Kindly close this.

**Comment by saikrishnaa97** [comment]
Duplicate of https://github.com/cowinapi/developer.cowin/issues/40.
