### ISSUE TITLE
Add a captcha to reduce abuse by bots

### ISSUE THREAD

**Issue by akhilesh-godi** [cowinapi/developer.cowin#37]
I can easily demonstrate end to end automation until the process of booking even with OTP. This disadvantages people and doesn't make vaccine availability equitable. Rate limiting or just adding user-agent check (at CDN) wouldn't suffice. It is easy to bypass this by running automation on multiple instances or spoofing user-agent

Please add a captcha in addition to your (protected even if not public) APIs and also do a shallow check/deep check of the JWT tokens to make sure abuse by bots is reduced for public APIs.

**Comment by akhilesh-godi** [comment]
cc: @cowinapi

**Comment by gaurav281296** [comment]
@akhilesh-godi While your intent is good but don't you think that will make the product (the portal) more difficult to use for millions of people who are not used to solving them. And if the captcha is too simple then it can be easily decoded using bots thereby doing more harm than good.

how about just reducing the ttl of the auth token post OTP authentication to make the bots less effective?

**Comment by akhilesh-godi** [comment]
@gaurav281296 while I understand that captchas are hostile to users, the situation until yesterday made it unusable for almost everyone (no point in having a portal when there are no slots) - hence the suggestion was a stop-gap. I also understand that if the captchas are weak they can be broken with OCR.

Reducing expiry on auth tokens is probably not the best idea. This would mean real users who are on the website too would end up getting logged out often. Currently expiry on JWT token is 15 mins, I would argue that it would make it worse for users if expiry is reduced. Plus, any expiry used here won't stop bots - rate limits can't be employed here because a real user could also be displaying same behaviour.

I can see that a slew of alternative measures were taken last night - including 'referrer' and 'origin' checks, setting cache TTL based on the above. But like all - these are stop-gaps, and can be bypassed.

**Comment by backtrackbaba** [comment]
@akhilesh-godi are these referrer and origin checks implemented?

**Comment by theGeekyLad** [comment]
@akhilesh-godi while reducing the TTL could impact both users and bots alike, aren't the prospects bleak to keep bots at bay especially with some advanced web automation frameworks?

**Comment by akhilesh-godi** [comment]
@theGeekyLad captcha was only a temporary measure suggested until more complex bot detection techniques can be employed. I see several other ways to do this have already been outlined in #11 

However the root cause of all this is the dearth of supply and high demand - unless this is fixed either at the ground level or a better vaccination policy is in place - the devs will have to continue employing such measures.

I also think this issue can now be closed as they have implemented captcha now.

cc: @sudhir-trigyn @satishchandra-pandey
