### ISSUE TITLE
Unauthenticated access! while getting the Request URL: https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries

### ISSUE THREAD

**Issue by Raghava525** [cowinapi/developer.cowin#374]
Hi, Can you please share the process or putting the headers token and what are the options required to get the beneficiaries after successfully getting the auth token. Please show an example headers

**Comment by arunim2405** [comment]
Hi, can you explain the solution? @Raghava525

**Comment by Raghava525** [comment]
Hi @arunim2405  

$.ajax({
	  type: "GET",
	  url: 'https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries',
	  "async": true,
	  "crossDomain": true,
	  "headers": {
		"Authorization": "Bearer "+authentication_obj.token,
		"Accept" : "application/json, text/plain, */*",
		"Content-Type" : "application/json"
	  },
	  dataType: 'json',
	  contentType: 'application/json; charset=utf-8',
	  success: function(res){}
});

I have tried to get beneficiaries list by using open API authtoken. Its not correct. Later I have used token which are generated by using Protected API. So that I got result and I have closed this issue.

**Comment by ganeshksp** [comment]
Hi @Raghava525 i have searched entire forum, looks like only u had success in generating & validating otp and getting beneficiaries from protected apis. I am not able to succesfully talk to protected apis (all of generate otp, confirm otp and getting beneficiaries) when ever i try to communicate with protected apis, i get below error.

Access to XMLHttpRequest at 'https://cdndemo-api.co-vin.in/api/v2/auth/generateOTP' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

I tried to get otp and confirm it using public apis(thank god) and then use the same bearer token in auth header to get beneficiaires from both public and protected beneficiary urls. this is not working either. can you explain how u were able to do this ? did u register for protected apis and get any key other than '3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi' ? are you doing some base64 encoding when sending x-api-key to generate and validate otp. I have tried it all.
