### ISSUE TITLE
Rescheduling slot from one vaccine type to another doesn't change vaccine type for beneficiary

### ISSUE THREAD

**Issue by akhilesh-godi** [cowinapi/developer.cowin#38]
Steps to reproduce:
1. Book a slot for a beneficiary for Covishield
2. Reschedule for another center with Covaxin
3. Beneficiary still retains vaccine as 'Covishield' in beneficiary schema.

Please fix reschedule flow to update `vaccine` in beneficiary schema.
This might cause problems to people when they are looking for the second dose and might be administered different vaccines.

**Comment by akhilesh-godi** [comment]
@cowinapi could you please have this checked?

**Comment by akhilesh-godi** [comment]
@satishchandra-pandey fyi ^

**Comment by satishchandra-pandey** [comment]
@akhilesh-godi 
Fix for this is already on the way
