### ISSUE TITLE
Reduce fraud of fake vaccine administration even when vaccine not provided

### ISSUE THREAD

**Issue by akhilesh-godi** [cowinapi/developer.cowin#39]
Demonstrable cases:

1. https://twitter.com/krishmedikonda/status/1389867070498557955?s=20
2. https://twitter.com/shrutinair1/status/1389865949885472769?s=20

Several such cases reported.

Like certificate verification - find a fool proof solution to prevent fraud in administering vaccine.

**Comment by satishchandra-pandey** [comment]
@akhilesh-godi 
This is developer's forum to help out in API integration.
For this issue, you can call on Cowin helpline number or drop an email.

Helpline Number : +91-11-23978046. Toll-Free: 1075. Helpline Email ID: ncov2019@gov.in

**Comment by akhilesh-godi** [comment]
@satishchandra-pandey Of course I understand this is a developer forum and I am suggesting a tech solution to this. There needs to be some form of authentication when vaccine is being administered. Would request you to reopen the issue and consider exploring options.

**Comment by satishchandra-pandey** [comment]
@akhilesh-godi 
There are other security things that will go live in Vaccination Module in few days that will block the fake vaccination.
But the reason to close this is,this is not in regards with the booking api's.

**Comment by akhilesh-godi** [comment]
Understood. Thanks @satishchandra-pandey
