### ISSUE TITLE
What is wrong with coWIN site ? Can't even see captcha code

### ISSUE THREAD

**Issue by ipankajkumar93** [cowinapi/developer.cowin#390]
![Untitled](https://user-images.githubusercontent.com/24999656/120684173-03b4ac00-c4bc-11eb-953b-7e280f2340c3.png)

**Comment by ipankajkumar93** [comment]
Such a piece of **** it is, tried incognito mode still can't see captcha code and yet 900 slots of a hospital got over in less than a second

**Comment by ipankajkumar93** [comment]
and now it is logging me out every single minute

**Comment by Nakul93** [comment]
They have removed captcha authentication and also has decreased requests to 20 per session this means if you keep on hitting the search button for slots after 20th hit it will log you out.
