### ISSUE TITLE
Any updates on implementation of new guidelines ? 

### ISSUE THREAD

**Issue by nonrealjunco** [cowinapi/developer.cowin#392]
Hi,

New guidelines were published on 24th May 2021. But there seems to be **no timeline on submitting requests for an API Key and then receiving them.**  (Although I see changes being made to the API in last 2 days.)

There are many services/developers who are honestly hitting the Public API within the limits.

But many groups/applications still seem to get data before hand. A few minutes make a lot of difference in a populous country like India.

And even if say they are using the Public API only they must be running multiple instance so the 100 req / 5 mins can be easily overridden. 

Once the Public and Private API's have the **same live data** for available centers, you will see less issues and less people complaining about the same. 

Also with an API Key you can restrict the requests per key. So its a fair playing field for all.

**Comment by shivkant1418** [comment]
I totally agree. I changed my telegrams to use public keys. But there are still many groups that are getting data in real-time. I doubt they have protected API implemented.

**Comment by nonrealjunco** [comment]
API's updated and registration available.
