### ISSUE TITLE
No Any APIs are supporting multiple districtId or StateId

### ISSUE THREAD

**Issue by MaverickNyk** [cowinapi/developer.cowin#397]
APIS should accept List of districtIds and list of stateIds,
currently its only accepting a single districtId or stateId

**Expected:** 
/v2/appointment/sessions/public/findByDistrict?districtId=<List of DistrictId>
i.e. /v2/appointment/sessions/public/findByDistrict?districtId = 1,2,3,4,5,6

**Actual:**
/v2/appointment/sessions/public/findByDistrict?districtId=<districtId>
i.e. /v2/appointment/sessions/public/findByDistrict?districtId = 1

**Comment by rahulshinde11** [comment]
You have to loop and query each one

**Comment by MaverickNyk** [comment]
Closing this issue as a limitation.
