### ISSUE TITLE
Appointment availability data caching 

### ISSUE THREAD

**Issue by sasank2102** [cowinapi/developer.cowin#40]
Its mentioned at [https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2](https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2) :

> The appointment availability data is cached and may be upto 30 minutes old.

Does this mean that appointment data from api could be old while it could be updated on cowin.gov.in site ?

**Comment by SehgalNeeraj** [comment]
> Its mentioned at https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2 :
> 
> > The appointment availability data is cached and may be upto 30 minutes old.
> 
> Does this mean that appointment data from api could be old while it could be updated on cowin.gov.in site ?

Yes :(

**Comment by sasank2102** [comment]
@SehgalNeeraj  cowin.gov.in seems to sending GET request to same api address when searching for slots ( could be seen in firefox n/w monitor ). ins't the delay supposed to be same then ?

**Comment by sidgod** [comment]
@sasank2102 That's exactly what I'm concerned about!

**Comment by theGeekyLad** [comment]
> @SehgalNeeraj cowin.gov.in seems to sending GET request to same api address when searching for slots ( could be seen in firefox n/w monitor ). ins't the delay supposed to be same then ?

They're probably relying on server-side CORS to channel requests coming from the `cowin.gov.in` domain and thereby provided un-cached real-time data.

**Comment by lyveng** [comment]
> > @SehgalNeeraj cowin.gov.in seems to sending GET request to same api address when searching for slots ( could be seen in firefox n/w monitor ). ins't the delay supposed to be same then ?
> 
> They're probably relying on server-side CORS to channel requests coming from the `cowin.gov.in` domain and thereby provided un-cached real-time data.

What exactly do you mean by server-side CORS? The request sent from `cowin.gov.in` to `cdn-api.co-vin.in` will just have the Origin header set to `https://selfregistration.cowin.gov.in`. I've tried setting this header when making the availability call. I still get cached data. Although the twitter bot [@BloreVaccine](https://twitter.com/BloreVaccine) seems to be getting real time data. Just not sure how.
