### ISSUE TITLE
I made a website for personalized vaccine alerts, feedback required

### ISSUE THREAD

**Issue by rahulshinde11** [cowinapi/developer.cowin#400]
I made this website that sends free personalized vaccine availability alerts based on centers/hospitals on WhatsApp. Have a look or share it with someone who might need it.
Would love your feedback. 
https://vaccine.india-covid.info/

**Comment by saurajain1005** [comment]
What is the maximum latency I can expect between slot available & whatApp notification?

What donation to make to increase the limit to 30 centres?

**Comment by rahulshinde11** [comment]
Hello, It's 5 min sync for the cities and 30mins for the rural areas.
Received msg is 100% accurate as the messages are sent as soon the data is synced

**Comment by rahulshinde11** [comment]
Quick Hack: You can sign up using multiple numbers to get the alerts. haha
I am happy with any contribution to code or as a donation. I plan to extend the limit for donated people

**Comment by abizerlokhandwala** [comment]
Hey @rahulshinde11 ! Great website you have there :)
A few friends and I have also built a real-time personalized notifications platform through emails, we also give you an option of only subscribing to centers nearby, very relevant for users who cannot travel to far away centers and do not want to be spammed.
URL: https://vaccinepost.co.in/
We have been attempting to enable Whatsapp alerts since sometime, but haven't received Facebook Verification yet. We looked into other methods but they were not scalable and realtime. Would be great if we could talk about your Whatsapp implementation and see if we can do something great!

**Comment by rahulshinde11** [comment]
Hello, Thanks for your message. Great website btw.
About Whatsapp: the implementation is custom. I can provide you an endpoint from my servers to send WhatsApp messages if you are okay with that.

**Comment by rahulshinde11** [comment]
Please join our telegram channel if you have more questions. 
https://telegram.me/joinchat/LeyTBcvHD3gyMmI1

**Comment by sumati927** [comment]
Very well designed interface. 👍

**Comment by rahulshinde11** [comment]
Thank you :)

**Comment by kailashyogeshwar85** [comment]
@rahulshinde11 thats a nice portal. We have also build a similar kind of portal with email notification for now at https://covidend.in

**Comment by rahulshinde11** [comment]
hey @kailashyogeshwar85 I wonder how many of you guys it took to build that?
I admire the effort, 
btw they have 18+ and 45+ in some centers
like ASTER RV HOSPITAL, pin: 560078

**Comment by udayogra** [comment]
Great work done by all fellow developers. I also did my part and have made https://vaccineslot.in almost a month back. Used by more than 2 lacs users. I have managed to give alerts atleast 2-3 seconds before most of the telegram channels.

Things are improving a lot and hopefully users wont use our app in future anymore :)

**Comment by rahulshinde11** [comment]
Interesting to see 2-3 seconds. haha. 
There are a lot of people + children to be vaccinated 
It's not about how fast you give the information. it's about reach and usability. As a user, 2-3 seconds means nothing. unless I'm running a bot.

**Comment by rahulshinde11** [comment]
actually, I would accept 5 seconds delay for not having so many errors in my console 
![image](https://user-images.githubusercontent.com/44699277/121410578-5bea2300-c980-11eb-8f6b-e7fa6a2d0308.png)

**Comment by udayogra** [comment]
LOL. In Bangalore slots get over in 20-30 seconds. Few days back they used to last 10-15 secs.

**Comment by rahulshinde11** [comment]
Currently, I don't see any problems in Bangalore. People are getting enough time to act on my WhatsApp notifications(18+ too). If my app missed it then it's ok. Anyway, a normal user with a phone can't book within seconds.
My target audience is any Indian with WhatsApp.

It would be great if you could give me some examples of where the slots got missed. I can reduce the sync time even further if that's the case.

**Comment by udayogra** [comment]
Not sure who those lucky people from Bangalore are. I tried your app. More than 4 hospitals opened slots in last 1 hour but I did not get any notification. All those slots lasted very long - almost 3-4 minutes. I am talking about 18+. 45+ dont even need any alert service unless looking for Covaxin

![image](https://user-images.githubusercontent.com/2443631/121464986-8ebd0700-c9d2-11eb-80b3-818a82d9748d.png)

**Comment by rahulshinde11** [comment]
Does your website use private/protected api?

Here is an example where the alert was sent just few mins back

*Alert: Vaccine slots available*
Center: APOLLO CRADLE JAYANAGAR
Date: 10-06-2021
Address: No.25 46th Cross 5TH BLOCK JAYANAGAR Bangalore, South, BBMP, 560011
 
*Detailed Information*
Total Available: 44
Type: Paid(₹780)
Dose 1: 44
Dose 2: 0
Minimum Age: 18
Vaccine: COVISHIELD


To manage your alerts visit https://vaccine.india-covid.info

There are 100s of these are being sent out throughout India every minute

**Comment by udayogra** [comment]
At what time was it sent? I did not receive
Public APIs

And there were 200 slots. You are fetching cached data. By the time API would have returned 44 slots, all slots would have actually vanished

**Comment by zebkailash** [comment]
> hey @kailashyogeshwar85 I wonder how many of you guys it took to build that?
> I admire the effort,
> btw they have 18+ and 45+ in some centers
> like ASTER RV HOSPITAL, pin: 560078

We need to fix this. Thanks for the feedback.

**Comment by rahulshinde11** [comment]
> At what time was it sent? I did not receive
> 
> Public APIs
> 
> 
> 
> And there were 200 slots. You are fetching cached data. By the time API would have returned 44 slots, all slots would have actually vanished

10:40 am

**Comment by udayogra** [comment]
> > At what time was it sent? I did not receive
> > Public APIs
> > And there were 200 slots. You are fetching cached data. By the time API would have returned 44 slots, all slots would have actually vanished
> 
> 10:40 am

Slots got finished by 9:40 AM

**Comment by udayogra** [comment]
Just checked again. Slots for Apollo cradle got finished by 10:38 AM. Which API are you using?

By the way I still did not get any whatsapp notification.

**Comment by udayogra** [comment]
I missed a point. You need to subscribe to CENTERS and not to DISTRICTS?

**Comment by rahulshinde11** [comment]
Yes. That's a cool thing because people don't want to get spammed by so many messages.

**Comment by rahulshinde11** [comment]
My app is not for someone who is ok to sit in front of a computer staring at it ready to book. I think such people should use your app.
My app is for someone who can know about the nearby centers whats available and where it's not, and plan it for himself and his family. Many people are not using CoWin. They directly go to the hospitals/centers. My app can help those people too.

**Comment by rahulshinde11** [comment]
And I'm giving you here actual stats from the users. Even though I give 5 centers to subscribe. Rarely people cross 3.
They just want to know when it will be available in that center closest to them. I guess they don't want to travel.
