### ISSUE TITLE
Unable to generate OTP

### ISSUE THREAD

**Issue by hemantsingh011** [cowinapi/developer.cowin#407]
![image](https://user-images.githubusercontent.com/13682518/121060765-b2b8f680-c7e0-11eb-93d5-7df4aae9967e.png)

**Comment by dhruv5harma** [comment]
I am getting same error, let me know if you find a solution for this. Although i am getting the otp via cowin public api but not able to validate it.

**Comment by hemantsingh011** [comment]
@dhruv5harma sure, in case you get the answer please also let me know

**Comment by rocky-rancho** [comment]
same issue, still waiting for the resolution

**Comment by hemantsingh011** [comment]
It's working fine now
