### ISSUE TITLE
Slots are always full on cowin when API call shows available slots 

### ISSUE THREAD

**Issue by asimamitavm** [cowinapi/developer.cowin#412]
I have been tracing vaccine slots for last one month  using API call. But I have never got an available slot on cowin corresponding to the API call results. Am I doing something wrongly or missing something here..

**Comment by capt2101akash** [comment]
Which API are you using?

**Comment by udayogra** [comment]
Because Cowin caches each API call for 5 mins.  There is a small technical way of bypassing it.

**Comment by amitexm** [comment]
> Because Cowin caches each API call for 5 mins. There is a small technical way of bypassing it.

Can you please eleborate a little on small way of doing that?
Please ping me here...
rishabh49@ichigo.me

**Comment by badinenisaivardhan** [comment]
hey @amitexm , Try changing the date format and year, 
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=610&date=08-06-2021
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=610&date=8-06-2021
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=610&date=8-6-2021
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=610&date=8-06-21
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=610&date=8-6-21
here each request is treated as individual request so you will be getting real-time data , not a cache data , and also check the response header date and remapped-date of each request ...!!
Hope i made you clear ..!

**Comment by asimamitavm** [comment]
Thanks @badinenisaivardhan . I understand the api call results being cached  in cowin, but my problem is even the first call results of the day is not  reflecting on the portal.. I always see all the the slots booked when I login to portal for each day. Any idea ?

**Comment by badinenisaivardhan** [comment]
hey @asimamitavm , you need to understand that the medical hospitals play a major role in updating the data such as stock of vaccine's , doses , age limits , and slots..., and also keep in mind it differs from hospital to hospital..., and also the quantity of the vaccine also plays major part..... so all this factor's make the slot are booked every time,  so we need Waite till the dose update.... or try information from the local hospital crew (offline).. 
**Note: all the info here are my personal view .., it may be wrong or it may be right**

**Comment by asimamitavm** [comment]
Yes @badinenisaivardhan . That's true. I am aware that lot of depends on that data from hospitals. Thanks.

**Comment by udayogra** [comment]
> > Because Cowin caches each API call for 5 mins. There is a small technical way of bypassing it.
> 
> Can you please eleborate a little on small way of doing that?
> Please ping me here...
> [rishabh49@ichigo.me](mailto:rishabh49@ichigo.me)

Cowin will pass today's date as 11-06-2021. You can pass 11-6-21,11-06-2021,11-06-21,11/6/21,11/06/2021,11/06/21
You can replace 11 with past dates like 10,9,7 etc. Remember calendarByPincode will return 1 week's data.
You can also add spaces like 11 -06-2021,11  -06-2021,11   -06-2021,11    -06-2021 and so on
You can also add another query parameter like vaccine=COVISHIELD

All these unique parameters will make Cowin's cache layer treat your request as a new request unless someone has already used the combination and you will get latest data
By the way Cowin has reduced cache period from 5 mins to 1 min. So all this might not be even required

**Comment by udayogra** [comment]
> Thanks @badinenisaivardhan . I understand the api call results being cached in cowin, but my problem is even the first call results of the day is not reflecting on the portal.. I always see all the the slots booked when I login to portal for each day. Any idea ?

Its not a cache per IP. Your first request(pincode + date), someone else would have already made, that is why you would see cached data. In order to make your request unique and fetch latest data you need to tweak the date format. This you can do even when you are logged in into cowin portal, by putting debug point in their JS code and changing the date format being passed
