### ISSUE TITLE
Vaccinator API mocking

### ISSUE THREAD

**Issue by krsharath** [cowinapi/developer.cowin#413]
1.  POST API  /v2/vaccinator/onspots/schedule 
The body needs a session-id.  
How can I mock session-id here?

Without this, I get invalid slot ID error
{"errorCode":"APPOIN0015", "error":"Invalid Slot Id"}

2. ​POST /v2​/vaccinator​/beneficiaries​/vaccinate
The body needs center_id and vaccine_batch
How can I mock these values?

Without this, I get below error
{ "errorCode": "GERR001", "error": "Something Went wrong!" }

**Comment by jigarjain709** [comment]
Hey 
I am facing a similar issue as your point 1 my error is 
_For POST API_ /v2/vaccinator/onspots/schedule
{"errorCode":"APPOIN0047", "error":"Name of individual is required!"}

_For  POST_ /v2​/vaccinator​/beneficiaries​/vaccinate
{ "errorCode": "GERR001", "error": "Something Went wrong!" }
 
@cowinapi Do we have a list of error codes and their meaning?

@krsharath, 1 . You can get the session id from https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=395&date=10-06-2021.
