### ISSUE TITLE
How to generate secret for generateMobileOTP public API?

### ISSUE THREAD

**Issue by amaltb** [cowinapi/developer.cowin#414]

**Comment by big89** [comment]
On https://apisetu.gov.in/public/api/cowin API portal, Public APIs are open for all, Protected APIs are not open without API Key.
This are provided for official use after registration.

Also, API calls inspected from https://selfregistration.cowin.gov.in/ portal are different and unofficial.

@amaltb generateMobileOTP is neither public nor protected API. It seems the inspected API call from Co-WIN portal.

**Comment by ganeshksp** [comment]
Hey @big89 , you are right. 
Using below public urls
https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP
https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP
I am able to generate and verify otp with out any problem.

But when i try to use sandbox urls, 
https://cdndemo-api.co-vin.in/api/v2/auth/generateOTP
https://cdndemo-api.co-vin.in/api/v2/auth/confirmOTP
I am not able to neither generate otp nor confirm. However, i tried a small modification of the sandbox url (adding /public)
https://cdndemo-api.co-vin.in/api/v2/public/auth/generateOTP
https://cdndemo-api.co-vin.in/api/v2/public/auth/confirmOTP
Then i am only able to generate otp and not verify it. Very confusing.

**Comment by amaltb** [comment]
Hey @big89 , Thanks for pointing it out. I got this the generateMobileOTP from cowin portal inspection, Hence thought of checking if someone has got hold of the algo generating the random secret. Previously I tried the generateOTP public endpoint from my ISP and it was throwing 429 (Probably my local ISP distributing the same IP for many connections over NAT). After your comment, I tried generateOTP API once again using my mobile network and it worked.

**Comment by amaltb** [comment]
> Hey @big89 , you are right.
> Using below public urls
> https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP
> https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP
> I am able to generate and verify otp with out any problem.
> 
> But when i try to use sandbox urls,
> https://cdndemo-api.co-vin.in/api/v2/auth/generateOTP
> https://cdndemo-api.co-vin.in/api/v2/auth/confirmOTP
> I am not able to neither generate otp nor confirm. However, i tried a small modification of the sandbox url (adding /public)
> https://cdndemo-api.co-vin.in/api/v2/public/auth/generateOTP
> https://cdndemo-api.co-vin.in/api/v2/public/auth/confirmOTP
> Then i am only able to generate otp and not verify it. Very confusing.

What error are you getting? I think you might be missing the x-api-key header in you request. I tried the sandbox ones and it was working as expected.

**Comment by ganeshksp** [comment]
@amaltb  what  headers did u set for sandbox requests ?

**Comment by amaltb** [comment]
@ganeshksp These are the ones I used. API key is provided on the api setu cowin portal. 

`Content-Type:application/json
x-api-key:3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi`

**Comment by ganeshksp** [comment]
@amaltb  so only adding this key worked for getting beneficiaries as well ???

**Comment by ganeshksp** [comment]
for me whenever i use x-api-key, i am getting below error 
Access to XMLHttpRequest at 'https://cdndemo-api.co-vin.in/api/v2/auth/public/confirmOTP' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field x-api-key is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by amaltb** [comment]
> @amaltb so only adding this key worked for getting beneficiaries as well ???

For beneficiaries You need the bearer token I guess. You will get the token in the confirmOTP response.

**Comment by amaltb** [comment]
> for me whenever i use x-api-key, i am getting below error
> Access to XMLHttpRequest at 'https://cdndemo-api.co-vin.in/api/v2/auth/public/confirmOTP' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field x-api-key is not allowed by Access-Control-Allow-Headers in preflight response.

Can you try with the sandbox endpoint mentioned on the site. You can verify this from postman or any other rest client as well. If you are trying from a local site, there could be other headers or params that you need to enable (for cross site scripting and all) which I am not very sure of.
