### ISSUE TITLE
Account blocked for exceeding search limit

### ISSUE THREAD

**Issue by BhagyashreeAher** [cowinapi/developer.cowin#415]
Hi Team,

I am trying book slot from yesterday first got message  "Generate OTP failed"  and today got new message 
"my account is blocked for exceeding search limit"
Any help how can i unlock the account?

**Comment by SatheMangesh** [comment]
Hi Team,

I am also getting same message, I am due for second dose of covaxin and I have 2 other family members added to the account. 

Yesterday after 4 PM : USRAUT0018 otp failure
Today evening 8 PM :  USRAUT0030 limit exceeded and try after sometime
An hour back : {"errorCode":"USRAUT0030", "error":"Your account is blocked for exceeding our search limit, please read our terms of service."} 

Is account permanently blocked? should we register new number and get dose2 by registering for dose1

**Comment by vishalsuriasm** [comment]
Hii Team 

same above issue is being faced by me also please help our vaccine 2nd dose is due

**Comment by awanishprasad007** [comment]
Hi Team, pls let us know how to get the account unblocked.

**Comment by manalshaikh** [comment]
> Hi Team, pls let us know how to get the account unblocked.

This wouldn't be the best practice, but I'd suggest you use a proxy. Use it only if the OTP error that was generated is likely to be false-positive. This is because if you even try with proxy, it will probably block it too. Maybe something's off with your script. Are you looping the calls?

**Comment by awanishprasad007** [comment]
Thanks for replying!

I am not using any script or bot.
But I was trying to manually search multiple times, that someone has to do
otherwise slots get full in max 2 sec.

And after few searches, its logges out so obviously have to relogin as fast
as possible.

Not sure when this problem would be resolved.

Pls help if possible.

Thanks,
Awanish

**Comment by mohit-soral** [comment]
> Hi Team,
> 
> I am also getting same message, I am due for second dose of covaxin and I have 2 other family members added to the account.
> 
> Yesterday after 4 PM : USRAUT0018 otp failure
> Today evening 8 PM : USRAUT0030 limit exceeded and try after sometime
> An hour back : {"errorCode":"USRAUT0030", "error":"Your account is blocked for exceeding our search limit, please read our terms of service."}
> 
> Is account permanently blocked? should we register new number and get dose2 by registering for dose1

Facing same issue. The 2nd dose for both my wife and I are pending, and we were registered as beneficiaries under this number which is shown as blocked now !
If I register using another mobile number, then it does not show that 1st dose is done and 2nd one is pending.
