### ISSUE TITLE
Forbidden error on php curl public api get request , please help

### ISSUE THREAD

**Issue by shababps** [cowinapi/developer.cowin#417]
$curl = curl_init();

             curl_setopt_array($curl, array(
               
              CURLOPT_SSL_VERIFYHOST=>0,
              CURLOPT_SSL_VERIFYPEER =>0,
              CURLOPT_URL => "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=683580&date=09-06-2021",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_ENCODING => "",
              CURLOPT_MAXREDIRS => 10,
              CURLOPT_TIMEOUT => 0,
              CURLOPT_FOLLOWLOCATION => false,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "GET",
              CURLOPT_HTTPHEADER => array(
                  "Authorization: Basic c3VyYWowNzA4MTk5NTp4a2V5c2liLWUyNDI3MzA4NjcyOWFlMTg5MzkyOGExNmI5MDU1NGI5MTAxMDliZmJmNjJjNzQyOWY5ZjQyNzZhZmJjZmQwNjgtc2Y0M3ZhU25Ga1Uwd3RkOQ==",
                 "accept: application/json",
                "Accept-Language: en_US",
                 "User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
                 
              ),
            ));

             $response = curl_exec($curl);
             $err = curl_error($curl);
   if ($err) {
              echo "cURL Error #:" . $err;
            } else {
             curl_close($curl);
              $data_obj=json_decode($response);
              var_dump($response);
              }

**Comment by shababps** [comment]
$curl = curl_init();

             curl_setopt_array($curl, array(
               
              CURLOPT_SSL_VERIFYHOST=>0,
              CURLOPT_SSL_VERIFYPEER =>0,
              CURLOPT_URL => "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=683580&date=09-06-2021",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_ENCODING => "",
              CURLOPT_MAXREDIRS => 10,
              CURLOPT_TIMEOUT => 0,
              CURLOPT_FOLLOWLOCATION => false,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "GET",
              CURLOPT_HTTPHEADER => array(
                  "Authorization: Basic c3VyYWowNzA4MTk5NTp4a2V5c2liLWUyNDI3MzA4NjcyOWFlMTg5MzkyOGExNmI5MDU1NGI5MTAxMDliZmJmNjJjNzQyOWY5ZjQyNzZhZmJjZmQwNjgtc2Y0M3ZhU25Ga1Uwd3RkOQ==",
                 "accept: application/json",
                "Accept-Language: en_US",
                 "User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
                 
              ),
            ));

             $response = curl_exec($curl);
             $err = curl_error($curl);
   if ($err) {
              echo "cURL Error #:" . $err;
            } else {
             curl_close($curl);
              $data_obj=json_decode($response);
              var_dump($response);
              }

**Comment by big89** [comment]
@shababps This is a working code and make sure you are sending request from Indian IP only.

`<?php

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=683580&date=09-06-2021');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Accept-Language: en_US';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;

?>`

Thanks,
Logicmaker

**Comment by manalshaikh** [comment]
Adding to what big89 said, if your "server" isn't from India, I suggest you find a proxy. There are so many Indian proxies. Level 3/Elite proxies are recommended to avoid being marked as spam.

**Comment by rahulshinde11** [comment]
You can set up a VPN on your server and connect it to an Indian server. I suggest you use an Indian server if possible.
