### ISSUE TITLE
Getting Failed to fetch when Trying from OpenApi

### ISSUE THREAD

**Issue by angsdey2** [cowinapi/developer.cowin#42]
When I am trying to execute the "/v2/appointment/sessions/public/findByPin" from OpenApi screen getting Failed to fetch Error.

![image](https://user-images.githubusercontent.com/26900900/117299189-dd3c2a80-ae95-11eb-9cf4-7c6ee8b8a730.png)

**Comment by abhishek1234321** [comment]
Try in Postman? or in the command line using curl?

**Comment by snehil** [comment]
do you have a working example?

**Comment by nidhiakanksh** [comment]
@snehil @angsdey2 I called the api beyond prescribed limits. Waited for the cooldown (if any) to lapse but still unable to work with the api. Is the blacklisting of my IP permanent ? I am getting a similar Failed to Fetch error on the API UI.

**Comment by snehil** [comment]
@nidhiakanksh Not sure why you have tagged me but I am not part of the team that manages this API.. so I am the wrong person to reach out to with your question.. Sorry about that..
