### ISSUE TITLE
Easy to use Multiple Co-win Slot finder on 1 click

### ISSUE THREAD

**Issue by sumati927** [cowinapi/developer.cowin#422]
You can visit the site https://jpsays.com/vaccine

1. **SET MULTIPLE ALERT CRITERIA**
You just need to select your criteria for alerts like district, type of vaccine/dose/date and Set Reminder.

You can set multiple criteria from different districts too.

On 1 click all your searches will be done.

Next time you open the site in same browser, your search criteria will be there already. Just click Check Availability button, all information will be available.

2. **ENABLE NOTIFICATION ( IF SUPPORTED BY DEVICE )**
If your device supports notification like Windows 10 desktop/laptop, then after setting alert criteria, click on Enable Notification button. Allow it.

Minimize the browser or continue with your other work, keep the site open. As and when the slots are available, it will notify in you.

3. **DOWNLOAD CERTIFICATE**
Authenticate your mobile using OTP and download vaccination certificate for unique reference ID provided at the time of booking a slot.

_**Please visit and give your valuable feedback**_

For better experience, API for beneficiaries linked to mobile number is required.
Some users have taken both doses under two different beneficiary IDs. Cowin app should provide some way of merging them into one.

**Comment by ganeshksp** [comment]
Hi Sumati, nice job, If I show u what m working on u wud be shocked to how similar it is. Also, did u have any luck talking to private apis ??? I think lot of people are able to but I am not !!!

**Comment by sumati927** [comment]
> Hi Sumati, nice job, If I show u what m working on u wud be shocked to how similar it is. Also, did u have any luck talking to private apis ??? I think lot of people are able to but I am not !!!

Thanks for sharing your thoughts. No, I didn’t try for private APIs. All the best !!

**Comment by Nakul93** [comment]
@sumati927 great job. Just one question are the alerts real time or would there be a delay?

**Comment by udayogra** [comment]
> Hi Sumati, nice job, If I show u what m working on u wud be shocked to how similar it is. Also, did u have any luck talking to private apis ??? I think lot of people are able to but I am not !!!

Public APIs are giving real time data, so why do we require to talk to private APIs

**Comment by Nakul93** [comment]
> > Hi Sumati, nice job, If I show u what m working on u wud be shocked to how similar it is. Also, did u have any luck talking to private apis ??? I think lot of people are able to but I am not !!!
> 
> Public APIs are giving real time data, so why do we require to talk to private APIs

Not really check the [API doc page](https://apisetu.gov.in/public/api/cowin/cowin-public-v2) it says Public APIs data maybe upto 5mins old

**Comment by rahulshinde11** [comment]
Yes, public API is not the latest. I have verified.

**Comment by udayogra** [comment]
> > > Hi Sumati, nice job, If I show u what m working on u wud be shocked to how similar it is. Also, did u have any luck talking to private apis ??? I think lot of people are able to but I am not !!!
> > 
> > 
> > Public APIs are giving real time data, so why do we require to talk to private APIs
> 
> Not really check the [API doc page](https://apisetu.gov.in/public/api/cowin/cowin-public-v2) it says Public APIs data maybe upto 5mins old

Try findByDistrict...It is real time...CalendarByDistrict has 5 mins cache...Even that can be bypassed

**Comment by Nakul93** [comment]
Not really I’ve tried findby public APIs when slot opens up, but there was a delay of 2-3mins. 
Same with private gave me instant response.
Anyhow the policies for usage of these APIs have been updated not sure how long we will be able to use this

**Comment by udayogra** [comment]
> Not really I’ve tried findby public APIs when slot opens up, but there was a delay of 2-3mins.
> Same with private gave me instant response.
> Anyhow the policies for usage of these APIs have been updated not sure how long we will be able to use this

I run findBy API 24 by 7 and always get fresh data. CalendarBy can also give by tweaking the date being passed

**Comment by Nakul93** [comment]
And do you use public APIs?

**Comment by udayogra** [comment]
> And do you use public APIs?

Yes. Even telegram updater channels are using public APIs only

**Comment by udayogra** [comment]
You can always check response headers to check how much your data is cached/old. DATE and remapped-date needs to be equal for latest data
![image](https://user-images.githubusercontent.com/2443631/121497356-fbe39300-c9f8-11eb-9db0-dde57a5275d2.png)

**Comment by Nakul93** [comment]
But it does have a limit of 100 searches per IP for 5mins.

**Comment by udayogra** [comment]
> But it does have a limit of 100 searches per IP for 5mins.

Yes it is. I run one request every 3.5 seconds per user. And each user acts as a new public IP for me. So literally I get latest data every second

**Comment by Nakul93** [comment]
When you say per user are you actually logging in and searching for slots or without it?

**Comment by udayogra** [comment]
Not logged in. I run API calls on browser. So if X number of users are using my app, each of them(actually 10%) will be making calls from different IP addresses to COWIN APIs after every 3.5 seconds. Whosoever finds slot first will communicate to others via backend

**Comment by Nakul93** [comment]
Nice.
Is this the app you are using: https://jpsays.com/vaccine

**Comment by rahulshinde11** [comment]
How can you bypass CORS and make a request to another domain?

**Comment by rahulshinde11** [comment]
It's this one. https://vaccineslot.in/ I see lot of script errors
![image](https://user-images.githubusercontent.com/44699277/121503424-b0cc7e80-c9fe-11eb-8d4a-0bdb1141466a.png)

**Comment by udayogra** [comment]
All harmless errors

**Comment by udayogra** [comment]
> How can you bypass CORS and make a request to another domain?

Even you can do that. They allow cross domain calls

**Comment by sumati927** [comment]
> @sumati927 great job. Just one question are the alerts real time or would there be a delay?

Thank you for supporting.
There is 5 mins delay in public API, as given in description. But practically I have seen delay of 2-3 mins only.

And our page refreshes after every 60 seconds for all the set alerts.
