### ISSUE TITLE
unable to get the response from the following api (/v2/appointment/schedule) in protected api

### ISSUE THREAD

**Issue by sravani7774** [cowinapi/developer.cowin#423]
Request URL : https://cdndemo-api.co-vin.in/api/v2/appointment/schedule

Request we are passing
{
    "dose": "1",
    "session_id": "ef8a78fa-adc0-4397-b278-85ce60da3367",
    "slot": "FORENOON",
    "beneficiaries": [
        "48448366834980"
    ]
}

Even though we change the slot the response is always the following
{"errorCode":"APPOIN0015", "error":"Invalid Slot Id"}

Please help us with the issue as soon as possible

Thankyou.

**Comment by badinenisaivardhan** [comment]
Hey @sravani7774  , The issue is with the slot, Initial the slot array used to get forenoon,afternoon but bow the slot array is with the time slot array with time,pass the index value of slot as the value, and also check the session_id as it is in realtime..
