### ISSUE TITLE
Protected APIs not returning any slots for beneficiary 

### ISSUE THREAD

**Issue by chhabraharsh** [cowinapi/developer.cowin#424]
Protected APIs always returning [] array for the logged-in beneficiary on protected APIS.
Anyone one any idea, why it is happening?

**Comment by badinenisaivardhan** [comment]
Hey @chhabraharsh  , Have You Added The Beneficiary In The The Website ??

**Comment by chhabraharsh** [comment]
@badinenisaivardhan Yeh, we authenticated the beneficiary using OTP through protected APIS. Yes, we have added a beneficiary to the sandbox data. when we are hitting calenderByDistric or Pincode it is just returning an empty response.

**Comment by badinenisaivardhan** [comment]
Hey @chhabraharsh , yes the sandbox is given centers as an empty array, as there may be no test centers for general code areas

**Comment by chhabraharsh** [comment]
@badinenisaivardhan 
Do you know any Pincode or district ID for which it might return a non-empty array?
In fact, CalenderByDistrict is not working on the sandbox. It is throwing an error.

**Comment by badinenisaivardhan** [comment]
@chhabraharsh  Working On it , Found Some Extra State Id Have been added to the https://cdndemo-api.co-vin.in/

got the response of states end point , may be this are the test states what we are looking for 

{
  "states": [
    {
      "state_id": 1,
      "state_name": "Andaman and Nicobar Islands"
    },
    {
      "state_id": 2,
      "state_name": "Andhra Pradesh"
    },
    {
      "state_id": 3,
      "state_name": "Arunachal Pradesh"
    },
    {
      "state_id": 4,
      "state_name": "Assam"
    },
    {
      "state_id": 5,
      "state_name": "Bihar"
    },
    {
      "state_id": 6,
      "state_name": "Chandigarh"
    },
    {
      "state_id": 7,
      "state_name": "Chhattisgarh"
    },
    {
      "state_id": 8,
      "state_name": "Dadar and Nagar Haveli"
    },
    {
      "state_id": 54,
      "state_name": "Dadra and Nagar Haveli"
    },
    {
      "state_id": 37,
      "state_name": "Daman and Diu"
    },
    {
      "state_id": 9,
      "state_name": "Delhi"
    },
    {
      "state_id": 80,
      "state_name": "Demo"
    },
    {
      "state_id": 83,
      "state_name": "Demo State"
    },
    {
      "state_id": 82,
      "state_name": "DhState1"
    },
    {
      "state_id": 90,
      "state_name": "DNM State"
    },
    {
      "state_id": 10,
      "state_name": "Goa"
    },
    {
      "state_id": 11,
      "state_name": "Gujarat"
    },
    {
      "state_id": 12,
      "state_name": "Haryana II"
    },
    {
      "state_id": 13,
      "state_name": "Himachal Pradesh"
    },
    {
      "state_id": 14,
      "state_name": "Jammu and Kashmir"
    },
    {
      "state_id": 15,
      "state_name": "Jharkhand"
    },
    {
      "state_id": 16,
      "state_name": "Karnataka"
    },
    {
      "state_id": 17,
      "state_name": "Kerala"
    },
    {
      "state_id": 88,
      "state_name": "KeralaNew"
    },
    {
      "state_id": 98,
      "state_name": "KL New"
    },
    {
      "state_id": 18,
      "state_name": "Ladakh"
    },
    {
      "state_id": 19,
      "state_name": "Lakshadweep"
    },
    {
      "state_id": 107,
      "state_name": "Lucknow"
    },
    {
      "state_id": 20,
      "state_name": "Madhya Pradesh"
    },
    {
      "state_id": 21,
      "state_name": "Maharashtra"
    },
    {
      "state_id": 91,
      "state_name": "Maharashtra1"
    },
    {
      "state_id": 22,
      "state_name": "Manipur"
    },
    {
      "state_id": 23,
      "state_name": "Meghalaya"
    },
    {
      "state_id": 24,
      "state_name": "Mizoram"
    },
    {
      "state_id": 25,
      "state_name": "Nagaland"
    },
    {
      "state_id": 105,
      "state_name": "New State"
    },
    {
      "state_id": 89,
      "state_name": "newstate"
    },
    {
      "state_id": 26,
      "state_name": "Odisha"
    },
    {
      "state_id": 27,
      "state_name": "Puducherry"
    },
    {
      "state_id": 28,
      "state_name": "Punjab"
    },
    {
      "state_id": 29,
      "state_name": "Rajasthan"
    },
    {
      "state_id": 103,
      "state_name": "sample state1"
    },
    {
      "state_id": 104,
      "state_name": "Sanity 210121"
    },
    {
      "state_id": 99,
      "state_name": "Sanity State"
    },
    {
      "state_id": 30,
      "state_name": "Sikkim"
    },
    {
      "state_id": 81,
      "state_name": "South Mumbai"
    },
    {
      "state_id": 95,
      "state_name": "state KL"
    },
    {
      "state_id": 85,
      "state_name": "State MH"
    },
    {
      "state_id": 86,
      "state_name": "State MH One"
    },
    {
      "state_id": 96,
      "state_name": "state TN"
    },
    {
      "state_id": 93,
      "state_name": "state1"
    },
    {
      "state_id": 31,
      "state_name": "Tamil Nadu"
    },
    {
      "state_id": 84,
      "state_name": "tamilnadu"
    },
    {
      "state_id": 92,
      "state_name": "tel1"
    },
    {
      "state_id": 32,
      "state_name": "Telangana"
    },
    {
      "state_id": 97,
      "state_name": "test"
    },
    {
      "state_id": 102,
      "state_name": "Test st"
    },
    {
      "state_id": 87,
      "state_name": "Test State"
    },
    {
      "state_id": 94,
      "state_name": "test state new"
    },
    {
      "state_id": 100,
      "state_name": "Test State123"
    },
    {
      "state_id": 108,
      "state_name": "test state1234"
    },
    {
      "state_id": 101,
      "state_name": "Test123"
    },
    {
      "state_id": 106,
      "state_name": "testtesttest"
    },
    {
      "state_id": 33,
      "state_name": "Tripura"
    },
    {
      "state_id": 34,
      "state_name": "Uttar Pradesh"
    },
    {
      "state_id": 35,
      "state_name": "Uttarakhand"
    },
    {
      "state_id": 36,
      "state_name": "West Bengala"
    }
  ],
  "ttl": 24
}

**Comment by badinenisaivardhan** [comment]
@chalukyamohanraj  Check on This State Id endpoints 80,83,82,90,105,89,103,104,99,86,93,96,84,92,97,102,87,94,100,108,101,106  one center will be found for a catch..!

**Comment by badinenisaivardhan** [comment]
> 
> 
> @badinenisaivardhan Yeh, we authenticated the beneficiary using OTP through protected APIS. Yes, we have added a beneficiary to the sandbox data. when we are hitting calenderByDistric or Pincode it is just returning an empty response.

May I Know what procedure did you follow to get to register for sandbox access @chhabraharsh , help me in process or register link is appreciated.. 👍

**Comment by chhabraharsh** [comment]
@badinenisaivardhan Tried some random district ID = 151 for Goa->North Goa and it worked.
In this district, it is returning some data for centers. Otherwise, it is next to impossible for someone to test a scheduled vaccine feature. 

Thanks, @badinenisaivardhan  for your prompt replied and support. Much appreciated.
