### ISSUE TITLE
Book Appointment for Dose (1/2): wrongly architected cowin app UI and api design 

### ISSUE THREAD

**Issue by nitinkothwal** [cowinapi/developer.cowin#432]
I was looking to book my first appointment. I found it is very tedious task ever to do from end user perspective.

My observations:
- User need to keep on searching to book their slot. This part is worst developed by the developers / architectures. This will increase number of api calls to the api servers. 
    - why don't you guys have used push mechanism (websocket) to make things live on their own? 
    - Once vaccine availability is added into the cowin, the application would have notified all the connected web clients proactively.
- If I'm logged in user you know all my details age / DOB etc still why I needed to select filters 18+ / 45+?
    - I'm trying to book vaccine for my self it ask me filter by 18+, Free / Paid etc. I didn't understood logic to fetch all the centers for my area and then make user to filter out. By doing this you are making more n/w traffic from your servers.

I'm thinking that you designed this app only to serve technically good people b/c they only can tweak through booking slot. This doesn't provide equal access to all common people who need vaccine first.

We software / IT guys can think from that perspective and could have come with innovative approach to book these appointments.

**Comment by arunim2405** [comment]
- If I'm logged-in user you know all my details age / DOB etc still why I needed to select filters 18+ / 45+?

You can add multiple beneficiaries from one account, so this point is invalid
