### ISSUE TITLE
Random 401 error while hitting url from browser

### ISSUE THREAD

**Issue by amanthakkar** [cowinapi/developer.cowin#44]
If I try hitting https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=395&date=08-05-2021 for example, most of the time I get a valid response but every now and then I get Unauthorized Access. Why is that? Does not seem to be related to the IP address limit.

**Comment by abhishek1234321** [comment]
are you getting 401 or 403? if 403 and something like this 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>

<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
	<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD>

<BODY>
	<H1>403 ERROR</H1>
	<H2>The request could not be satisfied.</H2>
	<HR noshade size="1px">
	Request blocked.
	We can't connect to the server for this app or website at this time. There might be too much traffic or a
	configuration error. Try again later, or contact the app or website owner.
	<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
	<BR clear="all">
	<HR noshade size="1px">
	<PRE>
Generated by cloudfront (CloudFront)
Request ID: 6scDxeN7pcVB231HNezu_yxvtdA7MtQv7zsfRYqHkSfdKps3ZpKENA==
</PRE>
	<ADDRESS>
	</ADDRESS>
</BODY>

</HTML>
```

This is basically to disallow bots and stuff

**Comment by heavell7870** [comment]
@abhishek1234321 it's disallowing bots but it's not working on android I tried many solution but all of them failed

**Comment by ricky-bhatia** [comment]
> If I try hitting https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=395&date=08-05-2021 for example, most of the time I get a valid response but every now and then I get Unauthorized Access. Why is that? Does not seem to be related to the IP address limit.

You need to use the public API url. The one you have listed is a protected API and might only work with authentication.

**Comment by atulmits** [comment]
URL is working fine. Just update the date as well.
