### ISSUE TITLE
unable to download appointment slip

### ISSUE THREAD

**Issue by suraj-deshmukh** [cowinapi/developer.cowin#440]
i am trying to download appointment slip through python request module but i am getting below error msg

```
In [28]: pdf = session.get("https://cdn-api.co-vin.in/api/v2/appointment/appointmentslip/download?appointment_id=5c34fc4a-4f6f-480b-9f4c-6d03eebc7f00")
In [29]: print(pdf)                                                                                                                                                                                         
<Response [504]>
In [30]: pdf.json()                                                                                                                                                                                         
Out[30]: {'message': 'Endpoint request timed out'}
```
session used here is authenticated one. I am facing same issue from cowin portal as well. 

![slip](https://user-images.githubusercontent.com/14833831/121927999-549a8f00-cd5d-11eb-9d55-d9313c422b1f.png)

**Comment by shababps** [comment]
How you got the appointment id?

**Comment by suraj-deshmukh** [comment]
I booked the appointment today that's why I got appointment id

**Comment by shababps** [comment]
Where does it displays on dashboard?
You hashed it right ?

**Comment by shababps** [comment]
Downloading appointment slip needs to use protected API. You have to get API key from them by register on the link provided above the API Development Page.

**Comment by suraj-deshmukh** [comment]
> Where does it displays on dashboard?
> You hashed it right ?

You won't be able to see appointment id on dashboard unless you open browser in inspect mode. What i am trying to show here is even from portal it is getting timeout.

**Comment by shababps** [comment]
ok, I do notice that. I am also looking for a solution
.

**Comment by suraj-deshmukh** [comment]
I guess issue is resolved now bcz I am able to download appointment slip.

Closing this issue
