### ISSUE TITLE
The protected API for downloading Certificate throwing 500 error

### ISSUE THREAD

**Issue by BhawanjitSinghSaini** [cowinapi/developer.cowin#443]
The protected API for downloading Certificate throwing 500 error

https://cdndemo-api.co-vin.in/api/v2/registration/certificate/download

**Comment by BhawanjitSinghSaini** [comment]
The Error 

{"errorCode":"CERTIFICATE00002","error":"parsing body body from \"\" failed, because json: cannot unmarshal string into Go struct field CertificationRequestV2RecipientAddress.recipient.address.pincode of type int64"}

**Comment by big89** [comment]
In response of this API call, you will get pdf data in binary format that you need to display as pdf file.

curl -X GET "https://cdndemo-api.co-vin.in/api/v2/registration/certificate/download?beneficiary_reference_id=1234567890123" -H  "accept: application/pdf" -H  "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxx"

Thanks,
Logicmaker

**Comment by BhawanjitSinghSaini** [comment]
> In response of this API call, you will get pdf data in binary format that you need to display as pdf file.
> 
> curl -X GET "https://cdndemo-api.co-vin.in/api/v2/registration/certificate/download?beneficiary_reference_id=1234567890123" -H "accept: application/pdf" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxx"
> 
> Thanks,
> Logicmaker

**Comment by BhawanjitSinghSaini** [comment]
@big89 yes i know that. But i am getting this error.
