### ISSUE TITLE
unable to create beneficiary

### ISSUE THREAD

**Issue by aviroop89** [cowinapi/developer.cowin#446]
Was trying to develop an app using the API set but unable to create beneficiary. What I am doing wrong? Error received - Unauthorized Access

**Comment by big89** [comment]
@aviroop89 Make sure you have passed Authorization Bearer token in request header which you will get in response of confirm OTP api.

curl -X POST "https://cdndemo-api.co-vin.in/api/v2/registration/beneficiary/new" -H  "accept: application/json" -H  **"Authorization: Bearer** xxxxxxxxxxxxxxxxxxxxxxxxxxx" -H  "Content-Type: application/json" -d "{\"name\":\"Apparao\",\"birth_year\":\"1980\",\"gender_id\":1,\"photo_id_type\":1,\"photo_id_number\":\"9999\",\"comorbidity_ind\":\"Y\",\"consent_version\":\"1\"}"

Thanks,
Logicmaker

**Comment by aviroop89** [comment]
> @aviroop89 Make sure you have passed Authorization Bearer token in request header which you will get in response of confirm OTP api.
> 
> curl -X POST "https://cdndemo-api.co-vin.in/api/v2/registration/beneficiary/new" -H "accept: application/json" -H **"Authorization: Bearer** xxxxxxxxxxxxxxxxxxxxxxxxxxx" -H "Content-Type: application/json" -d "{"name":"Apparao","birth_year":"1980","gender_id":1,"photo_id_type":1,"photo_id_number":"9999","comorbidity_ind":"Y","consent_version":"1"}"
> 
> Thanks,
> Logicmaker

While implementing the confirmOTP API, there is an error message saying "Beneficiary Not registered"...What's the Base URL that needs to be implemented

**Comment by aviroop89** [comment]
At the time of implementing confirmOTP API, getting an error - "Beneficiary not registered" well before getting the Authorization Bearer token. Secondly, what's the Base URL as it is different from the one given in CoWIN site?

**Comment by big89** [comment]
Not sure, but there seems some misbehavior with API, that if no Beneficiary added, then confirm OTP sometimes gives such error. Not sure if there is any such validation applied.

We are talking about Co-WIN Protected APIs with Sandbox url: https://cdndemo-api.co-vin.in/api

Thanks,
Logicmaker

**Comment by aviroop89** [comment]
Thanks for your response...Are you able to generate OTP with the SandBox url? Getting an error 403 (Forbidden)

**Comment by big89** [comment]
Yes, just tested below PHP code and its generating OTP using Protected APIs with given Sandbox API Key -

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://cdndemo-api.co-vin.in/api/v2/auth/generateOTP');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"mobile":"9876543210"}');

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'X-Api-Key: 3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;


Thanks,
Logicmaker

**Comment by aviroop89** [comment]
Thanks...registered

**Comment by aviroop89** [comment]
How are you generating the center list
