### ISSUE TITLE
Solution for 403?

### ISSUE THREAD

**Issue by heavell7870** [cowinapi/developer.cowin#45]
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

This user - agent does not work in android apps please gimme a solution

**Comment by abhishek1234321** [comment]
This works fine from postman, no reason why it wouldn't work from Android app as such

**Comment by heavell7870** [comment]
yeah it's working in chrome but not in android

**Comment by heavell7870** [comment]
@cowinapi please help man I really bought google play console for this only, now from morning it's just eating my head

**Comment by ghostdev7** [comment]
Could you try with this value -> "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)". Works for me.

**Comment by snehil** [comment]
this did not work via curl. Can you paste the command here?

**Comment by heavell7870** [comment]
@ghostdev7  it's working in web but not in android specially in react native

**Comment by heavell7870** [comment]
@cowinapi team waiting for a solution man

**Comment by snehil** [comment]
I got it to work via AWS an AWS lambda fn deployed in Mumbai region

**Comment by snehil** [comment]
it apparently only works in India (I am not in India)

**Comment by sumitkr1992** [comment]
While calling the public APIs via local or postman, it's working with
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

But if deploying the same code to heroku server, **Appointment Availability APIs** public apis throwing 403 Forbidden error.
Any solution for this?

**Comment by iamarjun** [comment]
@sumitkr1992 try deploying on the Indian region if not already.

**Comment by akshaychavan7** [comment]
> @cowinapi team waiting for a solution man

I also getting the same error :(
Please let me know if you get any solution

**Comment by akshaychavan7** [comment]
> "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

Bingo! this worked for me too!
Thanks a million man :)

**Comment by smitdesai1010** [comment]
> "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

This solved my issue, thanks a lot man!!
But am still wondering what is the cause of this issue ?

**Comment by heavell7870** [comment]
@smitdesai1010  it's a step taken by cowin team for preventing bots

**Comment by Whip** [comment]
Don't send any more requests for 24hrs. You'll get unblocked after some timeout.

**Comment by akshch** [comment]
`"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"`

This solved my problem.
Thank you!
