### ISSUE TITLE
findByLatLong - Unauthenticated access!

### ISSUE THREAD

**Issue by webloper** [cowinapi/developer.cowin#457]
curl -X GET "https://cdndemo-api.co-vin.in/api/v2/appointment/centers/findByLatLong?lat=26.846695&long=80.946167" -H "accept: application/json" -H "Accept-Language: hi_IN" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxx"

Getting response - 401 

Unauthenticated access!

**Comment by big89** [comment]
It seems that your Authorization Bearer token is no more valid.
Please try once again by passing valid once and confirm as its working for me.

Thanks & Regards,
Logicmaker

**Comment by webloper** [comment]
@big89 Hi I have checked thrice, every time i am getting the same error

**Comment by badinenisaivardhan** [comment]
Hey @webloper Try , curl -X GET "https://cdndemo-api.co-vin.in/api/v2/appointment/centers/findByLatLong?lat=26.846695&long=80.946167" -H "accept: application/json" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by webloper** [comment]
hi I have checked same from localhost and server

curl -X GET "https://cdndemo-api.co-vin.in/api/v2/appointment/centers/findByLatLong?lat=26.846695&long=80.946167" -H "accept: application/json" -H "Authorization: Bearer eyJhXXXXXXXXXXXX"



<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: OLns21Lag2ACEBPqjdBgo2d_kMKHlI026yXApf5TWOqah2FYAXeNzA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by badinenisaivardhan** [comment]
@webloper ,Are you requesting this API within India or outside India..?
Because it is working fine with testing ..
![Capture](https://user-images.githubusercontent.com/24708206/122894473-d6de1100-d364-11eb-9fe7-195c8273d90a.JPG)

**Comment by big89** [comment]
@webloper You should access this APIs from Indian IP only.

Check the below working PHP cURL script for the same -

`<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://cdndemo-api.co-vin.in/api/v2/appointment/centers/findByLatLong?lat=28.7&long=77.1');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Accept-Language: en_US';
$headers[] = 'Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;

?>`

Thanks,
Logicmaker

**Comment by webloper** [comment]
:cry:

@big89 
![Clipboard01](https://user-images.githubusercontent.com/334000/122897702-dc892600-d367-11eb-8685-b9a0246cd00c.jpg)

**Comment by webloper** [comment]
@badinenisaivardhan India Lucknow :cry:

**Comment by big89** [comment]
@webloper It will be better if you could explain in detail the steps you are following.

**Comment by webloper** [comment]
@big89 

Here are the steps

BASE_URL = https://cdndemo-api.co-vin.in/api/v2

Step 1 POST {{BASE_URL}}/auth/public/generateOTP 
Request Param mobile 
Response txnId

Step 2 POST {{BASE_URL}}/auth/public/confirmOTP
Request Param sha256 ( otp ), txnId
Response token = xxxxxxxxxxxxxxx

Step 3 GET {{BASE_URL}}/appointment/beneficiaries
Request Headers
Accept: application/json
Accept-Language: en_US
Authorization: Bearer token

Response
Unauthenticated access!

**Comment by badinenisaivardhan** [comment]
hey @webloper , on identifying steps you have followed, you are using wrong end points for sandbox ,use this endpoints for sandbox testing,not public endpoints..
 OTP Generation : https://cdndemo-api.co-vin.in/api/v2/auth/generateOTP 
 Token Generation And OTP Conformation : https://cdndemo-api.co-vin.in/api/v2/auth/confirmOTP
and above code in php will work ... Thanks..!

**Comment by webloper** [comment]
@badinenisaivardhan :no_mouth: Thanks its working, I didn't notice this change damn.

**Comment by webloper** [comment]
Closing this issue
