### ISSUE TITLE
appointment/beneficiaries - Unauthenticated access!

### ISSUE THREAD

**Issue by webloper** [cowinapi/developer.cowin#458]
curl -X GET "https://cdndemo-api.co-vin.in/api/v2/appointment/beneficiaries" -H "accept: application/json" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Getting Response - 401

Unauthenticated access!

**Comment by big89** [comment]
It seems that your Authorization Bearer token is no more valid.
Please try once again by passing valid once and confirm as its working for me.

Thanks & Regards,
Logicmaker

**Comment by webloper** [comment]
@big89 Hi I have checked thrice, every time i am getting the same error

**Comment by webloper** [comment]
Closing as Its working, For OTP generation we have to use  /v2/auth/generateOTP not /v2/auth/public/generateOTP
