### ISSUE TITLE
Daily district-wise vaccination data

### ISSUE THREAD

**Issue by runformoney** [cowinapi/developer.cowin#459]
Need data to run some TS analysis and visualization similar to: https://dashboard.cowin.gov.in/
Any pointers are appreciated.

**Comment by big89** [comment]
Currently, I can see only this option on Co-Win website publicly available -

https://api.cowin.gov.in/api/v1/reports/v2/getPublicReports?state_id=&district_id=&date=2021-06-22

https://dashboard.cowin.gov.in/assets/json/csvjson.json

**Note:** Above is for reference purpose only and can be considered as unofficial API.

Thanks,
Logicmaker

**Comment by runformoney** [comment]
Problem is solved ;)
