### ISSUE TITLE
How to access Public Cowin Certificate API ? 

### ISSUE THREAD

**Issue by Anirudhk07** [cowinapi/developer.cowin#46]
Even though the `Certificate API` is public , I am getting `Unauthenticated access!` even after entering correct beneficiary_reference_id. Can someone help in this regard ?

Get request url  -->https://cdn-api.co-vin.in/api/v2/registration/certificate/public/download?beneficiary_reference_id=

Can someone pls tell how to use the Bearer Token to further request for the certificate.

For eg. I first used `/v2/auth/public/generateOTP` To generate otp and got the `txn-id`. After this I confirmed the OTP and `txn-id`. In return I got back a **Token**.

After this how should I request for the certificate api ? What to do with **Token**? How to use this API - /v2/registration/certificate/public/download

I got a binary text in return. Is that the vaccination certificate ? How do I convert it to PDF?

**Comment by m0j0r0j0** [comment]
send the token in header 

 conn.setRequestProperty("Authorization", "Bearer "+your token);

**Comment by sudarshankushal** [comment]
how do i get the token?

**Comment by yashbrid03** [comment]
> Even though the `Certificate API` is public , I am getting `Unauthenticated access!` even after entering correct beneficiary_reference_id. Can someone help in this regard ?
> 
> Get request url -->https://cdn-api.co-vin.in/api/v2/registration/certificate/public/download?beneficiary_reference_id=
> 
> Can someone pls tell how to use the Bearer Token to further request for the certificate.
> 
> For eg. I first used `/v2/auth/public/generateOTP` To generate otp and got the `txn-id`. After this I confirmed the OTP and `txn-id`. In return I got back a **Token**.
> 
> After this how should I request for the certificate api ? What to do with **Token**? How to use this API - /v2/registration/certificate/public/download
> 
> I got a binary text in return. Is that the vaccination certificate ? How do I convert it to PDF?

Hey @Anirudhk07 How did you confirmed the OTP ? I have the following issues

what should I pass in `otp` ? If I pass the actual OTP is shows Invalid OTP .
**Thanks in Advance**

**Comment by sudhir-trigyn** [comment]
Send OTP in sha256 hash format

**Comment by Anirudhk07** [comment]
Hello @yashbrid03  you first need to convert OTP to SHA256. This SHA256 value will then be compared with the `txn-id`.

You can check this site to convert it to SHA256 - https://emn178.github.io/online-tools/sha256.html

Hope this helps! :)

**Comment by Anirudhk07** [comment]
@sudhir-trigyn  Do you have any idea on how to convert binary content to viewable PDF?

**Comment by m0j0r0j0** [comment]
> @sudhir-trigyn Do you have any idea on how to convert binary content to viewable PDF?

+1 same doubt!

**Comment by sudhir-trigyn** [comment]
We done that in angular by converting it into blob then creating object URL.
In java I have no idea. But try this solution you may have to convert that binary data into byte array, after that write that byte array to fileoutputstream.

**Comment by Anirudhk07** [comment]
@yashbrid03  If your doubt is resolved , I would request you to remove that image as it contains your personal details

**Comment by Anirudhk07** [comment]
> We done that in angular by converting it into blob then creating object URL.
> In java I have no idea. But try this solution you may have to convert that binary data into byte array, after that write that byte array to fileoutputstream.

I got a very big response back , some characters are not readable too. So what exact part do we have to convert ?

**Comment by sudhir-trigyn** [comment]
Are you using RestTemplate to call the API? 
If yes what is the response type you mentioned in RestTemplate?

You have convert whole response into byte array

**Comment by sudhir-trigyn** [comment]
If you are Using Resttemplate. You can do something like this

restTemplate.execute(
  FILE_URL,
  HttpMethod.GET,
  clientHttpRequest -> clientHttpRequest.getHeaders().set(
    "Range",
    String.format("bytes=%d-%d", file.length(), contentLength)),
    clientHttpResponse -> {
        StreamUtils.copy(clientHttpResponse.getBody(), new FileOutputStream(file, true));
    return file;
});

**Comment by Anirudhk07** [comment]
Thanks @sudhir-trigyn

**Comment by m0j0r0j0** [comment]
@Anirudhk07 does the able resttemplete code worked for you?
