### ISSUE TITLE
binary content to PDF download

### ISSUE THREAD

**Issue by m0j0r0j0** [cowinapi/developer.cowin#47]
I am getting some binary data in response using download certificate API. 

Can someone help me to convert the binary content to pdf in java.

**Comment by Anirudhk07** [comment]
@m0j0r0j0  same doubt ! Getting binary content , but how to convert it to PDF?
Please let me know if you are able to figure it out!

**Comment by satishchandra-pandey** [comment]
It is of type blob.

Please refer sample angular code

 this.http.get<any>(`/appointmentslip/download?appointment_id=${appointment_id}`, requestOptions)
        .subscribe((fileData) => {
       
            const blob: any = new Blob([fileData], { type: 'application/pdf' });
    
            const link = document.createElement('a');
            if (link.download !== undefined) {
              const url = URL.createObjectURL(blob);
              link.setAttribute('href', url);
              link.setAttribute('download', fileName);
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
            }
        });

**Comment by m0j0r0j0** [comment]
@Anirudhk07 Have u tried  in java ? 
 
I am getting error in converting inputstream to byte[ ]

**Comment by satishchandra-pandey** [comment]
https://stackoverflow.com/questions/28220352/how-to-convert-a-blob-object-into-a-pdf-file-in-java

**Comment by Anirudhk07** [comment]
I am still unable to convert that output to viewable format. It seems that the returned text is in PostScript. @m0j0r0j0 @satishchandra-pandey were you able to convert it ?

**Comment by satishchandra-pandey** [comment]
@Anirudhk07 the sample code that I gave above is the working code of angular directly calling from broswer.
Please find equivalent in coding language that you are using.

**Comment by m0j0r0j0** [comment]
@Anirudhk07 
Java::
`
ResponseEntity<byte[]> response2 = restTemplate.exchange("https://cdn-api.co-vin.in/api/v2/registration/certificate/public/download?beneficiary_reference_id="+beneficiaryId+"", HttpMethod.GET, entity, byte[].class);
   

	    
		
	    HttpHeaders header = new HttpHeaders();
	    header.setContentType(MediaType.APPLICATION_PDF);
	    header.set(HttpHeaders.CONTENT_DISPOSITION,
	                   "attachment; filename="+beneficiaryId+".pdf");
	    header.setContentLength(response2.getBody().length);
	    
	    return new HttpEntity<byte[]>(response2.getBody(), header); `

**Comment by Anirudhk07** [comment]
@m0j0r0j0 so do we first need to convert it to byte array ? Actually I am doing it in dart. Can you explain what exactly is the process to convert in words?

**Comment by Anirudhk07** [comment]
@m0j0r0j0 @satishchandra-pandey  is your response in this format ?
```

 %PDF-1.7
 
  1 0 obj
  <<
    /Type /Catalog
    /Pages 2 0 R
  >>
  endobj
```

**Comment by Anirudhk07** [comment]
@m0j0r0j0 @satishchandra-pandey any clue?
The base64 seems invalid in my case

**Comment by Anirudhk07** [comment]
https://stackoverflow.com/questions/67433878/invalid-characters-while-converting-api-response-to-pdf

See this @m0j0r0j0 @satishchandra-pandey

**Comment by yashbrid03** [comment]
> @m0j0r0j0 @satishchandra-pandey is your response in this format ?
> 
> ```
> 
>  %PDF-1.7
>  
>   1 0 obj
>   <<
>     /Type /Catalog
>     /Pages 2 0 R
>   >>
>   endobj
> ```

Hey I got the same response in POSTMAN
I converted it to viewable format by saving the response to file with .pdf extension.
![image](https://user-images.githubusercontent.com/65955929/117530134-1fca4800-aff9-11eb-9203-0e9d12046d6f.png)
