### ISSUE TITLE
Suggestion To Add GOVT COVID VACCINATION CENTERS AND CAMPS -  ADDRESS 

### ISSUE THREAD

**Issue by badinenisaivardhan** [cowinapi/developer.cowin#488]
Can You Add ****GOVT COVID VACCINATION** Centers And CAMP Address** With **Sate Wise** And **District Wise** ADDRESS, That Will Useful to The People Who are not aware of the COVID VACCINATION Centers Which are around them, it helps people to Walk-In and make an spot registration. #THANKS

**Comment by siddhesh1770** [comment]
+1

**Comment by siddhesh1770** [comment]
there should be map link in  appointment letter
