### ISSUE TITLE
How to find district id ?

### ISSUE THREAD

**Issue by siddharthbiju** [cowinapi/developer.cowin#490]
​/v2​/appointment​/sessions​/public​/calendarByDistrict

**Comment by big89** [comment]
You can get district list with district id using below API -

/v2/admin/location/districts/{state_id}

Thanks,
Logicmaker

**Comment by gourcool** [comment]
Visit the following api - 

https://cdn-api.co-vin.in/api/v2/admin/location/districts/[state_id]

In response you will get the districts with their id's like this - 

{
  "districts": [
    {
      "state_id": 16,
      "district_id": 391,
      "district_name": "Ahmednagar",
      "district_name_l": ""
    }
  ],
  "ttl": 0
}

**Comment by siddharthbiju** [comment]
But how to get state ID ?

**Comment by gourcool** [comment]
Visit the following api -

https://cdn-api.co-vin.in/api/v2/admin/location/states

In response you will get the states with their id's like this -

{
  "states": [
    {
      "state_id": 58,
      "state_name": "Andaman and Nicobar Islands",
      "state_name_l": ""
    }
  ],
  "ttl": 0
}
