### ISSUE TITLE
findslot.in - Allow users who wish to get a slot booked to do so

### ISSUE THREAD

**Issue by pulse-aj** [cowinapi/developer.cowin#5]
As part of building the whatsapp bot for findslot.in we want to allow users who want to book a slot as soon as its available in their pin code. We would like to get their opt in for booking upfront and place them in a queue within our system. When COWIN says there is slot free in that district, we will go ahead and book the slot after reconfirming it with the user. 

Suggestion is to provide this as a private API to trusted services to prevent abuse.

**Comment by chandraaditya** [comment]
I think this would be really useful! I have been trying to see if I can find a workaround but have not been able to. 

But I agree that an API like that would be extremely useful.

**Comment by amitvsavant** [comment]
@Pulse-akhil Pulse-akhil is this issue same as #4

**Comment by pulse-aj** [comment]
No. Issue 4 is about getting COWIN API servers informing a 3rd party service whenever a refresh is done to the vaccination slots. For example: if slot availability data for any of the districts becomes refreshed, you simply send a POST request to an endpoint the 3rd party service provides you, the POST payload will be the entire JSON body of all the vaccination centers in India. This ensures that 3rd party services do not need to continuously poll your infrastructure at regular intervals (saves you cost and ensures all 3rd party services riding on your service has fresh data). 

This is an enhancement request - it's about what happens after a slot is available at a nearby vaccination center. There should be an API endpoint where 3rd party services can book a slot on behalf of a user. Not meant to be a public API, this has to be a private one and only offered to 3rd party services that can guarantee abuse prevention of this endpoint functionality.

**Comment by amitvsavant** [comment]
Thank you for clarification. This API already exists - [CoWIN Protected APIs](https://apisetu.gov.in/public/marketplace/api/cowin/cowin-protected-v2) but it has not been opened up to private parties yet. Please stay tuned for future development on this.

**Comment by rahulswaminathan** [comment]
You could also use a pub-sub model for slot availability data instead of a POST request to be sent to every third party service.

**Comment by rahulswaminathan** [comment]
> As part of building the whatsapp bot for findslot.in we want to allow users who want to book a slot as soon as its available in their pin code. We would like to get their opt in for booking upfront and place them in a queue within our system. When COWIN says there is slot free in that district, we will go ahead and book the slot after reconfirming it with the user.
> 
> Suggestion is to provide this as a private API to trusted services to prevent abuse.

This would be really helpful!
