### ISSUE TITLE
Mismatch in centers shown by pincode and distruct

### ISSUE THREAD

**Issue by muniamma** [cowinapi/developer.cowin#50]
Search by pincode. A set of centers us shown. Search by district where the same pincode is part of. Very few centers shown and the ones shown by pincode do not appear.
Eg: 560011 and Bangalore urban.

**Comment by snehil** [comment]
how did you get it to work? I am seeing an http 403 error..

**Comment by akhilesh-godi** [comment]
Try district BBMP perhaps? Not Bangalore Urban.

**Comment by muniamma** [comment]
Just opened the app on my mobile and searched.

G Padmanabhan

**Comment by muniamma** [comment]
BBMP seems to return better results. However, on loggin in and doing the
same search, there is some difference in results (Apollo Jayanagar dies not
show up).

However, I am more interested in getting a solution to the previous issue
that I logged - after login, current date is not shown.

G Padmanabhan
