### ISSUE TITLE
Cowin Dashboard showing wrong total vaccination data

### ISSUE THREAD

**Issue by amanarora1707** [cowinapi/developer.cowin#503]
![Screenshot (50)](https://user-images.githubusercontent.com/66989611/125523360-c1062011-36fa-46f7-a026-08baecbb64eb.png)
Cowin Dashboard is showing wrong total vaccination data

**Comment by siddhesh1770** [comment]
Please explain issue in detail

**Comment by amanarora1707** [comment]
issue is resolved
