### ISSUE TITLE
No beneficiaries

### ISSUE THREAD

**Issue by vishwanath-dev95** [cowinapi/developer.cowin#505]
After passing the API key & token on the sandbox server for testing, I am getting no beneficiaries even though the mobile number is linked with 2 beneficiaries. The same is happening with download the Cowin vaccination certificate API as getting the beneficiary_reference_id does not exist in response.
![2021-07-15 12_28_35-](https://user-images.githubusercontent.com/51533850/125744059-edecc578-6c81-4b18-9404-58cc0612cb4b.jpg)
![2021-07-15 12_35_58-Mail](https://user-images.githubusercontent.com/51533850/125744631-c5c13b65-c632-49c4-afe9-4a0af11b20ab.jpg)

**Comment by John0911** [comment]
you need to add beneficiaries in sandbox for a phone number

**Comment by siddhesh1770** [comment]
demo server doesn't returns any data present on live

**Comment by siddhesh1770** [comment]
you should create dummy beneficiaries on this server

**Comment by vishwanath-dev95** [comment]
Thanks, @siddhesh1770
