### ISSUE TITLE
Trusted API key for just calendar data.

### ISSUE THREAD

**Issue by ofpiyush** [cowinapi/developer.cowin#51]
Quite a few notification systems have popped up to help people in this crisis.

The new API restrictions make it difficult for these systems to help people.

Specifically 2 things:
- cache time of 10-30 minutes on the public API endpoints.
- rate limit on the API by IP

As you must be aware, bad actors can still book the slots automatically anyway.

Good actors and people trying to help others are not able to give quality information to everyone.

To mitigate this, can we get an API key that allows us to query only the `calendarByDistrict` and `calendarByPin` public/protected API endpoints with higher rate limit and lower cache time?

Alternatively, if there was a way to get notified ahead of time or [register ourselves in a token/queue system](https://github.com/cowinapi/developer.cowin/issues/11#issuecomment-832337384), that would solve the problem as well.

**Comment by abhishek1234321** [comment]
`calendarByDistrict` and `calendarByPin` work without the token from what I understand

**Comment by souvik234** [comment]
@abhishek1234321 Yes, but both of these are still rate-limited for the public endpoint

**Comment by akhilesh-godi** [comment]
@ofpiyush I think you should open up a new issue - an enhancement for the token/queue system - not just for registration for updates but for real allocation of slots as well. I definitely think there needs to be such a system in place. It is also the right thing to do as long as the algorithm used for such an allocation of slots is 'fair' and backed by a vaccination 'policy'. The outline of your proposal is nice. It might be worth exploring it further. I hope the devs on this issue can take the enhancement proposal forward.

**Comment by ofpiyush** [comment]
Thanks @akhilesh-godi! I've created an issue #72 for it
