### ISSUE TITLE
{errorCode: USRAUT0010, error: Mobile is Required}

### ISSUE THREAD

**Issue by sidB67** [cowinapi/developer.cowin#515]
I am getting this error while posting in dart. The code is below
() async {
               
               var response = await http.post(url,body: json.encode({
                "mobile":'8130664467'
               }
               ) );
                
                print(jsonDecode(response.body));
              },

**Comment by big89** [comment]
To understand better, provide sufficient information like which API you are using and exact error/response you are getting.

Thanks,
Logicmaker

**Comment by vinfur** [comment]
> I am getting this error while posting in dart. The code is below
> () async {
> 
> ```
>            var response = await http.post(url,body: json.encode({
>             "mobile":'8130664467'
>            }
>            ) );
>             
>             print(jsonDecode(response.body));
>           },
> ```

You Have To Use "Post" Request
along with content type header
and Accept header
Both Should be Application/json
