### ISSUE TITLE
Provide bulk api for query by pincode 

### ISSUE THREAD

**Issue by arpanagr** [cowinapi/developer.cowin#52]
Since there a rate limit of 100 calls per 5 min. 

Can you please provide a api which take 20-25 pinches at a time and return the data. That ways one can still be in limits and also get more real time data

**Comment by backtrackbaba** [comment]
@arpanagr are those 20-25 pincodes a part of the same district? Or in how many districts do they come under?

**Comment by arpanagr** [comment]
I don't think they should have any relationship. So, they can belong to same district or all of them can belong to different district. It's just a bulk version of already present calendar api by pincode. One just needs to call the same code in a loop and return the result.

**Comment by arpanagr** [comment]
Any update here? Is the district id, state id always constant? I see a ttl value which makes me believe that it change

**Comment by arpanagr** [comment]
Since the admin has closed this, what is the resolution?
