### ISSUE TITLE
Filters for paid, vaccine type in search

### ISSUE THREAD

**Issue by muniamma** [cowinapi/developer.cowin#53]
Please include filters for vaccine type and paid in the search (in both before and after login)

**Comment by sudhir-trigyn** [comment]
Team is already working on this. It will be live soon. Thanks for you suggestion

**Comment by muniamma** [comment]
Would be good to include booked, open, all filters as well.

**Comment by riteshpanjwani** [comment]
We need to select the filters each time we hit the search button as they get cleared after the button click.

**Comment by muniamma** [comment]
I have done that.

G Padmanabhan
