### ISSUE TITLE
Getting 401 "Unauthenticated access" for '/v3/vaccination/status' endpoint

### ISSUE THREAD

**Issue by monu-simon** [cowinapi/developer.cowin#537]
I have added the valid Bearer token and even so it gives me this errror.

**Comment by lingan7** [comment]
@monu-simon  have you got it correct?

**Comment by lingan7** [comment]
i am trying for past 5 days, getting the same Unauthenticated Access, If you have got it. Can you please say the changes

**Comment by dmdhrumilmistry** [comment]
I'm also facing same issue
