### ISSUE TITLE
Using Vaccination Verification API

### ISSUE THREAD

**Issue by shahns** [cowinapi/developer.cowin#543]
I am trying to use vaccination verification API which is listed under Co-WIN public APIs.

When I send a POST request to test server using test API key ([https://cdndemo-api.co-vin.in/api/v3/vaccination/generateOTP](https://cdndemo-api.co-vin.in/api/v3/vaccination/generateOTP)) with a valid mobile number and full name I get following response with status code 400.

`{"errorCode":"USRAUT0015", "error":"Your account does not exist"}`

As per API docs it means the mobile number is invalid. Has anyone faced similar issue?

**Comment by shahns** [comment]
I understand that this could be possibly due to mobile number is queried on the test server and account should not exist there but on the production server.

**Comment by rahulkathet** [comment]
Production server give "Unauthenticated access!"
Do you have any idea how to get access ?
