### ISSUE TITLE
Logged in and logged out availability for pincode shows different results ... doesnt return many centers

### ISSUE THREAD

**Issue by raghuvivekg** [cowinapi/developer.cowin#57]
While am trying to search for 560100 , i can see there is one vaccination center in logged out view . when i login and try for same pincode it shows no vaccination centers are available .... Have observed this issue with multiple pin codes
![Loggedout_560100](https://user-images.githubusercontent.com/9539396/117409366-bd0c7a00-af2e-11eb-8e00-7dd26c7ef6eb.png)
![LoggedIn_560100](https://user-images.githubusercontent.com/9539396/117409514-e1685680-af2e-11eb-91e6-294a9c8b94fd.jpg)

**Comment by theGeekyLad** [comment]
@raghuvivekg I can second this argument as I too have faced the same. I've noticed that the logged-in slot data is what even the API returns and hence (maybe) veracious.

**Comment by networkrahul** [comment]
@raghuvivekg  Logged out version uses public API, while logged in version uses authenticated API. So this is probably due to cached (upto 30 mins stale) information being returned by public API

**Comment by raghuvivekg** [comment]
@networkrahul : while the center has no slots available ... even if the data is cached i would expect the API to return the center as slots are completely booked ... But in this case when i login the center doesnt show up completely .... this is happening with the centers who has availability for vaccine in different pin code ... Since it doesnt show in logged in view there is no way to book those slots
