### ISSUE TITLE
Reduce the Appointment Availability caching to 5 mins instead of 30 mins

### ISSUE THREAD

**Issue by shyamal890** [cowinapi/developer.cowin#58]
Hi Team,

Having 30 mins of cache is too long, why not reduce it to 5 mins? That would help 3rd party apps to send out correct and recent data to people who are awaiting their turn to get vaccinated. 

Moreover, reducing the caching from 30 mins to 5 mins won't have much performance implications too. 

Given the above reasons, I hope the team makes the change in the benefit of the nation. 

Regards,

**Comment by Whip** [comment]
Closed by a bot? Pathetic.
