### ISSUE TITLE
findslot.in - Allow users to get their vaccination certificate via APIs

### ISSUE THREAD

**Issue by pulse-aj** [cowinapi/developer.cowin#6]
Once a user a vaccinated they can get a copy of their vaccination certificate (PDF) via the whatsapp bot we are building. We will perform a OTP verification with the user before we vend out the vaccination certificate. In order to do this successfully, we will need a private API end point that allows users to download the vaccination certificate.

**Comment by kalps02** [comment]
Allow users to make changes in their final vaccine certificate.As many had errors in aadhar card number and even names.

**Comment by amitvsavant** [comment]
@Pulse-akhil , a public API [/v2/registration/certificate/public/download](https://apisetu.gov.in/public/marketplace/api/cowin/)  is already available for this. Is this not useful for your bot?

**Comment by pulse-aj** [comment]
yes, and sorry for not catching that before.

**Comment by kalps02** [comment]
Will you make changes in the app to change the error,as my father is one of them whose aadhar card and even middle name is wrong in the final vaccine certificate.

**Comment by chalukyamohanraj** [comment]
Yes, there will be feature made available to correct the vaccine certificate.

**Comment by kalps02** [comment]
Can we make changes in aadhar card number as well as name

**Comment by chalukyamohanraj** [comment]
Clerical and Substantive errors will be considered for corrections based on few conditions.

**Comment by kalps02** [comment]
Ok.Thank you.waiting for the day when we can make changes.Please keep
everyone updated.Thanks once again
