### ISSUE TITLE
Appointment slots for dose 2 should be different from those for dose 1

### ISSUE THREAD

**Issue by akhilesh-godi** [cowinapi/developer.cowin#60]
There are a lot of beneficiaries especially those falling into the priority group of Healthcare Workers (HCWs), Frontline Workers (FLWs) from the 18-44 group who will find it difficult to find slots for dose 2 if appointment slots are from a common pool. Recommend that pool of vaccines and appointment slots for Dose 1 and Dose 2 be separate (if not already done).

This problem will worsen since vaccination has been opened up to all of 18-44.

**Comment by sudhir-trigyn** [comment]
This feature is already under development will be out soon.  Thanks for your suggestion
