### ISSUE TITLE
Unable to convert returned output of Certificate to viewable format 

### ISSUE THREAD

**Issue by Anirudhk07** [cowinapi/developer.cowin#61]
My output starts with 

```
 %PDF-1.7
 
  1 0 obj
  <<
    /Type /Catalog
    /Pages 2 0 R
  >>
  endobj
 
  2 0 obj
  <<
    /Type /Pages
    /MediaBox [ 0 0 595.00 842.00 ]
    /Count 1
    /Kids [  5 0 R  ]
  >>
  endobj
```

It seems like PostScript but I am unable to convert it to viewable format. I am doing it in **dart** , I tried base64 decoding but the returned format seems incorrect ! @satishchandra-pandey @m0j0r0j0

**Comment by Anirudhk07** [comment]
https://stackoverflow.com/questions/67433878/invalid-characters-while-converting-api-response-to-pdf

**Comment by yashbrid03** [comment]
> https://stackoverflow.com/questions/67433878/invalid-characters-while-converting-api-response-to-pdf

Hey @Anirudhk07 is there any way to fetch the beneficiary_reference_id of logged in phone(using otp)? because everyone doesn't remember the  beneficiary_reference_id.

**Comment by Anirudhk07** [comment]
@yashbrid03  no you'll need beneficiary_reference_id. You can get it through Vaccine Certificate or by going on cowin.gov.in

**Comment by erankit100gupta** [comment]
@Anirudhk07 I am not able to figure out beneficiary_reference_id. Could you please share steps/screenshot to obtain it to get certificate

**Comment by parjanyaacoder** [comment]
@Anirudhk07 Were you able to find out any solution for this. I am also stuck at the same error/step .
