### ISSUE TITLE
schedule API giving APPOIN0044

### ISSUE THREAD

**Issue by anuraggoyal1** [cowinapi/developer.cowin#62]
schedule API is throwing 400 bad request with payload - 

{"errorCode":"APPOIN0044", "error":"Please enter valid security code"}

any help please.

**Comment by sudhir-trigyn** [comment]
You need captcha to schedule an appointment.

**Comment by anuraggoyal1** [comment]
is there any API to get captcha ?

**Comment by subrata304** [comment]
@anuraggoyal1 
How did you get the access token to call the protected APIs?

**Comment by siddhesh1770** [comment]
> @anuraggoyal1
> How did you get the access token to call the protected APIs?

he is using Test API

**Comment by crackedpotato007** [comment]
> You need captcha to schedule an appointment.

how do i do that?

**Comment by crackedpotato007** [comment]
> > @anuraggoyal1
> > How did you get the access token to call the protected APIs?
> 
> he is using Test API

there is a work around
