### ISSUE TITLE
Contact CoWIn team

### ISSUE THREAD

**Issue by mtwn105** [cowinapi/developer.cowin#64]
On API Setu CoWIN page it is written "Please contact Ministry of Health and Family Welfare, Government of India to get access to these APIs." How to contact MoHFW or GOI or MeiTY

**Comment by mehimanshupatil** [comment]
For any technical enquiry with respect to COVID-19, you may kindly email on technicalquery.covid19@gov.in  from [https://www.mohfw.gov.in/](https://www.mohfw.gov.in/)

**Comment by Jkvivace** [comment]
i tried to sent mail ,but  recipient e-mail Address has been deactivated.
