### ISSUE TITLE
Appointments Last Updated Date

### ISSUE THREAD

**Issue by mtwn105** [cowinapi/developer.cowin#65]
If possible please add a timestamp field to results for appointments data like `lastUpdatedDate` to see when the last time the appointments data was updated.

**Comment by taralshah1311** [comment]
how do you get the response i have tried using curl, postman both but not getting response from the appointment availability api.

**Comment by shubhamtawde** [comment]
> how do you get the response i have tried using curl, postman both but not getting response from the appointment availability api.

@taralshah1311  You need to add a User Agent in the Header. Curl won't work directly neither will postman. Add a User Agent in the header and you are good to go.

**Comment by taralshah1311** [comment]
@shubhamtawde thanks for the response. 👍 

i have added useragent but still no luck for postman i have tried adding PostmanRuntime/7.28.0 and Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 both 

and for curl i have added only Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

below is my Url
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=380051&date=12-05-2021

can you tell me where i'm making mistake?

**Comment by shubhamtawde** [comment]
@taralshah1311 What output you are getting? If it is blank with sessions as the only object, then the request has completed successfully. This endpoint only shows you the slots that are available, not already booked (or the centers available). Use the 7day calendar endpoint to get the full list (full meaning with booked slots also)

**Comment by taralshah1311** [comment]
@shubhamtawde  thanks for the reply.
I got the response in 7days calendar api.
