### ISSUE TITLE
Inability to receive OTP

### ISSUE THREAD

**Issue by theGeekyLad** [cowinapi/developer.cowin#66]
Has anyone else as well noticed this or is it just me? I've waited out the 3-minute interval for over 4-5 times and still don't receive OTP. This applies to the API as well.

Any thoughts?

**Comment by Prasad-Chaudhari** [comment]
Same issue

**Comment by beenarai** [comment]
I see the same issue . Too much lag and sometimes no OTO is being sent . Most of the times, we need to refresh the page and make a call again

**Comment by Chidroop-i** [comment]
Extremely delayed or no OTPs
