### ISSUE TITLE
Better Design

### ISSUE THREAD

**Issue by sandeepk336** [cowinapi/developer.cowin#68]
Hi Team,

I believe COWIN app should have allowed users to set up password instead of getting OTPs for login.
This could have reduced pain of users in getting SMS for OTP. 

Regards,
Sandeep

**Comment by Developer-R-7** [comment]
Hey @sandeepk336  Nice idea but the government is also seeing the matter that most of population it would be tough for people to make a account and login via password(government wanted it to be as simple as possible) ,  infact just by mobile number and otp it easy to login and maintaing a large users database is also challenging task. 
Regards, Rushi

**Comment by sandeepk336** [comment]
Hi Team,Please give option of password vs OTP , just like www.icicibank.com.  Password setting will give below benefits:
1.  Cowin will save resources as it will not need to connect to SMS server.2. Cowin will not earn bad name for not delivering OTP if there is peak user load.3. Logging in will be easier for users, so they will appreciate the change.

Please check personal banking process of icicibank.com.
Regards,Sandeep
    On Friday, May 7, 2021, 07:49:32 PM GMT+5:30, Rushi Patel ***@***.***> wrote:  
 
 


Hey @sandeepk336 Nice idea but the government is also seeing the matter that most of population it would be tough for people to make a account and login via password(government wanted it to be as simple as possible) , infact just by mobile number and otp it easy to login and maintaing a large user database is also challenging task.
Regards, Rushi
