### ISSUE TITLE
Can we access the protected API for 'Booking appointments'?

### ISSUE THREAD

**Issue by sreeneshkini** [cowinapi/developer.cowin#69]
I tried booking an appointment using protected API with required body parameters and access token but it's showing '401 Unauthorized'. Can we book appointments using protected APIs?

**Comment by sahildarOck** [comment]
That is not possible. Those are protected APIs.
You need to contact Ministry of Health and Family Welfare, Government of India to get access to those. APIs

**Comment by sreeneshkini** [comment]
Okay. Thanks for the clarification. Actually, I tried other protected APIs like 'Getting Vaccination Availability by District' using token and it worked. That's the reason I asked about the appointment API.

**Comment by angsdey2** [comment]
You don't need to pass token, those are public APIs. 
For all private APIs MOHFW are yet to decide on the policy.

**Comment by sreeneshkini** [comment]
Okay Sure. Thanks. I am closing this issue.
