### ISSUE TITLE
Use geolocation and find all nearest centers

### ISSUE THREAD

**Issue by sidtalia** [cowinapi/developer.cowin#7]
Hi,

If possible, please use Geolocation from the device itself and display the nearest centers where slots are available. It can be quite taxing to go through each district and each week of that district. 

Thank you.

**Comment by amitvsavant** [comment]
Thank you @naughtyStark for your suggestion. The APIs and geo-search feature are already in place. Currently this coordinate information for a vaccination site is mostly entered by the site administrators and is inaccurate. CoWIN team is in the process of correcting this information. This may be implemented in near future.
