### ISSUE TITLE
API not providing data however Cowin UI shwing data for same pin and date.

### ISSUE THREAD

**Issue by RajHiray** [cowinapi/developer.cowin#71]
I have try same data in API and Search by pin UI option but API not responding data where as Portal showing details.
Dues CoWin portal uses other API or data source .

![image](https://user-images.githubusercontent.com/48281071/117467672-86a41e80-af71-11eb-9ae8-b0f8c96c9fc8.png)

![image](https://user-images.githubusercontent.com/48281071/117467793-a63b4700-af71-11eb-9871-8cd29fdce950.png)

**Comment by shubhamtawde** [comment]
@RajHiray it only shows the slots which are "available" not which are booked. If slots are booked, API will not show data.

**Comment by vsingal-p** [comment]
^ This was not the case till now. I receive booked slots as well

**Comment by monish-1234** [comment]
Hey ! I checked it out. As far as I've seen, if you get the data for one particular day with `/v2/appointment/sessions/public/findByPin`,it returns only the slots which are not booked.

But curl-ing the API with 
`/v2/appointment/sessions/public/calendarByPin`, returns everything(including one's that are booked)


eg .
`https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=600016&date=08-05-2021`
returns only hospitals with available slots in the pincode '600016' on 08-05-2021 but,
 `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=600016&date=08-05-2021` 
returns hospitals with both available and unavaible slots in the pincode '600016' from 08-05-2021 to the next 7 days

Hope this helps. If it did, help out the Devs by closing the issue.
