### ISSUE TITLE
API and website showing completely different result

### ISSUE THREAD

**Issue by Prankurtiwari** [cowinapi/developer.cowin#74]
API and website showing different result. Why?

 
![Screenshot (22)](https://user-images.githubusercontent.com/43743993/117483873-f3281900-af83-11eb-88d2-6a4b87535a58.png)
![Screenshot (23)](https://user-images.githubusercontent.com/43743993/117483881-f6230980-af83-11eb-8dd5-9f74f4ce01f3.png)
![Screenshot (24)](https://user-images.githubusercontent.com/43743993/117483969-194db900-af84-11eb-9d1a-9ddca86a4e07.png)

**Comment by monish-1234** [comment]
@Prankurtiwari  The month is your GET request is March. Change it to May 
eg- https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=221001&date=07-05-2021

Close the issue and help out the devs if this solves your query.

**Comment by Prankurtiwari** [comment]
@monish-1234  thanks. It was such as blunder.

**Comment by monish-1234** [comment]
> @monish-1234 thanks. It was such as blunder.

That's alright. It do be like that sometimes :)
