### ISSUE TITLE
Called Api beyond prescribed limits.Waited for the cooldown to lapse but still unable to work with the api. Is the blacklisting permanent ?

### ISSUE THREAD

**Issue by nidhiakanksh** [cowinapi/developer.cowin#76]
Called Api beyond prescribed limits.Waited for the cooldown to lapse but still unable to work with the api. Is the blacklisting permanent ?

**Comment by nitinsali** [comment]
try changing you IP using VPN.
APIs are subject to a rate limit of 100 API calls per 5 minutes per IP.

**Comment by Whip** [comment]
For me, it resolves in something like 24hrs

**Comment by nidhiakanksh** [comment]
Damn ! I was already using a VPN on and off. Hasnt worked
