### ISSUE TITLE
calendarByDistrict api is returning incorrect data

### ISSUE THREAD

**Issue by p1sequaltonp** [cowinapi/developer.cowin#77]
The state id for Manipur as returned by the `location/states` api is 22. However, when i pass that as the value of district_id in calendarByDistrict api its showing results for Arunachal Pradesh. Is this is a bug in the api ?

`curl --location --request GET 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=22&date=08-05-2021'`

<img width="1110" alt="Screenshot 2021-05-08 at 12 10 46 AM" src="https://user-images.githubusercontent.com/83837852/117494444-f32f1580-af91-11eb-967f-b03164a99170.png">

**Comment by monish-1234** [comment]
Your usage of the API is a bit wrong.  Use the state API to get the `state_id `and then send the `state_id` to the district API. From the `district_id ` you can calender details.

For example in your case :
1. Use `https://cdn-api.co-vin.in/api/v2/admin/location/states` to get `state_id`
2. Select the desired `state_id` and then send it to (in your case, I guess) 
`https://cdn-api.co-vin.in/api/v2/admin/location/districts/22`
3. From that select the district you wish to get details for eg. for "Bishnupur" 
`https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=398&date=08-05-2021`

Hope this helps. If it did, help out the Devs and close the issue.

**Comment by p1sequaltonp** [comment]
@monish-1234 Sorry my bad, i missed that api. Thanks a lot :) .

**Comment by monish-1234** [comment]
> @monish-1234 Sorry my bad, i missed that api. Thanks a lot :) .

That's alright. It do be like that sometimes :)
