### ISSUE TITLE
Unable to access from servers hosted in US

### ISSUE THREAD

**Issue by nsriram** [cowinapi/developer.cowin#8]
I wanted to use the APIs on my application (https://chennai-zones.herokuapp.com), hosted in US. But the calls are restricted with 403, forbidden. I am able to access from my test app instances in India though. I tried from EU servers and they too are restricted with 403, forbidden. Can these be opened ?

**Comment by amitvsavant** [comment]
Yes, you are correct @nsriram. The APIs are currently geofenced to be used from India only. We will update if this changes in future.

**Comment by nsriram** [comment]
Ok. Can you please let us know the reason for restricting this information for servers accessing outside India ?

**Comment by avinassh** [comment]
@amitvsavant any info on rate limiters on the API?

**Comment by amitvsavant** [comment]
@avinassh the details have been added in the API description at [Co-WIN Public APIs](https://apisetu.gov.in/public/api/cowin)

**Comment by nsriram** [comment]
@amitvsavant when the rate limiting is so low, i.e., just 100 calls in 300 seconds (5mins), why restrict IPs from other places ?
As you may be aware many cloud providers are based out of India and if the APIs are truly meant to be open, for public consumption, why restrict ?

**Comment by nikhilkandur** [comment]
@amitvsavant - I was very happy when I got to know about Co-WIN public APIs.  I'm working towards pushing the community to vaccinate using them. It would be really great if you don't restrict non India region requests. The purpose of open APIs would be lost if we do region restriction. Could you expedite and remove them.

**Comment by satishchandra-pandey** [comment]
@nsriram @nikhilkandur 
These are government policies. This keeps on updating. We will notify you here in case of any changes in policy.
