### ISSUE TITLE
Enter Captcha field disabled on website while booking an appointment.

### ISSUE THREAD

**Issue by RohitSurwase** [cowinapi/developer.cowin#81]
Getting a free slot is itself a challenge and now on top of that when somehow we get a slot to book, the enter Captcha field does not allow us to enter anything. I could refresh the Captcha but can not enter it. This happened with me twice.
Please fix the issue.

**Comment by ashish-bargaje** [comment]
Also, sometimes upon entering valid Captcha and hitting 'Confirm' button doesn't validate anything and re-enables the 'Confirm' button without showing any error or display message.
