### ISSUE TITLE
Getting 403 Forbidden error from CloudFront Distribution

### ISSUE THREAD

**Issue by mowrishdev** [cowinapi/developer.cowin#83]
url : https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=600091&date=10-05-2021

When the above url is accessed via browser, I am getting a response from the server but when I am providing with a simple get request from my node app, I am getting 403 response code with status text as Forbidden and the following error response.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n' +
      '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n' +
      '<TITLE>ERROR: The request could not be satisfied</TITLE>\n' +
      '</HEAD><BODY>\n' +
      '<H1>403 ERROR</H1>\n' +
      '<H2>The request could not be satisfied.</H2>\n' +
      '<HR noshade size="1px">\n' +
      'Request blocked.\n' +
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n" +
      '<BR clear="all">\n' +
      'If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n' +
      '<BR clear="all">\n' +
      '<HR noshade size="1px">\n' +
      '<PRE>\n' +
      'Generated by cloudfront (CloudFront)\n' +
      'Request ID: EOONgsQb63D14ULCI7V_rvq4J8J2vkPCTElIovArAfMau1NDa74UXw==\n' +
      '</PRE>\n' +
      '<ADDRESS>\n' +
      '</ADDRESS>\n' +
      '</BODY></HTML>
```

**Comment by kaiwalyakhasnis** [comment]
I am facing similar issue

**Comment by mowrishdev** [comment]
@kaiwalyakhasnis I have found out the issue. Supply the request with a browser user-agent in the request headers.

**Comment by saran-surya** [comment]
Hello @mowrish , Kindly mention some user agents that work with Heroku servers :)

**Comment by mowrishdev** [comment]
The API provider has set-up user agent detection where requests from the browser are only accepted. So, it depends upon the User-Agent header value that you are sending along with the request and does not depend on the type of hosting servers. Below is an example for User-Agent value for chrome browser.

Chrome/51.0.2704.106

For more details on the same : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by darshani28** [comment]
@mowrish even after adding the correct user agent, i've always got 403 for schedule api. could it be because available_capacity of slot was 0? I'm also not using VPN

**Comment by saran-surya** [comment]
@darshani28 , you will still receive the data even if there are no slots, or vaccine capacity is 0, They have geo fenced it to Indian location, So that is causing the problem.

**Comment by saran-surya** [comment]
@mowrish I have tried using that on Heroku, and the problem was the location of the servers, so will try it with an Indian server and let you know

**Comment by mowrishdev** [comment]
@saran-surya Yes, you are right. It's because of the location of the servers. I have tested with UK and Indian servers by providing the user-agent. 
UK : 
![image](https://user-images.githubusercontent.com/10041770/117772837-3bca2580-b255-11eb-8349-657ba95882c5.png)

India :
![image](https://user-images.githubusercontent.com/10041770/117772881-484e7e00-b255-11eb-95f8-7e907f268486.png)

@darshani28 We have narrowed down the 403 Forbidden Request issue to User-Agent and Geo Location of the servers. Please provide us with much more info if these two are not the reasons for your issue.

**Comment by saran-surya** [comment]
@mowrish , These are the issues, I am currently working on a work round, will update you once i get the solution, And also could you suggest me some Indian servers for dev hosting

**Comment by darshani28** [comment]
> @saran-surya Yes, you are right. It's because of the location of the servers. I have tested with UK and Indian servers by providing the user-agent.
> UK :
> ![image](https://user-images.githubusercontent.com/10041770/117772837-3bca2580-b255-11eb-8349-657ba95882c5.png)
> 
> India :
> ![image](https://user-images.githubusercontent.com/10041770/117772881-484e7e00-b255-11eb-95f8-7e907f268486.png)
> 
> @darshani28 We have narrowed down the 403 Forbidden Request issue to User-Agent and Geo Location of the servers. Please provide us with much more info if these two are not the reasons for your issue.

@mowrish I'm getting 403 for schedule appointment api. slots' api returns information correctly if accessed via Indian location and user agent is added.

**Comment by mowrishdev** [comment]
@darshani28 Provide some more inputs to investigate further such as endpoint you are trying to access, complete request being sent.

**Comment by darshani28** [comment]
@mowrish  I am trying out appointment scheduling with endpoint api/v2/appointment/schedule.  Can we not use this public api for appointment scheduling?

**Comment by saran-surya** [comment]
@darshani28 , @mowrish I have come up with a workaround for this, You can use the package ***CASSATA*** , That will proxy the data to your server, for now it supports ***GET Requests*** and supports ***JSON***

[https://github.com/saran-surya/cassata](https://github.com/saran-surya/cassata)

**Comment by saran-surya** [comment]
you can use the package : 
### CASATA 🍥 , it's on npmJS
