### ISSUE TITLE
Unauthorised access (CONFIRM OTP)

### ISSUE THREAD

**Issue by ashkush** [cowinapi/developer.cowin#86]
Getting unauthenticated access while validating user with txnId and the opt generated?
Any help regarding this?

**Comment by vaibhavsingal96** [comment]
I have generally seen this when you the combination of OTP and txnId is wrong.
Or you maybe using the protected API and not public one

**Comment by ashkush** [comment]
Yeah, that was also there. But what I did wrong that is I was not using SHA256 encryption of the OTP received, for the authorisation. But most of the times the OTP is getting delayed that is why the combination of txnId and OTP are getting wrong.
