### ISSUE TITLE
usability question

### ISSUE THREAD

**Issue by bilal-fazlani** [cowinapi/developer.cowin#89]
If the data can be upto 30 mins old, given current gap in demand and supply, what purpose does this api serve? 
Alerts and booking will not happen since slots will be gone by the time api consumes data.

**Comment by theGeekyLad** [comment]
Since the CoWIN website as well consumes the same APIs, are they really differentiating the source of requests (`origin` or `referrer` or maybe CORS or something else) to serve 3rd parties with a rate limit?

More specifically, does the CoWIN portal also suffer from this rate limit?

**Comment by krishnaanaril** [comment]
@theGeekyLad There is no `public` route in the production API. e.g: `v2/appointment/sessions/calendarByDistrict`

**Comment by theGeekyLad** [comment]
@krishnaanaril the production APIs are deployed on `cdn-api.co-vin.in` and do have _public_ endpoints as well, e.g. `https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP`. But 3rd parties, as such, _"shouldn't"_ access these APIs without a specific auth param (and consent).

Does that imply that only _public_ endpoints are subject to rate limits and _non-public_ (or _protected_) endpoints (i.e. those used in the CoWIN portal) are not?
