### ISSUE TITLE
not able to book the second dose for 60+ elders on the same day

### ISSUE THREAD

**Issue by avgcoderlife** [cowinapi/developer.cowin#9]
Why I am not able to book same day appointments for my parents who are 60+ ? Where as I can see that few slots are present for the same day and those slots are giving at 8 AM the same day - How to book these for my parents ?

Strange thing is I can try to book for 18+ appointments on the same day but for my parents who are 60+ I need to book minimum 1 day in advance. It never shows the same day slots !

**Comment by animarawat** [comment]
Could you please share error screenshots for us to understand the precise issue?

**Comment by avgcoderlife** [comment]
![image](https://user-images.githubusercontent.com/2094882/116983825-2ea6b700-ace8-11eb-9b3d-c78b13b8cf29.png)
Today is May 4th

You can see that when I click on Schedule for second dose of 60+ , I can see only dates of tomorrow + (May 5th onwards)

**Comment by avgcoderlife** [comment]
This is what I ( 32 ) see in my Schedule option : 
I can book for the same day.

![image](https://user-images.githubusercontent.com/2094882/116984261-b8568480-ace8-11eb-82c2-bbd5b5f60054.png)

**Comment by avgcoderlife** [comment]
Impact due to this : Some private hospitals do not allow walkins for 60+ . they expect registrations. They open up reg only on the same day. saw so many 45+ slots on the same day but not able to book for my parents second dose as they can only see the tommorow + dates , not today ones !

**Comment by animarawat** [comment]
Please confirm if it has been minimum 28 days from dose 1 administration if you are trying to schedule appointment for your parents for dose 2.

**Comment by avgcoderlife** [comment]
Not just 28 days , its been 8 weeks :( Searching like hell from 2 weeks 

![image](https://user-images.githubusercontent.com/2094882/116985335-eee0cf00-ace9-11eb-8d5f-920fffcde5ca.png)
Hope this clears it up !

**Comment by animarawat** [comment]
Thank you for clarifying. Our development team will look into it.
