### ISSUE TITLE
APIs returning Forbidden while calling API via Postman and Browser

### ISSUE THREAD

**Issue by Ritwikjoshi** [cowinapi/developer.cowin#90]
<img width="893" alt="Screenshot 2021-05-08 at 12 25 31 PM" src="https://user-images.githubusercontent.com/20988024/117530001-7e42f680-aff8-11eb-9392-a70aa0a3e857.png">

**Comment by akshaymangaonkar** [comment]
Yeah. Facing the same issue.

**Comment by krishnaanaril** [comment]
Did you exceed 100 calls/5 min limit?

**Comment by geethesh-designway** [comment]
@Ritwikjoshi are you using any VPN?

**Comment by Ritwikjoshi** [comment]
No @geethesh-designway I'm not using any VPN. But I just figured out that it has to do something with my internet connection. I was facing this issue while I was connected to wifi but as soon as I switched to the mobile hotspot it started working.

@akshaymangaonkar you can also try changing your network.

**Comment by Inderpreetsingh11** [comment]
I tried changing my network. But it's still not working. Any idea @Ritwikjoshi ?

**Comment by Ritwikjoshi** [comment]
@Inderpreetsingh11 I don't have an exact idea why is it happening. It's not working for me when I'm trying to call it from an AWS server. But I can call if from my local machine using Postman or ever directly from the browser as well.
<img width="893" alt="Screenshot 2021-05-08 at 5 13 11 PM" src="https://user-images.githubusercontent.com/20988024/117537762-ac3c3100-b020-11eb-95e6-ef28f202e503.png">

**Comment by Rushabh5000** [comment]
> @Inderpreetsingh11 I don't have an exact idea why is it happening. It's not working for me when I'm trying to call it from an AWS server. But I can call if from my local machine using Postman or ever directly from the browser as well.
>

Hey, even I'm facing the same issue while trying to call it from GCP.. It seems locations out of India are not allowed to access these API's


![Screenshot (108)](https://user-images.githubusercontent.com/16048580/117539719-88311d80-b029-11eb-91fe-c3c9e66e6f73.png)

**Comment by Ritwikjoshi** [comment]
@Rushabh5000 But I'm accessing it from a server located in the Mumbai region on AWS...still facing the same issue

**Comment by abizerlokhandwala** [comment]
Locations out of India will receive 403 status codes. Try switching your server to Mumbai on AWS, it's working for me. Also, make sure you add a `User-Agent` header to your requests, otherwise, you will receive 403 errors.

**Comment by Rushabh5000** [comment]
> @Rushabh5000 But I'm accessing it from a server located in the Mumbai region on AWS...still facing the same issue

Then shouldn't be an issue

**Comment by Rushabh5000** [comment]
> Locations out of India will receive 403 status codes. Try switching your server to Mumbai on AWS, it's working for me. Also, make sure you add a `User-Agent` header to your requests, otherwise, you will receive 403 errors.

Any way to change location in GCP that you're aware of?

**Comment by abizerlokhandwala** [comment]
> @Rushabh5000 But I'm accessing it from a server located in the Mumbai region on AWS...still facing the same issue

Add `User-Agent` headers and try

**Comment by abizerlokhandwala** [comment]
> > Locations out of India will receive 403 status codes. Try switching your server to Mumbai on AWS, it's working for me. Also, make sure you add a `User-Agent` header to your requests, otherwise, you will receive 403 errors.
> 
> Any way to change location in GCP that you're aware of?

GCP has Mumbai as a region for their Compute Engines, check that out

**Comment by abizerlokhandwala** [comment]
> @Inderpreetsingh11 I don't have an exact idea why is it happening. It's not working for me when I'm trying to call it from an AWS server. But I can call if from my local machine using Postman or ever directly from the browser as well.
> <img alt="Screenshot 2021-05-08 at 5 13 11 PM" width="893" src="https://user-images.githubusercontent.com/20988024/117537762-ac3c3100-b020-11eb-95e6-ef28f202e503.png">

When calling it from your browser, the `User-Agent` headers are populated automatically. You'd have to do this on your own for requests through code. Try adding:
`headers = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"}`

**Comment by tharun518** [comment]
Same issue for my AWS server. IP seems to be getting blocked. Had to get new IP to make it working.

I was sending only 80 request per 10 mins with user agent. Still got blocked after a while.

**Comment by abizerlokhandwala** [comment]
Their rate limiting is a little sketchy, write code with the assumption that you might get random 403s

**Comment by tharun518** [comment]
Yes, it starts working again if we slow down. I was sending 80 requests all at once every 10 mins. Now I have scattered it across different times over period of 15 mins. Lets see how it goes.

**Comment by Inderpreetsingh11** [comment]
Hi @tharun518.. I’m a noob to all this. Could you please tell me what’s the meaning of sending 80 requests all at once?

**Comment by tharun518** [comment]
My script checks for slots for next 10 days and for multiple district at once. So total of 80 request when the script is executed in parallel.
