### ISSUE TITLE
using age as hard filter as input in the request

### ISSUE THREAD

**Issue by tavisca-dharminder** [cowinapi/developer.cowin#91]
why don't you take filters as hard filters or apply an auto filter based on the age of the person for which it is being scheduled?

**Comment by vaibhavsingal96** [comment]
The problem with this is, UI allows to select multiple people at once and they could be of mixed age groups.
First we'll have to add a UI check to not allow multi selection of different age group, only then we can have a filter by age

To clarify, I am also in support of filter by age requirement listed in this issue 👍
