### ISSUE TITLE
Some Pincodes no showing

### ISSUE THREAD

**Issue by sidB67** [cowinapi/developer.cowin#92]
On aarogaya setu vaccination checking i can see centers for 110092 but using this api i can not what is the issue

**Comment by monish-1234** [comment]
https://github.com/cowinapi/developer.cowin/issues/74#issuecomment-834680993

Check it out. 

If this helps, help the devs by closing the issue.

**Comment by monish-1234** [comment]
https://github.com/cowinapi/developer.cowin/issues/71#issuecomment-834755315

Hey ! @sidB67 check this out. 

If this helps you out , help out the devs by closing the Issue.
