### ISSUE TITLE
Merge members to one account 

### ISSUE THREAD

**Issue by Jkvivace** [cowinapi/developer.cowin#93]
How to merge members in two different account to single account in UI. 
So that both can book slot at same schedule..

**Comment by vaibhavsingal96** [comment]
Just register the members in one account. There's no check of registering same person in 2 different account :P

**Comment by Jkvivace** [comment]
@vaibhavsingal96 , thanks for your input. 
But it is not working as expected.. 
When I add member to other user, system generating new id. Which means I loose data about 1st dose :(

**Comment by Jkvivace** [comment]
We should have logic to add member based on member id.. Or match identification id ( aadhaar) and import old member...
