### ISSUE TITLE
FEATURE REQUEST - Only show/return Available sessions instead of ALL Sessions by District or Pin code

### ISSUE THREAD

**Issue by SehgalNeeraj** [cowinapi/developer.cowin#94]
@cowinapi 
The purpose is to find Available slots for people to book them.
We don't need Slots that are already filled up on the Search results or API's results

1. Show on Search page only "Available Slots" instead of showing Slots fille up / no availability
Show only Yellow/Green, user doesn't need to see Red

2. Modify API's for AVAILABLE vaccination sessions - just return data for centers with available slots (avalable_capacity > 0) in JSON instead of all sessions
[change response for / give corresponding Available session  API's]:
 ​/v2​/appointment​/sessions​/public​/calendarByDistrict
/v2/appointment/sessions/public/calendarByPin
/v2/appointment/sessions/public/findByPin
/v2/appointment/sessions/public/findByDistrict

**Comment by Jkvivace** [comment]
No ...., Filter them at client side..  people should know which hospitals are vaccinating... 

read this : https://github.com/cowinapi/developer.cowin/issues/71

**Comment by SehgalNeeraj** [comment]
> No ...., Filter them at client side.. people should know which hospitals are vaccinating...
> 
> read this : #71

ok - but not convinced how it helps to show which hospitals are vaccinating if they don't have available slots?
In fact, it's terrible UX if the available slots in the hospital are way down in the Search screen - at least can you bubble up the available slots hospitals to the top in search results?
Also, it will be great to see Total Slots (even if filled) as is shown when slots are available.

**Comment by vaibhavsingal96** [comment]
> how it helps to show which hospitals are vaccinating if they don't have available slots?

It shows that there might be slots available in future. It gives more confidence to user.
There should be a filter on UI for "available slots only" and that would solve your issue while maintaining transparency.

Showing all centres providing vaccination also portrays the efforts being put by the government and display the scale of vaccination drive

**Comment by vaibhavsingal96** [comment]
>  it will be great to see Total Slots (even if filled) as is shown when slots are available.

How will that help?

**Comment by SehgalNeeraj** [comment]
Please sort bubbling up available centers instead of 1 more filter on "available status" - the UI is getting cluttered and confusing.
Even if you give that filter everyone is only interested in available slots. I can say that as a user.
It does not give me confidence as a vaccine seeker if 100 hospitals are listed but none with available vaccine slots.

> > it will be great to see Total Slots (even if filled) as is shown when slots are available.
> 
> How will that help?

Gives confidence to the user that many vaccines were available in that center, giving transparency.

**Comment by durgeshsr** [comment]
My understanding was that /findByDistrict was doing this exact same availability filtering compared to /calendarbyDistrict?
If I check it for Mumbai on production server right now, /calendarByDistrict gives me few centers with 0 slots, whereas /findByDistrict for same district_id gives me empty results. In fact it was working in noon as well when find API was giving a single result where slots were available out of 122 centers (returned by calendar at around 2-30 PM).

**Comment by Giri-oss** [comment]
what are query filters supported for /findByDistrict?
"vaccine" and "min_age_limit" are valid query parameters to use some thing like https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=294&date=08-05-2021&vaccine=COVAXIN&min_age_limit=18

**Comment by SehgalNeeraj** [comment]
> what are query filters supported for /findByDistrict?
> "vaccine" and "min_age_limit" are valid query parameters to use some thing like https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=294&date=08-05-2021&vaccine=COVAXIN&min_age_limit=18

The Public API : /v2/appointment/sessions/public/findByDistrict takes only 2 parameters **district_id** and **date**

**Comment by vaibhavsingal96** [comment]
Bubbling up available centres at top is certainly a needed feature right now. It will surely ease the process for users
