### ISSUE TITLE
Status Code : 403 when trying to get data from the API

### ISSUE THREAD

**Issue by Inderpreetsingh11** [cowinapi/developer.cowin#95]
Tried using different internet connections but still getting the same status code.
Using python for this. 
Code
`import requests

response = requests.get('https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=132001&date=09-05-2021')`

Any idea guys.. why it is happening. I haven't exceeded the limit as well.

**Comment by Inderpreetsingh11** [comment]
Tried using different internet connections but still getting the same status code.

**Comment by pruthvip98** [comment]
adding a user-agent worked for me, which would look something like this:

response = requests.get(s, headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'})

**Comment by Harshit-9398** [comment]
When I add the **User-Agent** header, the response changes to **404**, else it comes **403**.

**Comment by mehulcse** [comment]
This is possibly because of throttling on their end. We have been getting this at [FindMySlots.com](https://www.findmyslots.com/) but not always.

**Comment by Rushabh5000** [comment]
> Tried using different internet connections but still getting the same status code.
> Using python for this.
> Code
> `import requests
> 
> response = requests.get('[https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=132001&date=09-05-2021')`](https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=132001&date=09-05-2021')%60)
> 
> Any idea guys.. why it is happening. I haven't exceeded the limit as well.

Hey, even I'm facing the same issue while trying to call it from GCP.. It seems locations out of India are not allowed to access these API's


![Screenshot (108)](https://user-images.githubusercontent.com/16048580/117539701-6d5ea900-b029-11eb-8f8e-578623495723.png)

**Comment by vaibhavsingal96** [comment]
I have only seen 2 major causes for 403
1. IP located outside India
2. Missing User-Agent header

Other than that, the API works in every case

**Comment by Inderpreetsingh11** [comment]
@pruthvip98 thanks for the help. Adding the user agent to it made it work.

**Comment by rajeshr6r** [comment]
I have added headers , rate limit within the threshold . Running on AWS ap-south-1 ( Mumbai ) . Yet no luck . Anybody facing this issue ? Strange fact : While inspecting the headers in the response , I feel the response is coming from another AWS server (CDN) implying that this infra is hosted on AWS . Not sure if my thought process is right .
