### ISSUE TITLE
No realtime slots being returned

### ISSUE THREAD

**Issue by Inderpreetsingh11** [cowinapi/developer.cowin#96]
Has anyone else facing this issue where the data returned by the API is nowhere to be found when a user goes to the self registration portal?

**Comment by mehulcse** [comment]
They have mentioned it here. 

The current data for the open APIs may have a lag of up to 30 minutes. 

https://apisetu.gov.in/public/marketplace/api/cowin#/

**Comment by MontuM** [comment]
I am not getting it either. As per the site, the lag will send us 30 min old data, but it should still send. Presently the API isn't returning anything.

**Comment by vaibhavsingal96** [comment]
@MontuM Can you share your request? The APIs are working fine for me

**Comment by Inderpreetsingh11** [comment]
@mehulcse the slots are getting filled in a matter of minutes. Will creating 3rd party apps even make sense if the data being returned is 30 mins old.?

**Comment by mehulcse** [comment]
@Inderpreetsingh11 Unfortunately, It doesn't make any sense as of now. Our team at [FindMySlots.com](https://github.com/FindMySlots/findmyslot) was working really hard to help people. We have created a web app, We were/are working on a chrome extension and mobile app to help people but may not be useful now. 

On the other side, I think folks at Co-win are also working day and night to support the world's largest vaccination drive and it is important to keep the bad actors in check. I believe this space is frequently changing and they will come out with some solution soon.

**Comment by MontuM** [comment]
> @MontuM Can you share your request? The APIs are working fine for me

Able to get the response now. For some 15-20 mins.  I wasn't getting any response. However, the delay isn't gonna help me much in what I was trying to do.

**Comment by ganmol123** [comment]
Trying this on postman: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=330&date=10-06-2021.
Response: {
    "sessions": []
}
Why is it returning empty sessions []? The response code is 200. I'm a bit noob but this should return something?

**Comment by Prankurtiwari** [comment]
@ganmol123 It may be possible that there is no session at the given district.
Also there is a cache of 30 mins so may be old data is displayed.

**Comment by Inderpreetsingh11** [comment]
As the API might have 30 mins delay, so my question is answered. Well kind of. Hence, closing it.
