### ISSUE TITLE
Provide latest data on calendarByDistrict and calendarByPin Public APIs or Trusted API key for these two APIs

### ISSUE THREAD

**Issue by mehulcse** [cowinapi/developer.cowin#97]
There are a lot of notification systems have popped up to help people in these tough times. We have created a similar system [findmyslots.com](https://www.findmyslots.com/). 

In addition to the web app we have a Chrome extension and a mobile application in progress with some degree of localization to help the larger audience and to save them from the pain of checking this frequently. 

The caching on this API have really destroyed the purpose of such apps. It's true that there are some bad actors, but I believe as Co-Win have added certain security aspects like captcha token expiry in 15 minutes have helped to reduce those unauthorized usages. 

Can you please consider reducing or removing the cache timing or provide a way to obtain API key just to access these 2 APIs `calendarByDistrict` and `calendarByPin`? This will help a larger audience and rescue them from the pain of checking the platform frequently?

**Comment by gopal-amlekar** [comment]
Cowin website seems to use a different route (v2/appointment/sessions/**calendarByPin**) than the one listed on apisetu.gov.in/ (​/v2​/appointment​/sessions​/**public​/findByPin**). 

Also the **calendarByPin** route sometimes responds with 401 but not always. Perhaps it is supposed to return 429 but returns 401 maybe.

**Comment by lyveng** [comment]
> There are a lot of notification systems have popped up to help people in these tough times. We have created a similar system [findmyslots.com](https://www.findmyslots.com/).
> 
> In addition to the web app we have a Chrome extension and a mobile application in progress with some degree of localization to help the larger audience and to save them from the pain of checking this frequently.
> 
> The caching on this API have really destroyed the purpose of such apps. It's true that there are some bad actors, but I believe as Co-Win have added certain security aspects like captcha token expiry in 15 minutes have helped to reduce those unauthorized usages.
> 
> Can you please consider reducing or removing the cache timing or provide a way to obtain API key just to access these 2 APIs `calendarByDistrict` and `calendarByPin`? This will help a larger audience and rescue them from the pain of checking the platform frequently?

For some reason, the twitter bot [@BloreVaccine](https://twitter.com/BloreVaccine) seems to be returning non-stale data. Even when I call the api with authorization header set as suggested [here](https://github.com/cowinapi/developer.cowin/issues/131#issuecomment-836716211), I receive the update(through polling every 5s) only after almost 1 minute. In fact the update that I receive has the availability filled in as 0 while the twitter bot showed availability of 100. So there seems to be some workaround that the twitter bot is using. Just not sure what.

**Comment by gopal-amlekar** [comment]
> For some reason, the twitter bot [@BloreVaccine](https://twitter.com/BloreVaccine) seems to be returning non-stale data. Even when I call the api with authorization header set as suggested [here](https://github.com/cowinapi/developer.cowin/issues/131#issuecomment-836716211), I receive the update(through polling every 5s) only after almost 1 minute. In fact the update that I receive has the availability filled in as 0 while the twitter bot showed availability of 100. So there seems to be some workaround that the twitter bot is using. Just not sure what.

That is a mystery. Even I observed today that I got notification on that Twitter bot for 100 slots at a hospital. I logged in and saw 98 slots, which was great. So I proceeded to book it but the slots vanished by the time I confirmed the booking. Only 2 to 3 people on that Twitter thread responded that they succeeded in booking the slot. So perhaps there are many such '**real-time**' bots.
