### ISSUE TITLE
Error in aadhar card number in final certificate 

### ISSUE THREAD

**Issue by kalps02** [cowinapi/developer.cowin#98]
How to change my aadhar card number on my final vaccine certificate.Cowin app should allow functions to correct the mistakes by beneficiaries.Where you can scan your original proof and get it corrected in your certificate?

**Comment by yogesharora3** [comment]
when you enter aadhar card number it not validating whether it's a valid aadhar card number or not.

**Comment by kalps02** [comment]
It’s not validating as my aadhar card.But I have got vaccinated and while
taking the second dose the vaccinator brought this into my notice and even
my middle name is wrong.I would like to rectify the mistake in my final
certificate.
Thank you

**Comment by kalps02** [comment]
Please add a function in cowin so that beneficiaries can make changes in the certificate by providing the proof.scan the proof and let them make changes.Their are a lot of people who must have made mistakes.

**Comment by kalps02** [comment]
I made changes in the final certificate but the system was down and it got
denied.and only once you can make changes.please look into it the matter
